--[[--------------------------------------------------
003_Horde_40to50.lua
Authors: mrmr, lanjelin
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 40 to Lvl 50
    1.04.1
        -- First Release
            Horde's Guide
            from level 40 to lever 50
    1.04.2
    	-- no changes in here for this revision
    1.04.3
	    -- Cleanup in text, changed formatting of coords
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Horde_40to50 = {
-----------40-41 Badlands
	--[401] = {
	[4041] = {
		title = "40-41 Badlands",
		--n = "40-41 Badlands",
		--pID = 311, nID = 402,
		--itemCount = 29,
		items = {
			[1] = { str = "40-41 Badlands" },
			[2] = { str = "The goal here is not to leave till your level 41, so grind mobs every where you go to...As you enter Badlands, run southwest to [42,52]...", x = 42, y = 52, zone = "Badlands" },
			[3] = { str = "Turn in #TURNINMartek the Exiled# at [42,52] ... accept #ACCEPTIndurium# and #ACCEPTBarbecued Buzzard Wings# ", x = 42, y = 52, zone = "Badlands" },
			[4] = { str = "Go down south a little and do #DOQUESTIndurium# [51,67]", x = 51, y = 67, zone = "Badlands" },
			[5] = { str = "Go back up and turn #TURNINIndurium# in ... accept #ACCEPTNews for Fizzle# " },
			[6] = { str = "Then go north-west and accept #ACCEPTStudy of the Elements: Rock# at [25,44].  #VIDEONOTE:# If you have the #NPCFrost Oil#, the #NPCGyrochronatom#, the #NPCHealing Potion#, the #NPCLesser Invisibility Potion# and the #NPCPatterned Bronze Bracers# items, accept and complete all the quests there.", x = 25, y = 44, zone = "Badlands" },
			[7] = { str = "Grind your way west to Kargath [04,46]...", x = 4, y = 46, zone = "Badlands" },
			[8] = { str = "Get FP at Kargath." },
			[9] = { str = "Do NOT make Kargath your home. (it should still be BB)" },
			[10] = { str = "Accept: #ACCEPTCoyote Thieves# #ACCEPTReport to Helgrum# #ACCEPTBroken Alliances# and #ACCEPTBadlands Reagent Run# " },
			[11] = { str = "Then go do:" },
			[12] = { str = "#DOQUESTBarbecued Buzzard Wings# " },
			[13] = { str = "#DOQUESTCoyote Thieves# " },
			[14] = { str = "#DOQUESTBroken Alliances# (skip the next part to this quest)" },
			[15] = { str = "#DOQUESTBadlands Reagent Run# " },
			[16] = { str = "#DOQUESTStudy of the Elements: Rock# (#NPClesser rock elementals#), turn in, then do..." },
			[17] = { str = "#DOQUESTStudy of the Elements: Rock# (#NPCrock elementals#), turn in, then do..." },
			[18] = { str = "#DOQUESTStudy of the Elements: Rock# (#NPCgreater rock elementals#)" },
			[19] = { str = "Then make sure all Badlands quests (besides #ACCEPTReport to Helgrum# ) are done and turned in." },
			[20] = { str = "You should be about level 41 right now, if not grind to it." },
			[21] = { str = "Hearth to BB and check if you have #DOQUESTDream Dust in the Swamp# in your questlog. If not, go accept it from Krazek at [27,77]", x = 27, y = 77, zone = "Stranglethorn Vale" },
			[22] = { str = "Fly to Grom'gol." },
			[23] = { str = "Go turn in all the #NPCThe Green Hills of Stranglethorn Chapters/Quests# at Nesingwary's Expedition [35,10] if you have all the pages for it, if not you have another chance to turn this in again later.  You can also look in the AH for your missing pages.", x = 35, y = 10, zone = "Badlands" },
			[24] = { str = "Then run all the way to Swamp of Sorrows, stopping along the way to accept this quest: #ACCEPTNothing But the Truth#, in Duskwood at [87,35]", x = 87, y = 35, zone = "Duskwood" },
			[25] = { str = "Then turn in #TURNINNothing But the Truth# (the guy right next to him)" },
			[26] = { str = "#ACCEPTNothing But the Truth# again" },
			[27] = { str = "Then run into Swamp of Sorrows..." },
			--[28] = { str = "." },
			--[29] = { str = "." },
		}
	},

-----------41-42 Swamp of Sorrows
	--[402] = {
	[4142] = {
		title = "41-42 Swamp of Sorrows",
		--n = "41-42 Swamp of Sorrows",
		--pID = 401, nID = 403,
		--itemCount = 27,
		items = {
			[1] = { str = "41-42 Swamp of Sorrows" },
			[2] = { str = "Start off doing: #DOQUESTDream Dust in the Swamp# [14,59] It may take several trips to that area to complete it..", x = 14, y = 59, zone = "Swamp of Sorrows" },
			[3] = { str = "#DOQUESTNothing But the Truth#  kill the Mire Lord for the Mire Lord Fungus (at 6.32)", x = 6, y = 32, zone = "Swamp of Sorrows" },
			[4] = { str = "Find and kill #NPCCudgel#, he drops Noboru's Cudgel, which starts #ACCEPTNoboru the Cudgel# " },
			[5] = { str = "Go turn in #TURNINNoboru the Cudgel# [25,31] ... accept #ACCEPTDraenethyst Crystals# ", x = 25, y = 31, zone = "Swamp of Sorrows" },
			[6] = { str = "Grind to Stonard [45,54]", x = 45, y = 54, zone = "Swamp of Sorrows" },
			[7] = { str = "Make Stonard your home." },
			[8] = { str = "Accept #ACCEPTLack of Surplus# and #ACCEPT#NPCFresh Meat# " },
			[9] = { str = "Get FP." },
			[10] = { str = "Turn in #TURNINReport to Helgrum# ... accept #ACCEPTPool of Tears# (Elite)" },
			[11] = { str = "Go do the following quests:" },
			[12] = { str = "#DOQUESTPool of Tears# (the artifacts are in the water around temple of atal'hakkar)" },
			[13] = { str = "#DOQUESTLack of Surplus# then turn it in at [81,80] ... accept #ACCEPTLack of Surplus# part2 and go do it", x = 81, y = 80, zone = "Swamp of Sorrows" },
			[14] = { str = "Go do #DOQUESTFresh Meat# and #DOQUESTNothing But the Truth# (#NPCShadow Panthers#' hearts) " },
			[15] = { str = "#DOQUESTDraenethyst Crystals# then turn it in at [25,31]", x = 25, y = 31, zone = "Swamp of Sorrows" },
			[16] = { str = "#DOQUESTOngeku# " },
			[17] = { str = "Turn in #TURNINLack of Surplus# part2 ... accept #ACCEPTThreat From the Sea#" },
			[18] = { str = "Turn in #TURNINThreat From the Sea# then accept #ACCEPTThreat From the Sea# again" },
			[19] = { str = "Go do #DOQUESTThreat From the Sea# along with #DOQUESTFresh Meat# " },
			[20] = { str = "Turn in #TURNINThreat From the Sea# ... accept #ACCEPTContinued Threat# " },
			[21] = { str = "Go do #DOQUESTContinued Threat# then turn it in." },
			[22] = { str = "Hearth to Stonard." },
			[23] = { str = "Turn in #TURNINFresh Meat# and #TURNINPool of Tears# ... accept #ACCEPTThe Atal'ai Exile# " },
			[24] = { str = "Should be about lvl 42 now, if not grind to it.  #HUNTERGet new hunter spells/abilities.#" },
			[25] = { str = "Fly to Grom'gol..." },
			--[26] = { str = "." },
			--[27] = { str = "." },
		}
	},

-----------42-43 Stranglethorn Vale
	--[403] = {
	[4243] = {
		title = "42-43 Stranglethorn Vale",
		--n = "42-43 Stranglethorn Vale",
		--pID = 402, nID = 404,
		--itemCount = 23,
		items = {
			[1] = { str = "42-43 Stranglethorn Vale" },
			[2] = { str = "Accept #ACCEPTMok'thardin's Enchantment# part4 and #ACCEPTSplit Bone Necklace# " },
			[3] = { str = "Fly to BB" },
			[4] = { str = "Accept ALL quests in BB: #ACCEPTThe Bloodsail Buccaneers# #ACCEPTUp to Snuff# #ACCEPTFool's Stout# #ACCEPTAkiris by the Bundle# #ACCEPTVoodoo Dues# #ACCEPTStoley's Debt# #ACCEPTStranglethorn Fever# and #ACCEPTKeep An Eye Out#" },
			[5] = { str = "Turn in #TURNINDream Dust in the Swamp# " },
			[6] = { str = "Make BB your home." },
			[7] = { str = "Then go do in the following order:" },
			[8] = { str = "#DOQUESTThe Bloodsail Buccaneers# along with #DOQUESTUp to Snuff# and #DOQUESTKeep An Eye Out# These are done at the shore around [31,80], and some more mobs can be found at [27,70].  Also do #DOQUESTStranglethorn Fever# for #DOQUESTStranglethorn Fever# you will need 10x Gorilla Fang, and the witch doctor is in the cave at [34,60]", x = 31, y = 80, zone = "Stranglethorn Vale" },
			[9] = { str = "#DOQUESTMok'thardin's Enchantment# part4 along with #DOQUESTAkiris by the Bundle# [25,63]", x = 25, y = 63, zone = "Stranglethorn Vale" },
			[10] = { str = "Do #DOQUESTFool's Stout# along with #DOQUESTVoodoo Dues# [34,52] and [39,58]", x = 34, y = 52, zone = "Stranglethorn Vale" },
			[11] = { str = "Do #DOQUESTSkullsplitter Tusks# along with #DOQUESTSplit Bone Necklace# at [46,42]", x = 46, y = 42, zone = "Stranglethorn Vale" },
			[12] = { str = "I keep grinding away at Skullsplitter trolls until im at least 2-3 bars away from 43." },
			[13] = { str = "Hearth to BB" },
			[14] = { str = "Turn in ALL quests and make sure to accept #ACCEPTTran'Rek# and #ACCEPTRumors for Kravel# from Krazek and  #ACCEPTWhiskey Slim's Lost Grog# from Whiskey Slim" },
			[15] = { str = "Fly to Grom'gol " },
			[16] = { str = "Turn in #TURNINMok'thardin's Enchantment# part4 and #TURNINSplit Bone Necklace# " },
			[17] = { str = "Accept #ACCEPTGrim Message#" },
			[18] = { str = "Get on the zeppelin to Orgrimmar" },
			[19] = { str = "Once there go to Belgrom Rockmaul at [75,34] and accept #ACCEPTA Threath in Ferelas#", x = 75, y = 34, zone = "Orgrimmar" },
			[20] = { str = "Fly to Thunder Bluff" },
			[21] = { str = "Turn in #TURNINFrostmaw# ... accept #ACCEPTDeadmire# (hint: i usually keep Frostmaw's mane in my bank for a long time)" },
			[22] = { str = "Fly to Desolace if you're not 4/5 bars into lvl 43 or Dustwallow Marsh if you're." },
			--[22] = { str = "." },
			--[23] = { str = "." },
		}
	},

-----------43-43 Desolace
	--[404] = {
	[4342] = {
		title = "43-43 Desolace",
		--n = "43-43 Desolace",
		--pID = 403, nID = 405,
		--itemCount = 16,
		items = {
			[1] = { str = "43-43 Desolace" },
			[2] = { str = "OPTIONAL: This whole section can be skipped if you are 4-5 blocks or more into lvl 43, it would not hurt to skip this section and go straight to Dustwallow Marsh." },
			[3] = { str = "Make Shadowprey Village your home." },
			[4] = { str = "Accept #ACCEPTPortals of the Legion# " },
			[5] = { str = "Go turn in #TURNINOngeku# at [36,79] ... SKIP #NPCKhan Jehn# ", x = 36, y = 79, zone = "Desolace" },
			[6] = { str = "While your in Desolace, keep an eye out for an Elite Giant for the quest #NPCNothing But the Truth#..." },
			[7] = { str = "...if you don’t find the giant and get the #NPCDeepstrider Tumor#, then the quest will have to be abandoned, i don’t spend time going all over looking for a deepstrider gaint." },
			[8] = { str = "Then go to Mannoroc Coven at [50,76] and do:", x = 50, y = 76, zone = "Desolace" },
			[9] = { str = "#DOQUESTPortals of the Legion# " },
			[10] = { str = "#DOQUESTThe Corrupter# (Elite) (Slay #NPCLord Azrethoc# and #NPCJugkar Grim'rod#)" },
			[11] = { str = "Turn in #TURNINThe Corrupter# (Elite) at [53,54]", x = 53, y = 54, zone = "Desolace" },
			[12] = { str = "Then hearth to Shadowprey Village" },
			[13] = { str = "Turn in #TURNINPortals of the Legion# " },
			[14] = { str = "Fly to TB, then to Dustwallow Marsh..." },
			--[15] = { str = "." },
			--[16] = { str = "." },
		}
	},

-----------43-43 Dustwallow Marsh
	--[405] = {
	[4343] = {
		title = "43-43 Dustwallow Marsh",
		--n = "43-43 Dustwallow Marsh",
		--pID = 404, nID = 406,
		--itemCount = 14,
		items = {
			[1] = { str = "43-43 Dustwallow Marsh" },
			[2] = { str = "Accept #ACCEPTIdentifying the Brood# " },
			[3] = { str = "Go down to [40,36] and accept #DOQUESTQuestioning Reethe# then do it.", x = 40, y = 36, zone = "Dustwallow Marsh" },
			[4] = { str = "Go down and do:" },
			[5] = { str = "#DOQUESTDeadmire# " },
			[6] = { str = "#DOQUESTMarg Speaks# Kill the mobs at around [58,63]", x = 58, y = 63, zone = "Dustwallow Marsh" },
			[7] = { str = "#DOQUESTIdentifying the Brood# " },
			[8] = { str = "Then grind your way back to Brackenwall Village" },
			[9] = { str = "Turn in #TURNINQuestioning Reethe# and #TURNINIdentifying the Brood# ... accept #ACCEPTThe Brood of Onyxia# " },
			[10] = { str = "Run back and forth until #DOQUESTThe Brood of Onyxia# is done, but don't actually do the final quest yet (this will be done later at #NPClevel 48#, so you can abandon it for now)." },
			[11] = { str = "Turn in #TURNINMarg Speaks# ... accept #ACCEPTReport to Zor# " },
			[12] = { str = "Fly to Tanaris..." },
			--[13] = { str = "." },
			--[14] = { str = "." },
		}
	},

-----------43-44 Tanaris
	--[406] = {
	[4344] = {
		title = "43-44 Tanaris",
		--n = "43-44 Tanaris",
		--pID = 405, nID = 407,
		--itemCount = 36,
		items = {
			[1] = { str = "43-44 Tanaris" },
			[2] = { str = "Go into Gadgetzan..." },
			[3] = { str = "Accept: #ACCEPTWANTED: Caliph Scorpidsting# and #ACCEPTWANTED: Andre Firebeard#   (Wanted Poster)" },
			[4] = { str = "Turn in #TURNINTran'Rek# " },
			[5] = { str = "Accept: #ACCEPTGadgetzan Water Survey# #ACCEPTWastewander Justice# and #ACCEPTWater Pouch Bounty# " },
			[6] = { str = "Make Gadgetzan your home." },
			[7] = { str = "Go to the Shimmering Flats in Thousand Needles, at [78,77] and turn in #TURNINRumors for Kravel# #TURNINNews for Fizzle# and #TURNINRazzeric's Tweaking# ... accept #ACCEPTSafety First# ", x = 53, y = 76, zone = "Tanaris" },
			[8] = { str = "Accept #ACCEPTKeeping Pace# " },
			[9] = { str = "Turn #TURNINKeeping Pace# in at Zamek, then go pick up Rizzle's Plans at [77,77] ... accept #ACCEPTRizzle's Schematics# " },
			[10] = { str = "Accept #ACCEPTBack to Booty Bay# (at Kravel Koalbeard)" },
			[11] = { str = "Go turn in #TURNINRizzle's Schematics# at Pozzik." },
			[12] = { str = "Hearth back to Gadgetzan." },
			[13] = { str = "Turn in #TURNINSafety First# ... i SKIP the next part to this quest." },
			[14] = { str = "Then grind your way east to Steamwheedle Port. [67,23]", x = 67, y = 23, zone = "Tanaris" },
			[15] = { str = "Accept: #ACCEPTPirate Hats Ahoy!# #ACCEPTScreecher Spirits# and #ACCEPTSouthsea Shakedown# " },
			[16] = { str = "Turn in #TURNINStoley's Debt# ... accept #ACCEPTStoley's Shipment# " },
			[17] = { str = "Then go complete these quests:" },
			[18] = { str = "#DOQUESTWastewander Justice# along with #DOQUESTWater Pouch Bounty# at [64,29]", x = 64, y = 29, zone = "Tanaris" },
			[19] = { str = "Then go do all of the following (steps 19 - 23) at Lost Rigger Cove [72,47]:", x = 72, y = 47, zone = "Tanaris" },
			[20] = { str = "#DOQUESTSouthsea Shakedown# " },
			[21] = { str = "#DOQUESTPirate Hats Ahoy!# " },
			[22] = { str = "#DOQUESTStoley's Shipment# " },
			[23] = { str = "#DOQUESTShip Schedules# (find this in one of the #NPCPirate's footlocker# at Lost Rigger Cove.  If the item cannot be found, just skip it)" },
			[24] = { str = "#DOQUESTWANTED: Andre Firebeard# " },
			[25] = { str = "Once they're all done, hearth to Gadgetzan." },
			[26] = { str = "Turn in #TURNINWater Pouch Bounty# #TURNINWastewander Justice# ... accept #ACCEPTMore Wastewander Justice# " },
			[27] = { str = "Go do #DOQUESTGadgetzan Water Survey# Grinding mobs along the way, coords are at [38,29], then go back and turn it in.", x = 38, y = 29, zone = "Tanaris" },
			[28] = { str = "Go to Steamwheedle Port." },
			[29] = { str = "Turn in ALL quests there ... accept #ACCEPTDeliver to MacKinley# " },
			[30] = { str = "Then go do: #DOQUESTMore Wastewander Justice# along with #DOQUESTWANTED: Caliph Scorpidsting# [59,37]", x = 59, y = 37, zone = "Tanaris" },
			[31] = { str = "Then hearth to Gadgetzan.  Make sure you save (put in your bank) all the Wastewander Water Pouches you have, because you will need them for a later quest." },
			[32] = { str = "Turn in #TURNINMore Wastewander Justice# and #TURNINWANTED: Caliph Scorpidsting# " },
			[33] = { str = "Fly to Freewind Post." },
			[34] = { str = "Run west into Feralas..." },
			--[35] = { str = "." },
			--[36] = { str = "." },
		}
	},

-----------44-46 Feralas
	--[407] = {
	[4446] = {
		title = "44-46 Feralas",
		--n = "44-46 Feralas",
		--pID = 406, nID = 408,
		--itemCount = 51,
		items = {
			[1] = { str = "44-46 Feralas" },
			[2] = { str = "Run into Camp Mojache. [75,44]", x = 75, y = 44, zone = "Feralas" },
			[3] = { str = "Accept ALL quests there: #ACCEPTA New Cloak's Sheen# #ACCEPTThe Ogres of Feralas# #ACCEPTGordunni Cobalt# #ACCEPTWar on the Woodpaw# #ACCEPTThe Mark of Quality# #ACCEPTA Strange Request# " },
			[4] = { str = "Get FP." },
			[5] = { str = "Make Camp Mojache your home." },
			[6] = { str = "Then go do in the following order:" },
			[7] = { str = "#DOQUESTWar on the Woodpaw# go just north of Camp Mojache to do this. [71,37]", x = 71, y = 37, zone = "Feralas" },
			[8] = { str = "#DOQUESTThe Ogres of Feralas# along with #DOQUESTGordunni Cobalt# [75,31]", x = 75, y = 31, zone = "Feralas" },
			[9] = { str = "Make sure you click on one of the scrolls laying on the ground which starts: #ACCEPTThe Gordunni Scroll# " },
			[10] = { str = "Then go do: #DOQUESTA New Cloak's Sheen# [67,48]", x = 67, y = 48, zone = "Feralas" },
			[11] = { str = "Go back to Camp Mojache, turn in ALL those quests, accept all new quests." },
			[12] = { str = "Go do #DOQUESTAlpha Strike# at [72,56] then turn it in. ... accept #ACCEPTWoodpaw Investigation# ", x = 72, y = 56, zone = "Feralas" },
			[13] = { str = "Go do #DOQUESTWoodpaw Investigation# at [71,55] complete it ... accept #ACCEPTThe Battle Plans# ", x = 71, y = 55, zone = "Feralas" },
			[14] = { str = "Then go do #DOQUESTA Grim Discovery# [66,46]", x = 66, y = 46, zone = "Feralas" },
			[15] = { str = "Hearth back to Camp Mojache, turn in #TURNINThe Battle Plans# and #TURNINA Grim Discovery# , accept ALL new quests." },
			[16] = { str = "PLEASE NOTE:  If the 'OOX-22/FE Distress Beacon' item drops, accept the quest #ACCEPTFind OOX-22/FE!# .  Turn in #TURNINFind OOX-22/FE!# at [53,55].  Then go do:", x = 53, y = 55, zone = "Feralas" },
			[17] = { str = "#DOQUESTStinglasher# along with #DOQUESTZukk'ash Infestation# [74,62]", x = 74, y = 62, zone = "Feralas" },
			[18] = { str = "#DOQUESTScreecher Spirits# [55,56]", x = 55, y = 56, zone = "Feralas" },
			[19] = { str = "#DOQUESTThe Ogres of Feralas# part2 [59,68]", x = 59, y = 68, zone = "Feralas" },
			[20] = { str = "#VIDEONOTE:#  While in this area, make sure you pick up a #NPCHippogryph Egg# down south-west around [55,76], this will be turned in at Tanaris for a later #NPCquest#.", x = 53, y = 76, zone = "Feralas" },
			[21] = { str = "#DOQUESTDark Ceremony# [59,68]", x = 59, y = 68, zone = "Feralas" },
			[22] = { str = "#DOQUESTThe Mark of Quality# [53,55]", x = 53, y = 55, zone = "Feralas" },
			[23] = { str = "Run back to Camp Mojache, then go turn those quests in, accept all new quests just from those quest givers. " },
			[24] = { str = "Then do the following (If you have 90+ gold, go buy your mount! You should have them by now...):" },
			[25] = { str = "Fly to Orgrimmar..." },
			[26] = { str = "Make sure to get 120 Silk Cloths and 120 Mageweave out from either your bank or mailbox. For those of you who can't add, that's 6 stacks of 20 for both Silk and Mageweave." },
			[27] = { str = "Then go turn in: #TURNINZukk'ash Report# [56,46]", x = 56, y = 46, zone = "Orgrimmar" },
			[28] = { str = "Go complete #DOQUESTA Donation of Silk# and #DOQUESTA Donation of Mageweave# at [63,51]", x = 63, y = 51, zone = "Orgrimmar" },
			[29] = { str = "Accept #ACCEPTRipple Recovery# (from Dran Droffers) [59,36]", x = 59, y = 36, zone = "Orgrimmar" },
			[30] = { str = "Then turn in #TURNINRipple Recovery# (the guy right next to Dran) ... accept #ACCEPTRipple Recovery# again." },
			[31] = { str = "Turn in #TURNINParts of the Swarm# and #TURNINA Grim Discovery# at #NPCBelgrom Rockmaul#... accept #ACCEPTBetrayed# [75,34].  Also get new spells/abilities while you are in Orgrimmar.", x = 75, y = 34, zone = "Orgrimmar" },
			[32] = { str = "Go turn in #TURNINA Strange Request# ... Accept #ACCEPTRetrun to Witch Doctor Uzer'i# in Cleft of Shadow, [49,50]", x = 49, y = 50, zone = "Orgrimmar" },
			[33] = { str = "Go turn in #ACCEPTReport to Zor# ... accept/complete #DOQUESTService to the Horde# in Valley of Wisdom, [38,38]", x = 38, y = 38, zone = "Orgrimmar" },
			[34] = { str = "Go turn in #TURNINThe Gordunni Orb# in Valley of Spirits, [39,86]", x = 39, y = 86, zone = "Orgrimmar" },
			[35] = { str = "Turn in #TURNINA Donation of Silk# and #TURNINA Donation of Mageweave# for the troll faction, at [37,87]", x = 37, y = 87, zone = "Orgrimmar" },
			[36] = { str = "Now, before hearting back to Ferelas, go Durotar and buy your mount!" },
			[37] = { str = "Turn in #TURNINRetrun to Witch Doctor Uzer'i# ... accept #ACCEPTNatural Materials# and #ACCEPTTesting the Vessel# " },
			[38] = { str = "Then do #DOQUESTNatural Materials# " },
			[39] = { str = "Grind away at hippogryphs till it's completed." },
			[40] = { str = "If the #NPCOOX-22/FE Distress Beacon# item drops, accept the quest #ACCEPTFind OOX-22/FE!# " },
			[41] = { str = "Turn in #TURNINFind OOX-22/FE!# at [51,57]", x = 51, y = 57, zone = Ferelas },
			[42] = { str = "If your not level 46, grind till you are on hippogryphs.." },
			[43] = { str = "Hearth back to Camp Mojache." },
			[44] = { str = "Turn #TURNINNatural Materials# in ... accept #ACCEPTThe Sunken Temple# " },
			[45] = { str = "Fly to Thunder Bluff" },
			[46] = { str = "Turn in #TURNINDeadmire# " },
			[47] = { str = "Get new spells/abilites." },
			[48] = { str = "Fly to XRs, then to Splintertree Post (Ashenvale)" },
			[49] = { str = "Then go east into Azshara..." },
			--[50] = { str = "." },
			--[51] = { str = "." },
		}
	},

-----------46-46 Azshara
	--[408] = {
	[4646] = {
		title = "46-46 Azshara",
		--n = "46-46 Azshara",
		--pID = 407, nID = 409,
		--itemCount = 16,
		items = {
			[1] = { str = "46-46 Azshara" },
			[2] = { str = "Go accept #DOQUESTSpiritual Unrest# and #DOQUESTA Land Filled with Hatred# at [10,78]", x = 10, y = 78, zone = "Azshara" },
			[3] = { str = "Then go do them at [17,66] and [20,62], and turn them in.", x = 17, y = 66, zone = "Azshara" },
			[4] = { str = "Then go to Valormok at [21,52]", x = 21, y = 52, zone = "Azshara" },
			[5] = { str = "Turn in #TURNINBetrayed# (skip the next part to this quest for now)" },
			[6] = { str = "Then get FP there and fly to Orgrimmar." },
			[7] = { str = "Then head to Under City." },
			[8] = { str = "Then go to Magic Quarter and accept #ACCEPTLines of Communication# " },
			[9] = { str = "Head to Apothecarium Quarter and accept: #ACCEPTSeeping Corruption# and #ACCEPTErrand for Apothecary Zinge# " },
			[10] = { str = "Then go turn in #ACCEPTErrand for Apothecary Zinge# (out in the other room)" },
			[11] = { str = "Go return back, and turn in #TURNINErrand for Apothecary Zinge# again ... accept #ACCEPTInto the Field# " },
			[12] = { str = "You can put the 'Field Testing Kit' and the 'Box of Empty Vials' in the Bank for now." },
			[13] = { str = "Fly to Tarren Mill and make it your home." },
			[14] = { str = "Head to the Hinterlands. There a passage at around [83,33]", x = 83, y = 33, zone = "Hillsbard Foothills" },
			--[15] = { str = "." },
		}
	},

-----------46-47 Hinterlands
	--[409] = {
	[4647] = {
		title = "46-47 Hinterlands",
		--n = "46-47 Hinterlands",
		--pID = 408, nID = 410,
		--itemCount = 38,
		items = {
			[1] = { str = "46-47 Hinterlands" },
			[2] = { str = "Go turn in #TURNINRipple Recovery# at [27,49] ... accept #ACCEPTA Sticky Situation# ", x = 27, y = 49, zone = "Hinterlands" },
			[3] = { str = "Ride all the way to Revantusk Village at [77,80]", x = 77, y = 80, zone = "Hinterlands" },
			[4] = { str = "Accept: #ACCEPTVilebranch Hooligans#, #ACCEPTCannibalistic Cousins#, #ACCEPTMessage to the Wildhammer#, #ACCEPTStalking the Stalkers#, #ACCEPTHunt the Savages# and #ACCEPTAvenging the Fallen# " },
			[5] = { str = "Then go do the following:" },
			[6] = { str = "#DOQUESTWhiskey Slim's Lost Grog# " },
			[7] = { str = "#DOQUESTVilebranch Hooligans# " },
			[8] = { str = "#DOQUESTCannibalistic Cousins# " },
			[9] = { str = "#DOQUESTA Sticky Situation# turn in later ... accept #ACCEPTRipple Delivery# " },
			[10] = { str = "#DOQUESTStalking the Stalkers# " },
			[11] = { str = "#DOQUESTHunt the Savages# " },
			[12] = { str = "#DOQUESTTesting the Vessel# " },
			[13] = { str = "#DOQUESTAvenging the Fallen# " },
			[14] = { str = "#DOQUESTLines of Communication# " },
			[15] = { str = "#DOQUESTMessage to the Wildhammer# " },
			[16] = { str = "#DOQUESTRin'ji is Trapped!#, Escort quest, starts at [31,48]", x = 31, y = 48, zone = "Hinterlands" },
			[17] = { str = "#DOQUESTGrim Message# ...while doing this quest accept #ACCEPTVenom Bottles# (one of those little bottles on the table)" },
			[18] = { str = "Yeah the good 'ol hinterlands grind.. have fun LOL." },
			[19] = { str = "If the #NPCOOX-09/HL Distress Beacon# item drops, accept the quest #ACCEPTFind OOX-09/HL!# " },
			[20] = { str = "Turn in #TURNINFind OOX-09/HL!# at [49,38]", x = 49, y = 38, zone = "Hinterlands" },
			[21] = { str = "Turn in #TURNINRin'ji is Trapped!# at [86,59] ... accept #ACCEPTRin'ji's Secret# ", x = 86, y = 59, zone = "Hinterlands" },
			[22] = { str = "Go to Revantusk Village." },
			[23] = { str = "Turn in ALL quests." },
			[24] = { str = "Then get FP and fly to TM." },
			[25] = { str = "Turn in #TURNINVenom Bottles# ... accept #ACCEPTUndamaged Venom Sac# " },
			[26] = { str = "I then get all my magewaeve out from my mailbox, then fly to Hammerfall..." },
			[27] = { str = "Then go to Doctor Gregory Victor to build up first aid..." },
			[28] = { str = "...I’m usually able to get to 290 first aid for Heavy Runecloth bandage." },
			[29] = { str = "Then fly back to TM." },
			[30] = { str = "Then ride back into Hinterlands (don’t fly)" },
			[31] = { str = "Go do #DOQUESTUndamaged Venom Sac# and #DOQUESTThe Atal'ai Exile# ... accept #ACCEPTReturn to Fel'Zerul# " },
			[32] = { str = "Then hearth to TarrenMill." },
			[33] = { str = "Turn in #TURNINUndamaged Venom Sac# ... i SKIP #NPCConsult Master Gadrin# Only accept this quest if you still need to get a mount as orc/troll, as you turn it in in the same spot." },
			[34] = { str = "Fly to the Undercity." },
			[35] = { str = "Go to magic quarter and turn in #TURNINA Donation of Mageweave# (you need 60 mageweave cloth for this quest) " },
			[36] = { str = "Then turn in: #TURNINLines of Communication# and #TURNINRin'ji's Secret# ..then complete #TURNINOran's Gratitude# " },
			[37] = { str = "Get on the zeppelin to go to Grom'gol..." },
			--[38] = { str = "." },
			--[39] = { str = "." },
		}
	},

-----------47-47 Stranglethorn Vale
	--[410] = {
	[4747] = {
		title = "47-47 Stranglethorn Vale",
		--n = "47-47 Stranglethorn Vale",
		--pID = 409, nID = 411,
		--itemCount = 20,
		items = {
			[1] = { str = "47-47 Stranglethorn Vale" },
			[2] = { str = "Go do #DOQUESTRaptor Mastery# (#NPCTethis#) [28,44] and go turn it in", x = 28, y = 44, zone = "Stranglethorn Vale" },
			[3] = { str = "Accept #ACCEPTBig Game Hunter# (Elite), go do it, then turn it in." },
			[4] = { str = "Go to Grom'gol and turn in #TURNINGrim Message# (if you did the Hinterlands section)." },
			[5] = { str = "Fly to BB." },
			[6] = { str = "Accept #ACCEPTThe Bloodsail Buccaneers# part5 and #ACCEPTWhiskey Slim's Lost Grog# " },
			[7] = { str = "Make BB your home." },
			[8] = { str = "Accept #ACCEPTThe Captain's Chest# (Elite) then go do it at [36,65]  NOTE:  This quest is tough to solo, it can be soloed, but you should find a group to help you kill Gorlash, I personally skip it while racing to 60.", x = 36, y = 65, zone = "Stranglethorn Vale" },
			[9] = { str = "Turn in #TURNINBack to Booty Bay# and #TURNINDeliver to MacKinley# " },
			[10] = { str = "Make sure that #DOQUESTThe Captain's Chest# is accepted, then go do it at [36,65]  .  If your class has troubles, either find a group to help, or you can simply skip it.", x = 36, y = 65, zone = "Stranglethorn Vale" },
			[11] = { str = "Find a small bottle laying around the shore east of BB, until this item: #NPCCarefully Folded Note# shows up ... which starts #ACCEPTMessage in a Bottle# " },
			[12] = { str = "Go turn #TURNINMessage in a Bottle# in at [38,80]", x = 38, y = 80, zone = "Stranglethorn Vale" },
			[13] = { str = "Then go do #DOQUESTThe Bloodsail Buccaneers# part5 (kill the three pirates in the three ships) ...while doing it, find #ACCEPTCortello's Riddle# (it's usually a little scroll downstairs in the middle ship)" },
			[14] = { str = "Then hearth back to BB, if hearth stone still is on a cooldown, die on purpose." },
			[15] = { str = "Turn in #TURNINThe Captain's Chest# and #TURNINThe Bloodsail Buccaneers# part5" },
			[16] = { str = "Fly to Kargath (Badlands).." },
			[17] = { str = "I get a stack of Silk Cloth out of the mailbox for the quest #ACCEPTCaught# , then..." },
			[18] = { str = "Go into Searing Gorge..." },
			--[19] = { str = "." },
			--[20] = { str = "." },
		}
	},

-----------47-48 Searing Gorge
	--[411] = {
	[4748] = {
		title = "47-48 Searing Gorge",
		--n = "47-48 Searing Gorge",
		--pID = 410, nID = 412,
		--itemCount = 26,
		items = {
			[1] = { str = "47-48 Searing Gorge" },
			[2] = { str = "First thing I do here is go south-east and do #DOQUESTCaught!#, guy in the outhouse [65,62], then turn it in. ... accept #ACCEPTLedger from Tanaris# ... click on outhouse to get the #NPCGoodsteel Ledger#", x = 65, y = 62, zone = "Searing Gorge" },
			[3] = { str = "I then go start killing Glassweb Spiders for the #DOQUESTLedger from Tanaris# quest." },
			[4] = { str = "Then go up north-west, Talk to #NPCKalaran Windblade# at [39,38] on way to Thorium Point [35,25]. Do first his listen to me quest #DOQUESTDivine Retribution#. In order to get #ACCEPTThe Flawless Flame# Once at Thorium Point collect ALL quests there and get the FP there too.", x = 35, y = 25, zone = "Searing Gorge" },
			[5] = { str = "Then do the following (steps 5 - 13 in any order):" },
			[6] = { str = "#DOQUESTFiery Menace!# " },
			[7] = { str = "#DOQUESTCurse These Fat Fingers# " },
			[8] = { str = "#DOQUESTSTOLEN: Smithing Tuyere and Lookout's Spyglass# " },
			[9] = { str = "#DOQUESTThe Flawless Flame# turn in, then get and do #DOQUESTForging the Shaft# " },
			[10] = { str = "#DOQUESTJOB OPPORTUNITY: Culling the Competition# " },
			[11] = { str = "#DOQUESTWANTED: Overseer Maltorius# (Elite) (only do this quest with a group, even a level 60 has a hard time soloing this quest)." },
			[12] = { str = "#DOQUESTWhat the Flux?#  (the plans for #DOQUESTWhat the Flux?# quest is right behind Overseer Maltorius)" },
			[13] = { str = "#DOQUESTIncendosaurs? Whateverosaur is More Like It# " },
			[14] = { str = "#DOQUESTThe Key to Freedom# starts from an item drop #NPCGrimsite Outhouse Key#, turn in at the outhouse, south-east at [65,62]", x = 65, y = 62, zone = "Searing Gorge" },
			[15] = { str = "Turn in #TURNINForging the Shaft# ... accept #ACCEPTThe Flame's Casing# " },
			[16] = { str = "Do #DOQUESTThe Flame's Casing# around [24,36].  Just keep killing the mobs there until the item drops.", x = 24, y = 36, zone = "Searing Gorge" },
			[17] = { str = "Then turn in #TURNINThe Flame's Casing# ... accept and do #DOQUESTThe Torch of Retribution# , then turn it in ... accept and do #DOQUESTThe Torch of Retribution# Part2 (just pick up the torch on the ground." },
			[18] = { str = "Accept #ACCEPTSquire Maltrake# , then turn it in ... accept #ACCEPTSet Them Ablaze!# " },
			[19] = { str = "Do #DOQUESTSet Them Ablaze!# north=[33,54], south=[44,61], east=[50,54], west=[35,60].  Once that is done, go back and turn it in.", x = 33, y = 54, zone = "Searing Gorge" },
			[20] = { str = "Click on the little chest on the ground at [38,38] and accept #ACCEPTTrinkets...# , then click on the chest again to turn it in.", x = 38, y = 38, zone = "Searing Gorge" },
			[21] = { str = "Make sure you keep the #NPCBlack Dragonflight Molt# in your inventory as you will need it for a later #NPCquest#." },
			[22] = { str = "Once all that's done, turn all Searing Gorge quests in. make sure you have all 20 solid crystal leg shafts." },
			[23] = { str = "Head south into Burning Steppes (You have to go through Black Rock Mountains).." },
			[24] = { str = "I discover some areas, then get FP there at [65,25], and fly directly to Stonard (swamp of sorrows)...", x = 65, y = 25, zone = "Searing Gorge" },
			--[25] = { str = "." },
			--[26] = { str = "." },
		}
	},

-----------48-48 Swamp of Sorrows
	--[412] = {
	[4848] = {
		title = "48-48 Swamp of Sorrows",
		--n = "48-48 Swamp of Sorrows",
		--pID = 411, nID = 413,
		--itemCount = 29,
		items = {
			[1] = { str = "48-48 Swamp of Sorrows" },
			[2] = { str = "Do NOT make Stonard your home. (it should still be Booty Bay)" },
			[3] = { str = "Go to the #NPCFallen Hero of the Horde# [34,66] ... keep talking to him till you get this quest: #ACCEPTThe Disgraced One# ", x = 34, y = 66, zone = "Searing Gorge" },
			[4] = { str = "Then go do #DOQUESTCortello's Riddle# [22,48] under the bridge", x = 22, y = 48, zone = "Searing Gorge" },
			[5] = { str = "Accept #ACCEPTCortello's Riddle# part2" },
			[6] = { str = "Go back to Stonard." },
			[7] = { str = "Go turn in #TURNINThe Disgraced One# (and #TURNINReturn to Fel'Zerul# if you did Hinterlands)... accept #ACCEPTThe Missing Orders# " },
			[8] = { str = "#HUNTER07) Get new hunter spells/abilities#" },
			[9] = { str = "Go turn in #TURNINThe Missing Orders# (in the inn) ... accept #ACCEPTThe Swamp Talker# " },
			[10] = { str = "Go do #DOQUESTThe Swamp Talker# in the cave at [65,78]", x = 65, y = 78, zone = "Searing Gorge" },
			[11] = { str = "Then head north east and.." },
			[12] = { str = "Go kill the mob #NPCJarquia# at around [94,50] or [92,65], he drops #NPCGoodsteel's Balanced Flameberge#... for the quest #DOQUESTLedger from Tanaris# ", x = 94, y = 50, zone = "Searing Gorge" },
			[13] = { str = "Then die on purpose, so you end up at Stonard." },
			[14] = { str = "Go to the #NPCFallen Hero of the Horde# [34,66] and turn in #TURNINThe Swamp Talker# ", x = 34, y = 66, zone = "Searing Gorge" },
			[15] = { str = "Accept and do #DOQUESTA Tale of Sorrow# (Just talk to the guy)" },
			[16] = { str = "Hearth to Booty Bay." },
			[17] = { str = "Get on the boat to go to Ratchet." },
			[18] = { str = "Fly to Brackenwall Village (Dustwallow Marsh).  Once there accept #ACCEPTThe Brood of Onyxia# " },
			[19] = { str = "Then head south and get the #NPCOverdue Package# for the quest #DOQUESTLedger from Tanaris# at [54,55]", x = 54, y = 55, zone = "Dustwallow Marsh" },
			[20] = { str = "Go down a bit and do #DOQUESTThe Brood of Onyxia#   the eggs can be found at [53,72] and [48,75]", x = 53, y = 72, zone = "Dustwallow Marsh" },
			[21] = { str = "Then head west to Bloodfen Burrow cave [32,67], and do #DOQUESTCortello's Riddle# ... accept the next part to it.", x = 32, y = 67, zone = "Dustwallow Marsh" },
			[22] = { str = "Then die on purpose, so you end up back at Brackenwall Village." },
			[23] = { str = "Turn in #TURNINThe Brood of Onyxia# ... accept #ACCEPTChallenge Overlord Mok'Morokk# (??? TBC Quest)" },
			[24] = { str = "Do #DOQUESTChallenge Overlord Mok'Morokk# Then turn it in. (??? TBC Quest)" },
			[25] = { str = "Then fly to Tanaris.." },
			[26] = { str = "Turn in #TURNINLedger from Tanaris# and #TURNINInto the Field# ... accept and complete #DOQUESTSlake that Thirst#" },
			[27] = { str = "Then fly to Ferelas.." },
			--[28] = { str = "." },
			--[29] = { str = "." },
		}
	},

--------48-49 Feralas
	--[413] = {
	[4849] = {
		title = "48-49 Ferelas",
		--n = "48-49 Feralas",
		--pID = 412, nID = 414,
		--itemCount = 27,
		items = {
			[1] = { str = "48-49 Feralas" },
			[2] = { str = "Turn in #TURNINTesting the Vessel# ... accept #ACCEPTHippogryph Muisek# " },
			[3] = { str = "Accept: #ACCEPTImproved Quality#, #ACCEPTVengeance on the Northspring# and #ACCEPTDark Heart# (Elite)" },
			[4] = { str = "Make it your home." },
			[5] = { str = "Go do #DOQUESTHippogryph Muisek# " },
			[6] = { str = "Then hearth back to Camp Mojache." },
			[7] = { str = "Turn in #TURNINHippogryph Muisek# ... accept #ACCEPTFaerie Dragon Muisek# " },
			[8] = { str = "Go do #DOQUESTFaerie Dragon Muisek# .. then turn it in ... accept #ACCEPTTreant Muisek# " },
			[9] = { str = "Go do #DOQUESTTreant Muisek# .. then turn it in ... accept #ACCEPTMountain Giant Muisek# (Elite)" },
			[10] = { str = "Stable pet." },
			[11] = { str = "Go accept #ACCEPTZapped Giants# at [44,44]" },
			[12] = { str = "Go tame an Ironfur Patriarch (for Claw Rank7)" },
			[13] = { str = "Then use that pet to Do the following quests:" },
			[14] = { str = "#DOQUESTImproved Quality# " },
			[15] = { str = "#DOQUESTPerfect Yeti Hide# (you should find this item/quest while doing this quest: #NPCImproved Quality#)" },
			[16] = { str = "#DOQUESTVengeance on the Northspring# " },
			[17] = { str = "#DOQUESTDark Heart# (Elite)" },
			[18] = { str = "#DOQUESTMountain Giant Muisek# (Elite) along with #DOQUESTZapped Giants#" },
			[19] = { str = "Once those quests are completed and #TURNINZapped Giants# is turned in..." },
			[20] = { str = "..hearth to Camp Mojache." },
			[21] = { str = "Abandon bear, get cat back out." },
			[22] = { str = "Turn in #TURNINMountain Giant Muisek# (Elite) ... accept #ACCEPTWeapons of Spirit# ... then turn it in complete it." },
			[23] = { str = "Turn in #TURNINImproved Quality#, #TURNINPerfect Yeti Hide#, #TURNINVengeance on the Northspring# and #TURNINDark Heart# " },
			[24] = { str = "Accept #ACCEPTThe Strength of Corruption# " },
			[25] = { str = "Fly to Tanaris..." },
			--[26] = { str = "." },
			--[27] = { str = "." },
		}
	},

-----------49-50 Tanaris
	--[414] = {
	[4950] = {
		title = "49-50 Tanaris",
		--n = "49-50 Tanaris",
		--pID = 413, nID = 501,
		--itemCount = 33,
		items = {
			[1] = { str = "49-50 Tanaris" },
			[2] = { str = "Go to the Egg-O-Matic machine in Gadgetzan, and turn in the #NPCHippogryph Egg# for #DOQUESTThe Super Egg-O-Matic# quest." },
			[3] = { str = "Make Gadgetzan your home." },
			[4] = { str = "Accept: #ACCEPTThe Thirsty Goblin# #ACCEPTNoxious Lair Investigation# #ACCEPTSuper Sticky# #ACCEPTThistleshrub Valley# and #ACCEPTThe Dunemaul Compound# " },
			[5] = { str = "Go turn in #TURNINThe Sunken Temple# at [52,45] ... accept #ACCEPTThe Stone Circle# and #ACCEPTGahz'ridian# ", x = 52, y = 45, zone = "Tanaris" },
			[6] = { str = "Go do in the following order:" },
			[7] = { str = "#DOQUESTThe Dunemaul Compound# along with #DOQUESTGahz'ridian# done at [46,66] and [40,73], Gor'marok is in the cave at [40,58]", x = 40, y = 58, zone = "Tanaris" },
			[8] = { str = "#DOQUESTNoxious Lair Investigation# [34,47]", x = 34, y = 47, zone = "Tanaris" },
			[9] = { str = "#DOQUESTThistleshrub Valley# along with #DOQUESTThe Thirsty Goblin# [28,65]", x = 28, y = 65, zone = "Tanaris" },
			[10] = { str = "#DOQUESTTooga's Quest#, escort turtle quest starts in the Thistleshrub Valley, lead Tooga to Torta at [66,25].", x = 66, y = 25, zone = "Tanaris" },
			[11] = { str = "Then turn in #TURNINTooga's Quest# along with #TURNINScreecher Spirits# " },
			[12] = { str = "Run to Gadgetzan." },
			[13] = { str = "Turn in #TURNINThe Thirsty Goblin# ... accept #ACCEPTIn Good Taste# turn it in ... accept #ACCEPTSprinkle's Secret Ingredient# " },
			[14] = { str = "Turn in #TURNINThistleshrub Valley#  #TURNINThe Dunemaul Compound# and #TURNINNoxious Lair Investigation# " },
			[15] = { str = "Accept #ACCEPTThe Scrimshank Redemption# " },
			[16] = { str = "Remember to get your Sampling Kit from the bank and go do:" },
			[17] = { str = "#DOQUESTTanaris Field Sampling# and turn in #TURNINGahz'ridian# at [52,45].", x = 52, y = 45, zone = "Tanaris" },
			[18] = { str = "#DOQUESTThe Scrimshank Redemption#, in the cave at [53,70]  The secret for finding the item for this quest is keep making right turns in the cave and it will lead you to it.  ", x = 53, y = 70, zone = "Tanaris" },
			[19] = { str = "If the OOX-17/TN Distress Beacon item drops, accept the quest #ACCEPTFind OOX-17/TN!# " },
			[20] = { str = "Turn in #TURNINFind OOX-17/TN!# at [60,64]", x = 60, y = 64, zone = "Tanaris" },
			[21] = { str = "Then do the Chicken escort #DOQUESTRescue OOX-17/TN!# " },
			[22] = { str = "Once all those quests are finished.." },
			[23] = { str = "Hearth to Gadgetzan." },
			[24] = { str = "Turn in #TURNINTanaris Fiels Sampling# ... accept #ACCEPTReturn to Apothecary Zinge# " },
			[25] = { str = "Turn in #TURNINThe Scrimshank Redemption# ... accept #ACCEPTInsect Part Analysis# " },
			[26] = { str = "Turn in #TURNINInsect Part Analysis# ... accept #ACCEPTInsect Part Analysis# again." },
			[27] = { str = "Turn in #TURNINInsect Part Analysis# ... accept #ACCEPTRise of the Silithid# " },
			[28] = { str = "Fly to Orgrimmar.." },
			[29] = { str = "Make Orgrimmar your home." },
			[30] = { str = "Get the Box of Empty Vials out of your Bank." },
			[31] = { str = "Fly to Azshara..." },
			--[32] = { str = "." },
			--[33] = { str = "." },
		}
	},
}
