--[[--------------------------------------------------
003_Horde_50to60.lua
Authors: mrmr, lanjelin
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 50 to Lvl 60
    1.04.1
        -- First Release
            Horde's Guide
            from level 50 to lever 60
    1.04.2
    	-- no changes in here for this revision
    1.04.3
	    -- Cleanup in text, changed formatting of coords
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Horde_50to60 = {
-----------50-50 Azshara
	--[501] = {
	[5049] = {
		title = "50-50 Azshara",
		n = "50-50 Azshara",
		pID = 414, nID = 502,
		itemCount = 23,
		items = {
			[1] = { str = "50-50 Azshara" },
			[2] = { str = "Accept: #ACCEPTStealing Knowledge# " },
			[3] = { str = "Go do:" },
			[4] = { str = "#DOQUESTStealing Knowledge# Done at the Ruins of Eldarath, [36,54]", x = 36, y = 54, zone = "Azshara" },
			[5] = { str = "#DOQUESTSeeping Corruption# Tide Pools are at: 1=[47,61], 2=[47,51], 3=[48,48], 4=[47,46]", x = 47, y = 61, zone = "Azshara" },
			[6] = { str = "Once their done, turn in #TURNINStealing Knowledge# ..accept ALL 4 delivery quests." },
			[7] = { str = "Turn in #TURNINDelivery to Archmage Xylem#, there is a teleporter at [28,50],#VIDEOSee Video# ... accept #ACCEPTXylem's Payment to Jediga# ", x = 28, y = 50, zone = "Azshara" },
			[8] = { str = "Then fly to Thunder Bluff.." },
			[9] = { str = "Turn in #TURNINDelivery to Magatha# (on Elder Rise) ... accept #ACCEPTMagatha's Payment to Jediga# " },
			[10] = { str = "Hearth to Orgrimmar." },
			[11] = { str = "Go turn in #TURNINRise of the Silithid# ... accept #ACCEPTMarch of the Silithid# at [56,46]", x = 56, y = 46, zone = "Azshara" },
			[12] = { str = "Turn in #TURNINDelivery to Jes'rimon# at [55,34] ... accept #ACCEPTJes'rimon's Payment to Jediga# and #ACCEPTBone-Bladed Weapons# ", x = 55, y = 34, zone = "Azshara" },
			[13] = { str = "Then turn in #TURNINRipple Delivery# at [59,36]  (If you did the Hinterlands section)", x = 59, y = 36, zone = "Azshara" },
			[14] = { str = "Then I go get new #HUNTERhunter# spells/abilities ... #HUNTERaccept# #ACCEPTThe Hunter's Charm# #HUNTER(if you're a Hunter).#" },
			[15] = { str = "Then go to The Undercity, head to the Apothecarium Quarter..." },
			[16] = { str = "Turn in #TURNINDelivery to Andron Gant# ... accept #ACCEPTAndron's Payment to Jediga# " },
			[17] = { str = "Then turn in #TURNINSeeping Corruption# and #TURNINReturn to Apothecary Zinge# ... accept #ACCEPTVivian Lagrave# while you are there." },
			[18] = { str = "Then accept #ACCEPTSeeping Corruption# ... then turn it in (at the tauren right next to him) ..." },
			[19] = { str = "... Then complete #TURNINSeeping Corruption# for the final time." },
			[20] = { str = "Then accept #ACCEPTA Sample of Slime...# and #ACCEPT... and a Batch of Ooze# " },
			[21] = { str = "Then fly to Raventusj Village..." },
			--[22] = { str = "." },
			--[23] = { str = "." },
		}
	},

-----------50-50 Hinterlands
	--[502] = {
	[5050] = {
		title = "50-50 Hinterlands",
		--n = "50-50 Hinterlands",
		--pID = 501, nID = 503,
		--itemCount = 20,
		items = {
			[1] = { str = "50-50 Hinterlands" },
			[2] = { str = "Accept: #ACCEPTSnapjaws, Mon!# #ACCEPTGammerita, Mon!# (Elite) and #ACCEPTLard Lost His Lunch# " },
			[3] = { str = "Go do in the following order:" },
			[4] = { str = "#DOQUESTSnapjaws, Mon!# along with #DOQUESTGammerita, Mon!# and #DOQUESTWhiskey Slim's Lost Grog# " },
			[5] = { str = "#DOQUESTCortello's Riddle# at [80,46], little chest in the water, 14 slot bag along with 8800 XP", x = 80, y = 46, zone = "The Hinterlands" },
			[6] = { str = "#DOQUESTLard Lost His Lunch# at [84,42]", x = 84, y = 42, zone = "The Hinterlands" },
			[7] = { str = "Then go turn in #TURNINSnapjaws, Mon!# #TURNINGammerita, Mon!# and #TURNINLard Lost His Lunch# " },
			[8] = { str = "Then go do #DOQUESTSprinkle's Secret Ingredient# at [41,60]", x = 41, y = 60, zone = "The Hinterlands" },
			[9] = { str = "Then hearth to Orgrimmar." },
			[10] = { str = "Fly to Azshara." },
			[11] = { str = "Turn in all 4 delivery quests." },
			[12] = { str = "Fly to XRs." },
			[13] = { str = "Make XRs your home." },
			[14] = { str = "Fly to Ratchet." },
			[15] = { str = "Pick up the #NPCStone Circle# at Liv Rizzlefix shop ... also accept #ACCEPTVolcanic Activity# while your there." },
			[16] = { str = "Get on the boat to go to BB" },
			[17] = { str = "Fly to Stonard (swamp of sorrows).." },
			[18] = { str = "Go into Blasted Lands..." },
			--[19] = { str = "." },
			--[20] = { str = "." },
		}
	},

------------50-51 Blasted Lands
	--[503] = {
	[5051] = {
		title = "50-51 Blasted Lands",
		--n = "50-51 Blasted Lands",
		--pID = 502, nID = 504,
		--itemCount = 27,
		items = {
			[1] = { str = "50-51 Blasted Lands" },
			[2] = { str = "I then find all the items to complete these 5 quests:" },
			[3] = { str = "#DOQUESTA Boar's Vitality# " },
			[4] = { str = "#DOQUESTSnickerfang Jowls# " },
			[5] = { str = "#DOQUESTThe Basilisk's Bite# " },
			[6] = { str = "#DOQUESTThe Decisive Striker# " },
			[7] = { str = "#DOQUESTVulture's Vigor# " },
			[8] = { str = "You need to find these many items to complete these quests:" },
			[9] = { str = "#NPCVulture Gizzards# x14" },
			[10] = { str = "#NPCBasilisk Brain# x11" },
			[11] = { str = "#NPCBlasted Boar Lungs# x6" },
			[12] = { str = "#NPCScorpok Pincers# x6" },
			[13] = { str = "#NPCSnickerfang Jowls# x5" },
			[14] = { str = "While I'm in Blasted Lands, I discover most of all the areas for XP." },
			[15] = { str = "If an #NPCImperfect Draenethyst Fragment drops turn in for this quest: #TURNINEverything Counts In Large Amounts# " },
			[16] = { str = "NOTE: I have NEVER found a #NPCFlawless Draenethyst Sphere# for the quest #TURNINTo Serve Kum'isha# ..good luck on that." },
			[17] = { str = "Turn in all quests." },
			[18] = { str = "I turn in #TURNINThe Decisive Striker# in last for Ground Scorpok Assay (+50 to agility)" },
			[19] = { str = "Then hearth to XRs." },
			[20] = { str = "Fly to Tanaris (GET A MITHRIL CASING for a later quest in Un'Goro!!!)" },
			[21] = { str = "Turn in #TURNINSprinkle's Secret Ingredient# ... accept #ACCEPTDelivery for Marin# " },
			[22] = { str = "Turn in #TURNINMarch of the Silithid# ... accept #ACCEPTBungle in the Jungle# " },
			[23] = { str = "Turn in #TURNINDelivery for Marin# ...accept #ACCEPTNoggenfogger Elixir# then turn it in." },
			[24] = { str = "Go turn in #TURNINThe Stone Circle# at [52,46] in Tanaris", x = 52, y = 46, zone = "Tanaris" },
			[25] = { str = "Then go into Un'Goro Crater..." },
			--[26] = { str = "." },
			--[27] = { str = "." },
		}
	},

-----------51-52 Un'Goro Crater
	--[504] = {
	[5152] = {
		title = "51-52 Un'Goro Crater",
		--n = "51-52 Un'Goro Crater",
		--pID = 503, nID = 505,
		--itemCount = 56,
		items = {
			[1] = { str = "51-52 Un'Goro Crater" },
			[2] = { str = "Go accept: #ACCEPTThe Apes of Un'Goro# and #ACCEPTThe Fare of Lar'korwi# at [71,75]", x = 71, y = 75, zone = "Un'Goro Crater" },
			[3] = { str = "Go do #DOQUESTThe Fare of Lar'korwi# at [68,56]", x = 68, y = 56, zone = "Un'Goro Crater" },
			[4] = { str = "Then go start doing: #DOQUESTSuper Sticky# (up north in the middle) until this item drops #NPCA Mangled Journal#" },
			[5] = { str = "Then go into Marshal's Refuge [43,10], accept ALL quests there:  #ACCEPTChasing A-Me 01# #ACCEPTShizzle's Flyer# #ACCEPTLost!# #ACCEPTBeware of Pterrordax# #ACCEPTRoll the Bones# #ACCEPTAlien Ecology# #ACCEPTExpedition Salvation# #ACCEPTLarion and Muigin# ", x = 43, y = 10, zone = "Un'Goro Crater" },
			[6] = { str = "Turn in #TURNINWilliden's Journal# " },
			[7] = { str = "Get FP there, then go do the Ungoro Grind :) ..." },
			[8] = { str = "NOTE: don't worry about the ungoro dirt mounds, you'll find enough soil from mob drops.  Also I don't worry about the Bloodpetal Sprouts, as they are not turned in for any XP." },
			[9] = { str = "While questing, find 7 crystals of each color (red, blue, green, and yellow for the #DOQUESTCrystals of Power# quest)" },
			[10] = { str = "#DOQUESTSuper Sticky# " },
			[11] = { str = "#DOQUESTThe Apes of Un'Goro# along with #DOQUESTChasing A-Me 01# (if you have a #NPCmithril casing# do the escort) [63,17]", x = 63, y = 17, zone = "Un'Goro Crater" },
			[12] = { str = "#DOQUESTLarion and Muigin# " },
			[13] = { str = "#DOQUESTBeware of Pterrordax# along with #DOQUESTShizzle's Flyer# and.." },
			[14] = { str = "#DOQUESTRoll the Bones# " },
			[15] = { str = "#DOQUESTExpedition Salvation# [68,36] and [38,65]", x = 68, y = 36, zone = "Un'Goro Crater" },
			[16] = { str = "#DOQUEST... and a Batch of Ooze# (I make sure I get at least 30 ooze samples)" },
			[17] = { str = "Go turn in #TURNINThe Apes of Un'Goro# ... accept #ACCEPTThe Mighty U'cha# " },
			[18] = { str = "Turn in #TURNINThe Fare of Lar'korwi# ... accept #ACCEPTThe Scent of Lar'korwi# " },
			[19] = { str = "Then go do:" },
			[20] = { str = "#DOQUESTBone-Bladed Weapons# along with #DOQUESTThe Scent of Lar'korwi# " },
			[21] = { str = "#ACCEPTIt's a Secret to Everybody# ... click on boat and then bag under water at [63,68]", x = 63, y = 68, zone = "Un'Goro Crater" },
			[22] = { str = "Then turn in #TURNINThe Scent of Lar'korwi# ... accept #ACCEPTThe Bait for Lar'korwi# [71,75]", x = 71, y = 75, zone = "Un'Goro Crater" },
			[23] = { str = "Then go do #DOQUESTAlien Ecology# along with #DOQUESTBungle in the Jungle# [50,80]", x = 50, y = 80, zone = "Un'Goro Crater" },
			[24] = { str = "Go accept #ACCEPTFinding the Source# at [30,50], then do it along with #DOQUESTVolcanic Activity# ", x = 30, y = 50, zone = "Un'Goro Crater" },
			[25] = { str = "The hotspot path for the quest #DOQUESTFinding the Source# starts at [51,42] and the hot spot is at [50,46]  (#VIDEOSee Video on where to find the hotspot#)", x = 51, y = 42, zone = "Un'Goro Crater" },
			[26] = { str = "#DOQUESTLost!# Make sure all quests are done before doing this (besides #NPCThe Mighty U'cha# and #NPCThe Bait for Lar'korwi# ), then..." },
			[27] = { str = "...This leads back to Marshal's Refuge, Turn in ALL quests there, accept new ones (including all the Pylon quests in the cave)." },
			[28] = { str = "Then go do (in the following order):" },
			[29] = { str = "#DOQUESTThe Northern Pylon# at [56,13]", x = 56, y = 13, zone = "Un'Goro Crater" },
			[30] = { str = "#DOQUESTThe Mighty U'cha# cave at [63,13]", x = 63, y = 13, zone = "Un'Goro Crater" },
			[31] = { str = "#DOQUESTThe Eastern Pylon# at [77,50]", x = 77, y = 50, zone = "Un'Goro Crater" },
			[32] = { str = "#DOQUESTThe Bait for Lar'korwi# [80,50].  Then turn it in along with #TURNINThe Mighty U'cha# [71,75]", x = 71, y = 75, zone = "Un'Goro Crater" },
			[33] = { str = "Go west killing oozes along the way.." },
			[34] = { str = "Turn in #TURNINFinding the Source# ... accept #ACCEPTThe New Springs# [30,50]", x = 30, y = 50, zone = "Un'Goro Crater" },
			[35] = { str = "#DOQUESTThe Western Pylon# at [23,58]", x = 23, y = 58, zone = "Un'Goro Crater" },
			[36] = { str = "Go back to Marshal's Refuge killing oozes along the way.." },
			[37] = { str = "Turn in quests. make sure you complete #DOQUESTMaking Sense of It# (just talk to the gnome in the cave)" },
			[38] = { str = "Fly to Tanaris." },
			[39] = { str = "Turn in #TURNINSuper Sticky# and #TURNINBungle in the Jungle# ... I SKIP #NPCPawn Captures Queen# " },
			[40] = { str = "Then fly to Thunder Bluff." },
			[41] = { str = "Go to Elder Rise." },
			[42] = { str = "Accept #ACCEPTUn'goro Soil# .. then turn it in ... accept #ACCEPTMorrowgrain Research# .. then turn that in..." },
			[43] = { str = "...but SKIP the next part (the part that says bring 10 Morrowgrain)" },
			[44] = { str = "Go get new spells/abilities." },
			[45] = { str = "Hearth to XRs." },
			[46] = { str = "Then fly to Ratchet.." },
			[47] = { str = "Turn in #TURNINVolcanic Activity# and #TURNINMarvon's Workshop# - I SKIP #NPCZapper Fuel# " },
			[48] = { str = "Get on the boat to go to BB.." },
			[49] = { str = "Turn in #TURNINWhiskey Slim's Lost Grog# " },
			[50] = { str = "Also turn in #TURNINRescue OOX-17/TN!# (if you did it)" },
			[51] = { str = "Fly to Kargath (Badlands).." },
			[52] = { str = "Turn in #TURNINVivian Lagrave# " },
			[53] = { str = "Accept: #ACCEPTDreadmaul Rock# and #ACCEPTThe Rise of the Machines# " },
			[54] = { str = "Then fly to Burning Steppes..." },
			--[55] = { str = "." },
			--[56] = { str = "." },
		}
	},

-----------52-53 Burning Steppes
	--[505] = {
	[5253] = {
		title = "52-53 Burning Steppes",
		--n = "52-53 Burning Steppes",
		--pID = 504, nID = 506,
		--itemCount = 18,
		items = {
			[1] = { str = "52-53 Burning Steppes" },
			[2] = { str = "Accept: #ACCEPTBroodling Essence# and #ACCEPTTablet of the Seven# " },
			[3] = { str = "Then go do:" },
			[4] = { str = "#DOQUESTBroodling Essence# (to the east) (also kill as many dragon whelps you see, their squishy mobs that die real fast)" },
			[5] = { str = "#DOQUESTDreadmaul Rock# [79,45]... then #DOQUESTKrom'Grul# (Krom'Grul has 2 different spawn points, in either cave)", x = 79, y = 45, zone = "Burning Steppes" },
			[6] = { str = "#DOQUESTThe Rise of the Machines# " },
			[7] = { str = "#DOQUESTTablet of the Seven# it's at [54,40]", x = 54, y = 40, zone = "Burning Steppes" },
			[8] = { str = "Go turn in #TURNINTablet of the Seven# and #TURNINBroodling Essence# ... accept #ACCEPTFelnok Steelspring# " },
			[9] = { str = "Then fly to Kargath (Badlands)" },
			[10] = { str = "Turn in #TURNINKrom'Grul# " },
			[11] = { str = "Turn in #TURNINThe Rise of the Machines# ... accept #ACCEPTThe Rise of the Machines# part2" },
			[12] = { str = "Go turn in #TURNINThe Rise of the Machines# part2 at [25,46] in Badlands", x = 25, y = 46, zone = "Badlands" },
			[13] = { str = "Then hearth to XRs." },
			[14] = { str = "Then fly to Orgrimmar and make it your home." },
			[15] = { str = "Go turn in #TURNINBone-Bladed Weapons# [55,34]", x = 55, y = 34, zone = "Orgrimmar" },
			[16] = { str = "Fly Azshara..." },
			--[17] = { str = "." },
			--[18] = { str = "." },
		}
	},

--------------53-54 Azshara
	--[506] = {
	[5354] = {
		title = "53-54 Azshara",
		--n = "53-54 Azshara",
		--pID = 505, nID = 507,
		--itemCount = 28,
		items = {
			[1] = { str = "53-54 Azshara" },
			[2] = { str = "Accept #ACCEPTBetrayed# " },
			[3] = { str = "Go turn in #TURNINThe Hunter's Charm#, this is a hunter only quest, at [41,42] ... accept #ACCEPTCourser Antlers# " },
			[4] = { str = "Go accept #ACCEPTKim'jael Indeed!# at [52,22] on top of the hill", x = 52, y = 22, zone = "Azshara" },
			[5] = { str = "Then go do:" },
			[6] = { str = "#DOQUESTCourser Antlers# " },
			[7] = { str = "#DOQUESTBetrayed# " },
			[8] = { str = "#DOQUESTKim'jael Indeed!# " },
			[9] = { str = "NOTE: I grind away at bloodelfs for a while doing those 2 quests." },
			[10] = { str = "Once those 3 quests are done, go turn in #TURNINKim'jael Indeed!# ... accept #ACCEPTKim'jael's Missing Equipment# " },
			[11] = { str = "Turn in #TURNINCourser Antlers# ... accept #ACCEPTWavethrashing# " },
			[12] = { str = "Then go do:" },
			[13] = { str = "#DOQUESTKim'jael's Missing Equipment# " },
			[14] = { str = "#DOQUESTWavethrashing# " },
			[15] = { str = "Once both are done, Hearth to Orgrimmar." },
			[16] = { str = "Then Fly to Azshara.." },
			[17] = { str = "Turn in #TURNINBetrayed# ... accept #ACCEPTBetrayed# " },
			[18] = { str = "Turn in #TURNINWavethrashing# ... i SKIP #NPCThe Green Drake# " },
			[19] = { str = "Turn in #TURNINKim'jael's Missing Equipment# " },
			[20] = { str = "At this point im usually about 3/4th the way to lvl 54, I grind my way to level 54 on BloodElfs." },
			[21] = { str = "I grind bloodelfs, cause their squishy mobs (mobs that have 30% fewer health/armor, than the average mob that level).  I used to grind satyrs on previous speed runs, but I was able to cut off almost a whole hour with the blood elfs." },
			[22] = { str = "OPTIONAL: Instead of the grinding you could go do BRD instance instead." },
			[23] = { str = "Once i hit 54 (or a few bars past it), i then hearth to Orgrimmar." },
			[24] = { str = "I then go turn in #TURNINBone-Bladed Weapons# and #TURNINBetrayed# " },
			[25] = { str = "Then fly to Splintertree Post (Ashenvale).." },
			[26] = { str = "Then go into Felwood..." },
			--[27] = { str = "." },
			--[28] = { str = "." },
		}
	},

-----------54-54 Felwood
	--[507] = {
	[5454] = {
		title = "54-54 Felwood",
		--n = "54-54 Felwood",
		--pID = 506, nID = 508,
		--itemCount = 16,
		items = {
			[1] = { str = "54-54 Felwood" },
			[2] = { str = "Accept #ACCEPTTimbermaw Ally# at [50,85] (??? TBC Quest?) Just talk to the NPC there he will give it to you.", x = 50, y = 85, zone = "Felwood" },
			[3] = { str = "Go accept #ACCEPTForces of Jaedenar# and #ACCEPTVerifying the Corruption# at the Emerald Sanctuary [51,82].", x = 51, y = 82, zone = "Felwood" },
			[4] = { str = "Go accept #ACCEPTCleansing Felwood# at [46,84]", x = 46, y = 84, zone = "Felwood" },
			[5] = { str = "I start killing oozes, I make sure I kill about 30/40 oozes here total for the quest #DOQUESTA Sample of Slime...# [40,68]", x = 40, y = 68, zone = "Felwood" },
			[6] = { str = "Then go complete #DOQUESTForces of Jaedenar# [38,60]", x = 38, y = 60, zone = "Felwood" },
			[7] = { str = "Then go to BloodVenom Post. [34,52]", x = 34, y = 52, zone = "Felwood" },
			[8] = { str = "Accept: #ACCEPTA Husband's Last Battle# and #ACCEPTWild Guardians# " },
			[9] = { str = "Get FP there." },
			[10] = { str = "Then go do in the following order:" },
			[11] = { str = "#DOQUESTVerifying the Corruption# (Elite) [41,41]", x = 41, y = 41, zone = "Felwood" },
			[12] = { str = "#DOQUESTCleansing Felwood# [54,16]", x = 54, y = 16, zone = "Felwood" },
			[13] = { str = "Go accept #ACCEPTDeadwood of the North# (at 64.8) but DON'T do it now.", x = 64, y = 8, zone = "Felwood" },
			[14] = { str = "Grind your way through the cave to go to Winterspring..." },
			--[15] = { str = "." },
			--[16] = { str = "." },
		}
	},

-----------54-55 Winterspring
	--[508] = {
	[5455] = {
		title = "54-55 Winterspring",
		--n = "54-55 Winterspring",
		--pID = 507, nID = 509,
		--itemCount = 31,
		items = {
			[1] = { str = "54-55 Winterspring" },
			[2] = { str = "Exit the cave and accept #ACCEPTWinterfall Activity# right outside of it." },
			[3] = { str = "Go to Donova Snowden at [31,45]", x = 31, y = 45, zone = "Winterspring" },
			[4] = { str = "Turn in #TURNINThe New Springs# and #TURNINIt's a Secret to Everybody# and accept #ACCEPTStrange Sources#" },
			[5] = { str = "NOTE: I SKIP #NPCThe Videre Elixir# and the rest of that chain." },
			[6] = { str = "Go to Everlook.. [61,38]", x = 61, y = 38, zone = "Winterspring" },
			[7] = { str = "Accept: #ACCEPTAre We There, Yeti?# #ACCEPTThe Everlook Report# #ACCEPTDuke Nicholas Zverenhoff# #ACCEPTSister Pamela# #ACCEPTTrouble in Winterspring#and #ACCEPTUrsius of the Shardtooth#" },
			[8] = { str = "Turn in #TURNINFelnok Steelspring# ... accept #ACCEPTChillwind Horns# " },
			[9] = { str = "Make Everlook your home." },
			[10] = { str = "Go do #DOQUESTUrsius of the Shardtooth#   (just keep grinding mobs on the hill north of everlook till #NPCUrsius# shows up)" },
			[11] = { str = "Then turn in #TURNINUrsius of the Shardtooth# ... accept #ACCEPTBrumeran of the Chillwind# " },
			[12] = { str = "Go do #DOQUESTBrumeran of the Chillwind# he patrols around [60,60]", x = 60, y = 60, zone = "Winterspring" },
			[13] = { str = "Then go Discover Darkwhisper Gorge at [59,73] for the quest #DOQUESTStrange Sources# ", x = 59, y = 73, zone = "Winterspring" },
			[14] = { str = "Then hearth back to Everlook." },
			[15] = { str = "Turn in #TURNINBrumeran of the Chillwind# ... SKIP #NPCShy-Rotam# " },
			[16] = { str = "Then go do the following quests (steps 17-20, in any order) to the west and some to the north. When you're at west remember to turn-in #TURNINTrouble in Winterspring# and accept #ACCEPTThreat of the Winterfall#:" },
			[17] = { str = "#DOQUESTAre We There, Yeti?# " },
			[18] = { str = "#DOQUESTThreat of the Winterfall# you should find #NPCEmpty Firewater Flask# which starts #ACCEPTWinterfall Firewater# while doing this quest.  When the #NPCWinterfall Ritual Totem# item drops, save it and put it in your bank you will need it later." },
			[19] = { str = "#DOQUESTWild Guardians# (the Ragged Owls are west of Everlook, and the Raging Owls are just north of Everlook)" },
			[20] = { str = "#DOQUESTChillwind Horns#, you can find a larger concentration of chimaera around [66,29]", x = 66, y = 29, zone = "Winterspring" },
			[21] = { str = "Once #DOQUESTThreat of the Winterfall# and #DOQUESTWinterfall Firewater# is completed go turn them in along with #TURNINStrange Sources# at [31,45]... accept #ACCEPTFalling to Corruption# ", x = 31, y = 45, zone = "Winterspring" },
			[22] = { str = "Once the rest of those quests are complete, go back to Everlook and turn in #TURNINAre We There, Yeti?# ...accept #ACCEPTAre We There, Yeti?# part2.  Turn in #TURNINChillwind Horns# ... i SKIP #NPCReturn to Tinkee# " },
			[23] = { str = "Then go do:" },
			[24] = { str = "#DOQUESTWinterfall Activity# [67,37]", x = 67, y = 37, zone = "Winterspring" },
			[25] = { str = "#DOQUESTAre We There, Yeti?# (find 2 Pristine Yeti Horns) [66,43]", x = 66, y = 43, zone = "Winterspring" },
			[26] = { str = "Then hearth to Everlook and accept #ACCEPTA Strange One #" },
			[27] = { str = "Go turn in #TURNINAre We There, Yeti?# ... accept #ACCEPTAre We There, Yeti?# part3" },
			[28] = { str = "Go scare Legacki with the mechanical yeti for the quest #DOQUESTAre We There, Yeti?# part3" },
			[29] = { str = "Then fly to Felwood..." },
			--[30] = { str = "." },
			--[31] = { str = "." },
		}
	},

-----------55-55 Felwood
	--[509] = {
	[5554] = {
		title = "55-55 Felwood",
		--n = "55-55 Felwood",
		--pID = 508, nID = 510,
		--itemCount = 31,
		items = {
			[1] = { str = "55-55 Felwood" },
			[2] = { str = "Turn in #TURNINWild Guardians# ... Accept #ACCEPTWild Guardians# part2 and #ACCEPTWell of Corruption#" },
			[3] = { str = "Go turn in #TURNINCleansing Felwood# ... then get a cenarion beacon for the quest #DOQUESTSalve Via Hunting# (just talk to the NPC to get it) [46,83]", x = 46, y = 83, zone = "Felwood" },
			[4] = { str = "Go turn in #TURNINVerifying the Corruption# and #TURNINForces of Jaedenar# ... accept #ACCEPTCollection of the Corrupt Water# [51,82]", x = 51, y = 82, zone = "Felwood" },
			[5] = { str = "Go do in the following order:" },
			[6] = { str = "Go do #DOQUESTA Husband's Last Battle# along with #DOQUESTTimbermaw Ally# [48,94]", x = 48, y = 94, zone = "Felwood" },
			[7] = { str = "Once they are done go turn in #TURNINTimbermaw Ally# at [50,85] ... accept #ACCEPTSpeak to Nafien#", x = 50, y = 85, zone = "Winterspring" },
			[8] = { str = "Go do #DOQUESTWell of Corruption# at [32,66].  Also make sure you collect 6 #NPCCorrupted Soul Shards# for the quest #DOQUESTSalve Via Hunting# ", x = 32, y = 66, zone = "Felwood" },
			[9] = { str = "#DOQUESTCollection of the Corrupt Water# [35,59]", x = 35, y = 59, zone = "Felwood" },
			[10] = { str = "Then go to Bloodvenom Post" },
			[11] = { str = "Turn in #TURNINA Husband's Last Battle# and #TURNINWell of Corruption# ... accept #ACCEPTCorrupted Sabers# " },
			[12] = { str = "Go turn in #TURNINSalve Via Hunting# (the 6 Corrupted Soul Shards) [46,83]", x = 46, y = 83, zone = "Felwood" },
			[13] = { str = "Go turn in #TURNINCollection of the Corrupt Water# ... I SKIP #NPCSeeking Spiritual Aid# [51,82] ", x = 51, y = 82, zone = "Felwood" },
			[14] = { str = "Go do #DOQUESTCorrupted Sabers# [32,66] then go turn it in.  (NOTE: when you turn it in, you have to talk to the cat first once you get to the NPC)", x = 32, y = 66, zone = "Felwood" },
			[15] = { str = "Then go up north and do:" },
			[16] = { str = "#DOQUESTDeadwood of the North# (61.9)  When the Deadwood Ritual Totem item drops, save it and put it in your bank when you get a chance, you will need it later.", x = 61, y = 9, zone = "Felwood" },
			[17] = { str = "#DOQUESTFalling to Corruption# (the cauldron at 60.5) (hint: I have my pet distract the mobs, while doing this quest)   ... then accept #ACCEPTMystery Goo# ", x = 60, y = 5, zone = "Felwood" },
			[18] = { str = "Go turn in #TURNINDeadwood of the North# (64.8) ... accept #ACCEPTSpeak to Salfa# .  And turn in #TURNINSpeak to Nafien# ", x = 64, y = 8, zone = "Felwood" },
			[19] = { str = "Then run through the cave (you should be Unfriendly with Timbermaw, so they shouldn't attack you).." },
			[20] = { str = "Turn in #TURNINWinterfall Activity# and #TURNINSpeak to Salfa# " },
			[21] = { str = "Then go turn in #TURNINMystery Goo# at [31,45] in Winterspring ... SKIP #NPCToxic Horrors# ", x = 31, y = 45, zone = "Winterspring" },
			[22] = { str = "Then hearth to Everlook." },
			[23] = { str = "Fly to Orgrimmar and make it your home." },
			[24] = { str = "If you happen to see #NPCWarcaller Gorlach#, accept #ACCEPTA Call To Arms: The Plaguelands!# " },
			[25] = { str = "Fly to Thunder Bluff, then directly to Camp Mojache, Ferelas" },
			[26] = { str = "Turn in #TURNINThe Strength of Corruption# " },
			[27] = { str = "Then fly to Tanaris..." },
			[28] = { str = "Go scare #NPCSprinkle# with the mechanical yeti for the quest #DOQUESTAre We There, Yeti?# part3" },
			[29] = { str = "Then fly to Silithus" },
			--[30] = { str = "." },
			--[31] = { str = "." },
		}
	},

------------55-55 Silithus
	--[510] = {
	[5555] = {
		title = "55-55 Silithus",
		--n = "55-55 Silithus",
		--pID = 509, nID = 511,
		--itemCount = 25,
		items = {
			[1] = { str = "55-55 Silithus" },
			[2] = { str = "Accept: #ACCEPTThe Twilight Mystery# #ACCEPTSecuring the Supply Lines# and #ACCEPTDeadly Desert Venom# " },
			[3] = { str = "Go do: #DOQUESTSecuring the Supply Lines# and #DOQUESTDeadly Desert Venom# (do these 2 quests northeast of Cenarion Hold)" },
			[4] = { str = "Then turn them in and accept new quests." },
			[5] = { str = "Then go do:" },
			[6] = { str = "#DOQUESTStepping Up Security# " },
			[7] = { str = "#DOQUESTThe Twilight Mystery# " },
			[8] = { str = "#DOQUESTNoggle's Last Hope# " },
			[9] = { str = "Once all three of those are done, go turn them in accept new ones." },
			[10] = { str = "Go do:" },
			[11] = { str = "#DOQUESTNoggle's Lost Satchel#, it's at around [40,90]", x = 40, y = 90, zone = "Silithus" },
			[12] = { str = "NOTE: I skip #NPCWanted - Deathclasp, Terror of the Sands# (Elite) cause it's too hard to solo at 55, but do it if you can find a group." },
			[13] = { str = "#DOQUESTThe Deserter# He's in the cave at [67,71] ... i SKIP #NPCThe Twilight Lexicon# ", x = 67, y = 71, zone = "Silithus" },
			[14] = { str = "Then i die on purpose, so i end up at Cenarion Hold." },
			[15] = { str = "Turn in #TURNINNoggle's Lost Satchel# " },
			[16] = { str = "Then go to Marshal's Refuge in Un'Goro Crater." },
			[17] = { str = "Go scare Quixxil with the mechanical yeti for the quest #DOQUESTAre We There, Yeti?# part3" },
			[18] = { str = "Then hearth to Orgrimmar." },
			[19] = { str = "Go to the Under City." },
			[20] = { str = "Go complete #TURNINA Sample of Slime...# and #TURNIN... and a Batch of Ooze# " },
			[21] = { str = "Go accept #ACCEPTA Call To Arms: The Plaguelands!# " },
			[22] = { str = "Make Under City your home." },
			[23] = { str = "Go to the Bulwark... (which is a small village east of Tirisfal Glades)" },
			--[24] = { str = "." },
			--[25] = { str = "." },
		}
	},

-----------55-56 Western Plaguelands
	--[511] = {
	[5556] = {
		title = "55-56 Western Plaguelands",
		--n = "55-56 Western Plaguelands",
		--pID = 510, nID = 512,
		--itemCount = 24,
		items = {
			[1] = { str = "55-56 Western Plaguelands" },
			[2] = { str = "Turn in #TURNINA Call To Arms: The Plaguelands!# accept #ACCEPTScarlet Diversions# ..." },
			[3] = { str = "... (make sure you get a Flame in a Bottle first, before doing this quest, it's in the box)" },
			[4] = { str = "Turn in #TURNINThe Everlook Report# " },
			[5] = { str = "Accept and complete #DOQUESTArgent Dawn Commission# " },
			[6] = { str = "Accept #ACCEPTA Plague Upon Thee# " },
			[7] = { str = "Go into the Western Plaguelands, Felstone field at [37,56] and...", x = 37, y = 56, zone = "Western Plaguelands" },
			[8] = { str = "Accept #ACCEPTBetter Late Than Never# (the lady in the house)" },
			[9] = { str = "Then go to the barn next door, and..." },
			[10] = { str = "Complete #DOQUESTBetter Late Than Never# .. click on the chest again to accept #ACCEPTBetter Late Than Never# again." },
			[11] = { str = "Go do #DOQUESTScarlet Diversions#, burn the tent down, and plant the banner [40,51]  ", x = 40, y = 51, zone = "Western Plaguelands" },
			[12] = { str = "Go back to the Bulwark..  (#VIDEONOTE:# Make sure you save all #NPCBone Fragments# you find, you will need 30 of them for a later #NPCquest#)" },
			[13] = { str = "Turn in #TURNINScarlet Diversions# ... accept #ACCEPTAll Along the Watchtowers# (Elite) and #ACCEPTThe Scourge Cauldrons# " },
			[14] = { str = "Turn in #TURNINThe Scourge Cauldrons# ... accept #ACCEPTTarget: Felstone Field# " },
			[15] = { str = "Go complete the whole Cauldron quest chain, you need to kill the Cauldron Lord at each targeted field (listed below), grab their key and use it at the big cauldron in the middle of the field.  (Just keep going back and forth from The Bulwark to the next field completing each one, turning them in and then accepting and doing the next one)..." },
			[16] = { str = "#DOQUESTTarget: Felstone Field# [37,56]", x = 37, y = 56, zone = "Western Plaguelands" },
			[17] = { str = "#DOQUESTTarget: Dalson's Tears# [46,52].  #VIDEONOTE:#  While you are here, there is a small quest chain here that starts with a little Diary in the barn [47,50] called #TURNINMrs. Dalson's Diary# , just click that to complete the quest.  Now, after you did that, then you need to kill a #NPCWandering Skeleton# to get a key that opens the outhouse behind the barn. After you get the key and open the outhouse, it will release a #NPCFarmer Dalson#, a level 56 undead. Kill him, grab that key, and then run in the house (that is right next to the barn) and go up the stairs, there you will find a cabinet, open the cabinet with that key (For the quest #DOQUESTLocked Away# ) and finally it's over.  Easy 10200 XP!  Or was it?", x = 46, y = 52, zone = "Western Plaguelands" },
			[18] = { str = "#DOQUESTTarget: Writhing Haunt# [53,65] (while you're there accept #ACCEPTThe Wildlife Suffers Too# at [53,64], the almost dead tauren in the hut", x = 53, y = 65, zone = "Western Plaguelands" },
			[19] = { str = "#DOQUESTTarget: Gahrron's Withering# [62,59]", x = 62, y = 59, zone = "Western Plaguelands" },
			[20] = { str = "Just keep going back and forth completing each one." },
			[21] = { str = "Then go accept and complete #DOQUESTMission Accomplished!# " },
			[22] = { str = "Then head into Eastern Plaguelands..." },
			--[23] = { str = "." },
			--[24] = { str = "." },
		}
	},

-----------56-57 Eastern Plaguelands
	--[512] = {
	[5657] = {
		title = "56-57 Eastern Plaguelands",
		--n = "56-57 Eastern Plaguelands",
		--pID = 511, nID = 513,
		--itemCount = 38,
		items = {
			[1] = { str = "56-57 Eastern Plaguelands" },
			[2] = { str = "Go accept: #ACCEPTDemon Dogs# #ACCEPTBlood Tinged Skies# and #ACCEPTCarrion Grubbage# (at 7.43)", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[3] = { str = "Grind your way to [26,74] and accept: #ACCEPTTo Kill With Purpose# and #ACCEPTUn-Life's Little Annoyances# .  NOTE: I SKIP #NPCThe Ranger Lord's Behest# ", x = 26, y = 74, zone = "Eastern Plaguelands" },
			[4] = { str = "Go down in the crypt at The Undercroft [27,85] and accept #ACCEPTHameya's Plea# (the scroll on the ground). (??? TBC Quest?)", x = 27, y = 85, zone = "Eastern Plaguelands" },
			[5] = { str = "Grind your way to Darrowshire [36,90] while doing these quests:", x = 36, y = 90, zone = "Eastern Plaguelands" },
			[6] = { str = "#DOQUESTDemon Dogs# " },
			[7] = { str = "#DOQUESTBlood Tinged Skies# " },
			[8] = { str = "#DOQUESTCarrion Grubbage# " },
			[9] = { str = "Then turn in #TURNINSister Pamela# ... accept and do #ACCEPTPamela's Doll# (there's 3 parts of the doll)" },
			[10] = { str = "Turn in #TURNINPamela's Doll# ... accept #ACCEPTAuntie Marlene# and #ACCEPTUncle Carlin# " },
			[11] = { str = "Then go complete #DOQUESTBlood Tinged Skies# " },
			[12] = { str = "Then make sure you kill 20 Plaguehound Runts for the quest #DOQUESTDemon Dogs# " },
			[13] = { str = "Then go to Light's Hope Chapel at [81,60]", x = 81, y = 60, zone = "Eastern Plaguelands" },
			[14] = { str = "Accept: #ACCEPTZaeldarr the Outcast# and #ACCEPTThe Restless Souls# " },
			[15] = { str = "Turn in #TURNINDuke Nicholas Zverenhoff# and #TURNINUncle Carlin# ... accept #ACCEPTDefenders of Darrowshire# " },
			[16] = { str = "Get FP there.  Then go do:" },
			[17] = { str = "#DOQUESTTo Kill With Purpose# " },
			[18] = { str = "#DOQUESTDefenders of Darrowshire# " },
			[19] = { str = "#DOQUESTHameya's Plea# [72,14] (??? TBC Quest?)", x = 72, y = 14, zone = "Eastern Plaguelands" },
			[20] = { str = "#DOQUESTDemon Dogs# " },
			[21] = { str = "#DOQUESTCarrion Grubbage# " },
			[22] = { str = "#DOQUESTUn-Life's Little Annoyances# " },
			[23] = { str = "#DOQUESTA Plague Upon Thee# (done at Plaguewood up north)" },
			[24] = { str = "#DOQUESTAugustus' Receipt Book# get this quest in the hut at [13,34], the book is upstairs in the inn at [15,33]", x = 15, y = 33, zone = "Eastern Plaguelands" },
			[25] = { str = "#DOQUESTThe Restless Souls# (#NPCEgan# is in the hut at [13,34]) (The next part refers to Stratholme, which I skip)", x = 13, y = 34, zone = "Eastern Plaguelands" },
			[26] = { str = "Then go turn in: #TURNINAugustus' Receipt Book# " },
			[27] = { str = "Grind your way through the cave [15,29] (watch out it is not easy) ", x = 15, y = 29, zone = "Eastern Plaguelands" },
			[28] = { str = "#VIDEONOTE:#  If the cave is too hard for you, another easy alternative is to take the Tower Gryphon ride from the Plaguewood Tower [22,32] to the Crown Guard tower [39,75], as long as the horde has control over the towers that is.  Then turn in #TURNINDemon Dogs# #TURNINBlood Tinged Skies# and #TURNINCarrion Grubbage#   accept #ACCEPTRedemption#   ... Just talk to the guy to complete it ... I SKIP #NPCOf Forgotten Memories# (you can try it if you find a group)", x = 22, y = 32, zone = "Eastern Plaguelands" },
			[29] = { str = "Then go turn in: #TURNINTo Kill With Purpose# and #TURNINUn-Life's Little Annoyances# at [26,74]", x = 26, y = 74, zone = "Eastern Plaguelands" },
			[30] = { str = "Then go do #DOQUESTZaeldarr the Outcast# [27,85]", x = 27, y = 85, zone = "Eastern Plaguelands" },
			[31] = { str = "Then go to the dirt mound behind the crypt and turn in #TURNINHameya's Plea# (??? TBC Quest?)" },
			[32] = { str = "Then turn in: #TURNINZaeldarr the Outcast# and #TURNINDefenders of Darrowshire# at Light's Hope Chapel" },
			[33] = { str = "Hearth to Under City.." },
			[34] = { str = "Turn in #TURNINBetter Late Than Never# ... accept #ACCEPTThe Jeremiah Blues# " },
			[35] = { str = "Turn in #TURNINThe Jeremiah Blues# (just right underneath the bank) ... accept #ACCEPTGood Luck Charm# " },
			[36] = { str = "Go back to the Bulwark..." },
			--[37] = { str = "." },
			--[38] = { str = "." },
		}
	},

-----------57-58 Western Plaguelands
	--[513] = {
	[5758] = {
		title = "57-58 Western Plaguelands",
		--n = "57-58 Western Plaguelands",
		--pID = 512, nID = 514,
		--itemCount = 37,
		items = {
			[1] = { str = "57-58 Western Plaguelands" },
			[2] = { str = "Turn in #TURNINA Plague Upon Thee# ... accept #ACCEPTA Plague Upon Thee# part2." },
			[3] = { str = "Go turn in #TURNINGood Luck Charm# ...accept #ACCEPTTwo Halves Become One# The lady in the house at [37,56]", x = 37, y = 56, zone = "Western Plaguelands" },
			[4] = { str = "Do #DOQUESTTwo Halves Become One# (#NPCJabbering ghouls# out in Felstone Field drop the item you need, once you get the item right-click it in your inventory), then go back to the lady in the house to turn it in." },
			[5] = { str = "Then do #DOQUESTA Plague Upon Thee# part2 ... accept #ACCEPTA Plague Upon Thee# part3, this is all done at [48,31]  " },
			[6] = { str = "Then go accept #ACCEPTUnfinished Business# part1 at [51,28], then do it. The mobs for this quest are at [50,42] and [53,44]", x = 51, y = 28, zone = "Western Plaguelands" },
			[7] = { str = "Turn in #TURNINUnfinished Business# part1 (back at [51,28]) ... accept #ACCEPTUnfinished Business# part2, then go do it. The 2 mobs for this quest are at [57,37] and [54,24].", x = 55, y = 30, zone = "Western Plaguelands" },
			[8] = { str = "Turn in #TURNINUnfinished Business# part2 (back at [51,28]) ... accept #ACCEPTUnfinished Business# part3, then go do it. Need to go up in the tower at [45,19] in a certain spot, watch out for Elites.", x = 51, y = 28, zone = "Western Plaguelands" },
			[9] = { str = "Then turn in #TURNINUnfinished Business# part3" },
			[10] = { str = "Then go complete and turn in #TURNINThe Wildlife Suffers Too# ... accept  #ACCEPTThe Wildlife Suffers Too# part2 [53,64]", x = 53, y = 64, zone = "Western Plaguelands" },
			[11] = { str = "Do #DOQUESTThe Wildlife Suffers Too# part2, then turn it in ... accept #ACCEPTGlyphed Oaken Branch# " },
			[12] = { str = "Go turn in #TURNINAuntie Marlene#, in the house at [49,78]  ...accept #ACCEPTA Strange Historian# ", x = 49, y = 78, zone = "Western Plaguelands" },
			[13] = { str = "Go get the ring for #DOQUESTA Strange Historian# (the ring is out in the graveyard)" },
			[14] = { str = "Go into Andorhal.." },
			[15] = { str = "Do #DOQUESTAll Along the Watchtowers# while working your way to the inn at [39,66]", x = 39, y = 66, zone = "Western Plaguelands" },
			[16] = { str = "Turn in #TURNINA Strange Historian# at #NPCChromie# up stairs in the inn at [39,68] ... accept #ACCEPTThe Annals of Darrowshire# and #ACCEPTA Matter of Time# ", x = 39, y = 68, zone = "Western Plaguelands" },
			[17] = { str = "Then go do (while grinding away at mobs):" },
			[18] = { str = "#DOQUESTAll Along the Watchtowers# (Elite) " },
			[19] = { str = "#DOQUESTA Matter of Time# [47,62]", x = 47, y = 62, zone = "Western Plaguelands" },
			[20] = { str = "#DOQUESTThe Annals of Darrowshire# the book for this is in the building at [42,67], the actual Annals of Darrowshire book looks different from the others, it has a lighter tint on the top portion of the pages in the book, unlike the rest which has a darker tint on the top portion of the pages.", x = 42, y = 67, zone = "Western Plaguelands" },
			[21] = { str = "Go turn in #TURNINA Matter of Time# and #TURNINThe Annals of Darrowshire# ... accept #ACCEPTCounting Out Time# and #ACCEPTBrother Carlin# " },
			[22] = { str = "Go do #DOQUESTCounting Out Time# then turn it in. (it's repeatable but you only get XP once from it)" },
			[23] = { str = "I then keep grinding away at mobs in Andorhal till i'm Friendly with the Argent Dawn, so im able to buy Enriched Manna Biscuits (which replenish mana faster from drinking). As soon as I hit friendly with AD, I then go back to the Bulwark.." },
			[24] = { str = "Turn in #TURNINA Plague Upon Thee# part3" },
			[25] = { str = "Turn in #TURNINAll Along the Watchtowers# ... accept #ACCEPTScholomance# " },
			[26] = { str = "Turn in #TURNINScholomance# at the undead guy right next to him ... accept #ACCEPTSkeletal Fragments# " },
			[27] = { str = "Stock up on #NPCEnriched Manna Biscuits# (which replenishes mana faster from drinking)" },
			[28] = { str = "I then go back to Andorhal, and grind all the way to level 58 while doing #DOQUESTSkeletal Fragments# quest." },
			[29] = { str = "As soon as I hit 58 and #DOQUESTSkeletal Fragments# is done and you also have 30 #NPCBone Fragments# (please note, if you are far off from the 30 bone fragments, then you can just skip it), then go back to the Bulwark and turn in #TURNINSkeletal Fragments# .. I SKIP #NPCMold Rhymes With...# " },
			[30] = { str = "I turn in any scourge stones, I have." },
			[31] = { str = "I then stock up on #NPCEnriched Manna Biscuits# (about 600? :D)" },
			[32] = { str = "Then go get on the zeppelin to go to Orgrimmar. (while waiting, make heavy runecloth bandages)" },
			[33] = { str = "Once in Orgrimmar i get new spells/abilites." },
			[34] = { str = "Bank 2/3rd of my manna biscuits." },
			[35] = { str = "Then fly to Winterspring..." },
			--[36] = { str = "." },
			--[37] = { str = "." },
		}
	},

------------58-60 Winterspring
	--[514] = {
	[5860] = {
		title = "58-60 Winterspring",
		--n = "58-60 Winterspring",
		--pID = 513, nID = 514,
		--itemCount = 32,
		items = {
			[1] = { str = "58-60 Winterspring" },
			[2] = { str = "First thing i do here is stable my pet." },
			[3] = { str = "Then make Everlook your home." },
			[4] = { str = "Turn in #TURNINAre We There, Yeti?# part3" },
			[5] = { str = "Accept: #ACCEPTLuck Be With You# (Elite) and #ACCEPTUrsius of the Shardtooth# (Elite)" },
			[6] = { str = "Then go tame a Winterspring Screecher (for Claw Rank8) (head south to do this)" },
			[7] = { str = "Then use that pet to do #DOQUESTLuck Be With You# (just use your pet to distract the giants while picking up the Frostmaul Shards)" },
			[8] = { str = "Then hearth to Everlook." },
			[9] = { str = "Go do #DOQUESTUrsius of the Shardtooth# (Elite) (just keep grinding mobs on the hill north of everlook till Ursius shows up)" },
			[10] = { str = "Go turn in #TURNINLuck Be With You# (if it's done yet) and #TURNINUrsius of the Shardtooth# ... accept #ACCEPTBrumeran of the Chillwind# (Elite)" },
			[11] = { str = "Then go south and do:" },
			[12] = { str = "#DOQUESTBrumeran of the Chillwind# (Elite)" },
			[13] = { str = "#DOQUESTLuck Be With You# (Elite) (if you still need to finish it up)" },
			[14] = { str = "#DOQUESTWild Guardians# part2 (i grind away at owls at the Owl Wing Thicket for a few hours, before leaving here)" },
			[15] = { str = "Then when im a few bars away from 59, i go back up to Everlook (DONT hearth).." },
			[16] = { str = "Turn in #TURNINLuck Be With You# and #TURNINBrumeran of the Chillwind# ... i SKIP #NPCShy-Rotam# (Elite)" },
			[17] = { str = "Fly to Bloodvenom Post (Felwood).." },
			[18] = { str = "Turn in #TURNINWild Guardians# part2 ... accept #ACCEPTWild Guardians# part3" },
			[19] = { str = "Then hearth back to Everlook." },
			[20] = { str = "Then go down to the Owl Wing Thicket and do #DOQUESTWild Guardians# part3" },
			[21] = { str = "I keep grinding away at Owls till im about 59 and a half, then..." },
			[22] = { str = "I die on purpose, so i end up at Everlook (don’t hearth)" },
			[23] = { str = "Then Fly to Bloodvenom Post (Felwood).." },
			[24] = { str = "Turn in #TURNINWild Guardians# part3 and #TURNINGuarding Secrets# ... accept #ACCEPTGuarding Secrets# part2" },
			[25] = { str = "I then fly to XRs, then to Thunderbluff, go to Elder Rise.." },
			[26] = { str = "Turn in #TURNINGuarding Secrets# part2 and #TURNINGlyphed Oaken Branch# (both at Nara Wildmane)" },
			[27] = { str = "Hearth back to Everlook." },
			[28] = { str = "At this point im usually about 3/4 way to 60." },
			[29] = { str = "I then go back down to the Owl Wing Thicket and Grind to 60.  (See End Game Credits)" },
			[30] = { str = "." },
			[31] = { str = "." },
			[32] = { str = "CONGRATULATION, you're lvl60 now!"},
			[33] = { str = "." },
			--[34] = { str = "." },
		}
	},
}
