--[[--------------------------------------------------
003_Horde_30to40.lua
Authors: mrmr, lanjelin
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 30 to Lvl 40
    1.04.1
        -- First Release
            Horde's Guide
            from level 30 to lever 40
    1.04.2
    	-- no changes in here for this revision
    1.04.3
	    -- Cleanup in text, changed formatting of coords
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Horde_30to40 = {
-----------30-30 Alterac Mountains
	--[301] = {
	[3029] = {
		title = "30-30 Alterac Mountains",
		--n = "30-30 Alterac Mountains",
		--pID = 210, nID = 302,
		--itemCount = 12,
		items = {
			[1] = { str = "30-30 Alterac Mountains" },
			[2] = { str = "Do the following:" },
			[3] = { str = "#DOQUESTElixir of Pain# (killing the level 32-34 mountain lions, on the plateaus there)" },
			[4] = { str = "Charge the third flame (Flame of Uzel), for the quest #DOQUESTHelcular's Revenge# " },
			[5] = { str = "Kill #NPCFrostmaw# Yes I know your gonna be killing Frostmaw (level 37 mob) at level 30, it's a tough battle so prepare yourself! " },
			[6] = { str = "Run down to Southshore, to drive the rod into Helcular's grave. (hint: i use my pet to distract the guards, by having my pet run all over the place). This is for the quest #DOQUESTHelcular's Revenge# " },
			[7] = { str = "Run back to Tarren Mill" },
			[8] = { str = "Turn in #TURNINElixir of Pain# " },
			[9] = { str = "Accept #ACCEPTThe Hammer May Fall# " },
			[10] = { str = "Run into Arathi Highlands..." },
			--[11] = { str = "." },
			--[12] = { str = "." },
		}
	},

-----------30-30 Arathi Highlands
	--[302] = {
	[3030] = {
		title = "30-30 Arathi Highlands",
		--n = "30-30 Arathi Highlands",
		--pID = 301, nID = 303,
		--itemCount = 20,
		items = {
			[1] = { str = "30-30 Arathi Highlands" },
			[2] = { str = "Go do this quest:" },
			[3] = { str = "#DOQUESTThe Hammer May Fall# at [34,45]", x = 34, y = 45, zone = "Arathi Highlands" },
			[4] = { str = "Then run to Hammerfall at [73,36]", x = 73, y = 36, zone = "Arathi Highlands" },
			[5] = { str = "Accept #ACCEPTHammerfall# " },
			[6] = { str = "Turn in #TURNINHammerfall# ... accept #ACCEPTRaising Spirits# " },
			[7] = { str = "Turn in #TURNINThe Hammer May Fall# " },
			[8] = { str = "Get FP there." },
			[9] = { str = "Then do #DOQUESTRaising Spirits#, just to the left of Hammerfall all around [64,37].  Then turn it in ... accept #ACCEPTRaising Spirits# part2", x = 64, y = 37, zone = "Arathi Highlands" },
			[10] = { str = "Turn in #TURNINRaising Spirits# part2 ... accept #ACCEPTRaising Spirits# part3" },
			[11] = { str = "Turn in #TURNINRaising Spirits# part3 ... skip #NPCGuile of the Raptor# for now" },
			[12] = { str = "Hearth to Orgrimmar." },
			[13] = { str = "Fly to XRs." },
			[14] = { str = "Run west in the XRs ... accept #ACCEPTThe Swarm Grows# " },
			[15] = { str = "Then run west from the XRs to the guy in the hut ... accept #ACCEPTThe Kolkar of Desolace# " },
			[16] = { str = "Run back to XRs, make XRs your home." },
			[17] = { str = "Fly to Ratchet" },
			[18] = { str = "Get on the boat at Ratchet to go to BB..." },
			--[19] = { str = "." },
			--[20] = { str = "." },
		}
	},

-----------30-31 Stranglethorn Vale
	--[303] = {
	[3031] = {
		title = "30-31 Stranglethorn Vale",
		--n = "30-31 Stranglethorn Vale",
		--pID = 302, nID = 304,
		--itemCount = 18,
		items = {
			[1] = { str = "30-31 Stranglethorn Vale" },
			[2] = { str = "Get the FP at BB and run up to Grom'Gol (get the FP there too)." },
			[3] = { str = "Go up north [35,10] and start doing the STV hunt quests:", x = 35, y = 10, zone = "Stranglethorn Vale" },
			[4] = { str = "#DOQUESTWelcome to the Jungle# (just accept this and turn in in right there)" },
			[5] = { str = "#DOQUESTTiger Mastery# (#NPCYoung Stranglethorn Tigers#) [33,10]", x = 33, y = 10, zone = "Stranglethorn Vale" },
			[6] = { str = "#DOQUESTPanther Mastery# (#NPCYoung Panthers#) (41.9)", x = 41, y = 9, zone = "Stranglethorn Vale" },
			[7] = { str = "#DOQUESTPanther Mastery# (#NPCPanthers#) [30,11]", x = 30, y = 11, zone = "Stranglethorn Vale" },
			[8] = { str = "#DOQUESTTiger Mastery# (#NPCStranglethorn Tigers#) [30,10]", x = 30, y = 11, zone = "Stranglethorn Vale" },
			[9] = { str = "#DOQUESTRaptor Mastery# (#NPCStranglethorn Raptors#) [25,15]", x = 25, y = 15, zone = "Stranglethorn Vale" },
			[10] = { str = "Accept #ACCEPTTiger Mastery# (#NPCElder Stranglethorn Tigers#) .. but don't do it now." },
			[11] = { str = "Accept #ACCEPTRaptor Mastery# (#NPCLashtail Raptors#) .. but don't do it now." },
			[12] = { str = "Skip the rest for now." },
			[13] = { str = "You should belvl 31 for sure, if not grind to it" },
			[14] = { str = "Hearth to XRs." },
			[15] = { str = "Fly to 1K needles." },
			[16] = { str = "Go east into Shimmering Flats at [77,77]...", x = 77, y = 77, zone = "Thousand Needles" },
			--[17] = { str = "." },
			--[18] = { str = "." },
		}
	},

-----------31-32 Thousand needles (Shimmering Flats)
	--[304] = {
	[3132] = {
		title = "31-32 TN (Shimmering Flats)",
		--n = "31-32 TN (Shimmering Flats)",
		--pID = 303, nID = 305,
		--itemCount = 27,
		items = {
			[1] = { str = "31-32 Thousand needles (Shimmering Flats)" },
			[2] = { str = "Accept: " },
			[3] = { str = "#ACCEPTHemet Nesingwary# " },
			[4] = { str = "#ACCEPTWharfmaster Dizzywig# " },
			[5] = { str = "Accept and do the following 5 quests together:" },
			[6] = { str = "#DOQUESTA Bump in the Road# " },
			[7] = { str = "#DOQUESTHardened Shells# " },
			[8] = { str = "#DOQUESTLoad Lightening# " },
			[9] = { str = "#DOQUESTRocket Car Parts# " },
			[10] = { str = "#DOQUESTSalt Flat Venom# " },
			[11] = { str = "Turn them all in." },
			[12] = { str = "Accept:" },
			[13] = { str = "#ACCEPTGoblin Sponsorship# " },
			[14] = { str = "#ACCEPTMartek the Exiled# " },
			[15] = { str = "SKIP #ACCEPTEncrusted Tail Fins# (Elite) " },
			[16] = { str = "You may or may not be level 32 right now, if not that's okay." },
			[17] = { str = "Go south into Tanaris to get FP in Gadgetzan at [51,25]", x = 51, y = 25, zone = "Tanaris" },
			[18] = { str = "Hearth to XRs." },
			[19] = { str = "Fly to Orgrimmar" },
			[20] = { str = "Turn in #TURNINThe Swarm Grows# at [75,34] ... accept #ACCEPTThe Swarm Grows# part2", x = 75, y = 34, zone = "Orgrimmar" },
			[21] = { str = "Accept #ACCEPTAlliance Relations# from Craven Drok in the Cleft of Shadow, [47,50]", x = 47, y = 50, zone = "Orgrimmar" },
			[22] = { str = "Then go to #NPCKeldran# in Orgrimmar [23,53] to accept #ACCEPTAlliance Relations# part2.", x = 23, y = 53, zone = "Orgrimmar" },
			[23] = { str = "Stop at first aid guy to buy silk bandage training.  #VIDEONOTE:#  Make sure you save all your extra Cloths in either your bank or mailbox, you will need them later for Cloth Donation quests." },
			[24] = { str = "Then fly to Stonetalon Mountains." },
			[25] = { str = "Run into Desolace..." },
			--[26] = { str = "." },
			--[27] = { str = "." },
		}
	},

-----------32-34 Desolace
	--[305] = {
	[3234] = {
		title = "32-34 Desolace",
		--n = "32-34 Desolace",
		--pID = 304, nID = 306,
		--itemCount = 64,
		items = {
			[1] = { str = "32-34 Desolace" },
			[2] = { str = "First thing to do here is start killing mobs at the Thunder Axe Fortress [55,24]...", x = 55, y = 24, zone = "Desolace" },
			[3] = { str = "Until this item drops: #NPCFlayed Demon Skin# which starts: #ACCEPTThe Corrupter# " },
			[4] = { str = "Then go down the path and do:" },
			[5] = { str = "#DOQUESTKodo Roundup#, starts at [60,61] (don't have to finish all of it now)", x = 60, y = 61, zone = "Desolace" },
			[6] = { str = "Then go to Ghost Walker Post [56,59]", x = 56, y = 59, zone = "Desolace" },
			[7] = { str = "Turn in #TURNINThe Kolkar of Desolace# ... accept #ACCEPTKhan Dez'hepah# " },
			[8] = { str = "Accept #ACCEPTGelkis Alliance# (this is the one you should choose to do).  Skip #NPCMagram Alliance# " },
			[9] = { str = "Turn in #TURNINAlliance Relations# ... accept #ACCEPTAlliance Relations# part2 ... accept #ACCEPTBefouled by Satyr# " },
			[10] = { str = "Turn in #TURNINThe Corrupter# ... accept #ACCEPTThe Corrupter# part2" },
			[11] = { str = "Turn in #TURNINAlliance Relations# part2 ... accept #ACCEPTThe Burning of Spirits# " },
			[12] = { str = "Do in the following order:" },
			[13] = { str = "#DOQUESTBefouled by Satyr# [75,22]  (Keep step #13 in mind)", x = 75, y = 22, zone = "Desolace" },
			[14] = { str = "#DOQUESTThe Corrupter# Part2 (collect a Shadowstalker Scalp from a Hatefury shadowstalker)" },
			[15] = { str = "#DOQUESTKhan Dez'hepah# [73,48]", x = 73, y = 48, zone = "Desolace" },
			[16] = { str = "#DOQUESTGelkis Alliance# [68,71]", x = 68, y = 71, zone = "Desolace" },
			[17] = { str = "Go back to Ghost Walker Post [56,59], and turn in #TURNINKhan Dez'hepah# .. accept #ACCEPTCentaur Bounty# .  Turn in #TURNINBefouled by Satyr# .  Turn in #TURNINThe Corrupter# Part2 .. accept #ACCEPTThe Corrupter# Part3.", x = 56, y = 59, zone = "Desolace" },
			[18] = { str = "Then run to Shadowprey Village, stopping along the way to turn in #TURNINGelkis Alliance# at [36,79] ... accept #ACCEPTStealing Supplies# ", x = 36, y = 79, zone = "Desolace" },
			[19] = { str = "Accept all quests at Shadowprey Village at [24,71], which include:  #ACCEPTHunting in Stranglethorn# #ACCEPTHand of Iruxos# #ACCEPTClam Bait# and #ACCEPTOther Fish to Fry# ", x = 24, y = 71, zone = "Desolace" },
			[20] = { str = "Make Shadowprey Village your home." },
			[21] = { str = "Then do:" },
			[22] = { str = "Go in the water and collect 10 #NPCShellfish# (from the Shellfish traps)" },
			[23] = { str = "Turn those in for 2 #NPCBloodbelly Fish# " },
			[24] = { str = "Travel up the water (collecting #NPCSoft-shelled Clam Meat# for the quest #DOQUESTClam Bait# along the way)" },
			[25] = { str = "Then accept #ACCEPTClaim Rackmore's Treasure!#, the chest/wrecked boat along the shore, [36,30]  (the silver key is dropped by a drysnap, and the golden key is dropped by a Slitherblade)", x = 36, y = 30, zone = "Desolace" },
			[26] = { str = "Go accept #ACCEPTSceptre of Light# from the argent dawn dude, at [38,27]", x = 38, y = 27, zone = "Desolace" },
			[27] = { str = "Then go do following at Thunder Axe Fortress [54,29]:", x = 54, y = 29, zone = "Desolace" },
			[28] = { str = "#DOQUESTThe Burning of Spirits# " },
			[29] = { str = "#DOQUESTSceptre of Light# " },
			[30] = { str = "#DOQUESTHand of Iruxos# " },
			[31] = { str = "Then grind your way back to the argent dawn dude [38,27]...", x = 38, y = 27, zone = "Desolace" },
			[32] = { str = "Then turn #TURNINSceptre of Light# in and get #ACCEPTBook of the Ancients# quest." },
			[33] = { str = "Then go do all this stuff in the water to the west:" },
			[34] = { str = "#DOQUESTOther Fish to Fry# " },
			[35] = { str = "#DOQUESTClam Bait# " },
			[36] = { str = "#DOQUESTBook of the Ancients# (27.6) ", x = 27, y = 6, zone = "Desolace" },
			[37] = { str = "#DOQUESTThe Corrupter# Part3 (collect a Oracle Crystal from a Slitherblade Oracle)" },
			[38] = { str = "#DOQUESTClaim Rackmore's Treasure!# " },
			[39] = { str = "Then turn in #TURNINClaim Rackmore's Treasure!# at the little chest (29.8)", x = 29, y = 8, zone = "Desolace" },
			[40] = { str = "Turn in #TURNINBook of the Ancients# [38,27]", x = 38, y = 27, zone = "Desolace" },
			[41] = { str = "Then go accept #ACCEPTBone Collector#   [62,38] (grinding mobs along the way)", x = 62, y = 38, zone = "Desolace" },
			[42] = { str = "Go to Ghost Walker Post [56,59], turn in #TURNINCatch of the Day# accept and turn in #TURNINThe Burning of Spirits# #TURNINThe Corrupter# Part3 .. accept and then turn in #TURNINThe Corrupter# Part4. Accept #ACCEPTAlliance Relations# Skip #NPCThe Corrupter# Part5.", x = 56, y = 59, zone = "Desolace" },
			[43] = { str = "Then go do:" },
			[44] = { str = "#DOQUESTBone Collector#, done at the kodo graveyard, [51,58]", x = 51, y = 58, zone = "Desolace" },
			[45] = { str = "Then #DOQUESTCentaur Bounty# and #DOQUESTStealing Supplies# [70,74]", x = 70, y = 74, zone = "Desolace" },
			[46] = { str = "Then go turn in #TURNINCentaur Bounty# [56,59]", x = 56, y = 59, zone = "Desolace" },
			[47] = { str = "Then turn in #TURNINBone Collector# [62,38]", x = 62, y = 38, zone = "Desolace" },
			[48] = { str = "Hearth to Shadowprey Village." },
			[49] = { str = "Turn in all quests there, which are: #TURNINHand of Iruxos# #TURNINOther Fish to Fry# and #TURNINClam Bait# " },
			[50] = { str = "You should be level 34 now for sure." },
			[51] = { str = "Turn in #TURNINStealing Supplies# [36,79] and accept #ACCEPTOngeku# ", x = 36, y = 79, zone = "Desolace" },
			[52] = { str = "Fly to CT (In the Barrens). (the flight master is on the docks in Shadowprey Village)" },
			[53] = { str = "Once at CT, run south-east into Dustwallow Marsh ([51,79] in the Barrens).", x = 51, y = 79, zone = "The Barrens" },
			[54] = { str = "Collect the 3 quest-objects at the Shady Rest Inn: " },
			[55] = { str = "#ACCEPTSuspicious Hoofprints# (just right outside in front of the inn)" },
			[56] = { str = "#ACCEPTLieutenant Paval Reethe# (laying on one of the planks on the ground)" },
			[57] = { str = "#ACCEPTThe Black Shield# (on top of the fireplace)" },
			[58] = { str = "Now run to Brackenwall Village [35,29]", x = 35, y = 29, zone = "Dustwallow Marsh" },
			[59] = { str = "Turn those 3 quests in (#TURNINSuspicious Hoofprints# #TURNINLieutenant Paval Reethe# and #TURNINThe Black Shield# ) ... accept and then turn in #TURNINThe Black Shield# Part2.  Skip #NPCThe Black Shield# Part3 for now." },
			[60] = { str = "Stop at the troll vendor, buy the 3 first aid books." },
			[61] = { str = "Fly to Ratchet to turn in #TURNINGoblin Sponsorship# & #TURNINWharfmaster Dizzywig# ... accept #ACCEPTGoblin Sponsorship# Part2 and #ACCEPTParts for Kravel# " },
			[62] = { str = "Get on the boat to go to BB (Booty Bay) ... (while waiting for the boat, build up first aid)" },
			--[63] = { str = "." },
			--[64] = { str = "." },
		}
	},

-----------34-35 Stranglethorn Vale
	--[306] = {
	[3435] = {
		title = "34-35 Stranglethorn Vale",
		--n = "34-35 Stranglethorn Vale",
		--pID = 305, nID = 307,
		--itemCount = 37,
		items = {
			[1] = { str = "34-35 Stranglethorn Vale" },
			[2] = { str = "Turn in #TURNINGoblin Sponsorship# Part2 .. accept #ACCEPTGoblin Sponsorship# Part3.  Make BB your home!  Accept #ACCEPTSinging Blue Shards# #ACCEPTBloodscalp Ears# #ACCEPTHostile Takeover# and #ACCEPTInvestigate the Camp# .  Turn in #TURNINGoblin Sponsorship# Part3 at Baron Revilgaz ... accept #ACCEPTGoblin Sponsorship# Part4." },
			[3] = { str = "Then do the following:" },
			[4] = { str = "Fly to Grom'gol..." },
			[5] = { str = "Grab ALL quests in grom'gol:  #ACCEPTThe Defense of Grom'gol# #ACCEPTMok'thardin's Enchantment# #ACCEPTBloodscalp Insight# #ACCEPTHunt for Yenniku# #ACCEPTTrollbane# #ACCEPTBloody Bone Necklaces# #ACCEPTThe Vile Reef# " },
			[6] = { str = "#HUNTER05) Get new hunter spells/abilities.#" },
			[7] = { str = "#VIDEOIMPORTANT:#  Make sure you save any Green Hills of Stranglethorn pages you find and mail them to your alt for storage, you will need them for a later #DOQUESTquest#.  You will need one of each of the following pages: 1, 4, 6, 8, 10, 11, 14, 16, 18, 20, 21, 24, 25, 26, and 27.  Once your alt collects all the pages, mail them back to your main.  Now go complete these quests:" },
			[8] = { str = "#DOQUESTSinging Blue Shards# [25,19]", x = 25, y = 19, zone = "Stranglethorn Vale" },
			[9] = { str = "#DOQUESTTiger Mastery# (#NPCElder Stranglethorn Tigers#) [31,19]", x = 31, y = 19, zone = "Stranglethorn Vale" },
			[10] = { str = "#DOQUESTBloodscalp Ears# and..." },
			[11] = { str = "#DOQUESTHunt for Yenniku# " },
			[12] = { str = "#DOQUESTBloody Bone Necklaces# (you don't have to finish all of this now)" },
			[13] = { str = "#DOQUESTRaptor Mastery# (#NPCLashtail Raptors#)" },
			[14] = { str = "#DOQUESTThe Defense of Grom'gol# " },
			[15] = { str = "Once all those are done (besides #DOQUESTBloody Bone Necklaces# ), go to Grom'gol.." },
			[16] = { str = "Turn in #TURNINHunt for Yenniku# ... accept #ACCEPTHeadhunting# " },
			[17] = { str = "Turn in #TURNINThe Defense of Grom'gol# ... accept #ACCEPTThe Defense of Grom'gol# part2." },
			[18] = { str = "Should be lvl 35 now, either way buy lvl 35 food/water/repair (so that you are prepared for when you do turn level 35), then go do in the following order:" },
			[19] = { str = "#DOQUESTHeadhunting# along with finishing up #DOQUESTBloody Bone Necklaces# [21,14]", x = 21, y = 14, zone = "Stranglethorn Vale" },
			[20] = { str = "#DOQUESTThe Vile Reef# along with #DOQUESTEncrusted Tail Fins# [24,24] Use a breath potion if you can.", x = 24, y = 24, zone = "Stranglethorn Vale" },
			[21] = { str = "Then go to Nesingwary's Expedition [35,10]... turn in ALL quests, accept all new ones (except #NPCThe Green Hills of Stranglethorn# ).  Then go do:", x = 35, y = 10, zone = "Stranglethorn Vale" },
			[22] = { str = "#DOQUESTTiger Mastery# (#NPCSin'Dall#), he is usually on top of the hill at [31,17].  Once that is done, go turn it in, then go do:", x = 31, y = 17, zone = "Stranglethorn Vale" },
			[23] = { str = "#DOQUESTHostile Takeover# along with #DOQUESTGoblin Sponsorship# [44,19]", x = 44, y = 19, zone = "Stranglethorn Vale" },
			[24] = { str = "#DOQUESTPanther Mastery# along with #DOQUESTMok'thardin's Enchantment# (kill #NPCshadowmaw panthers#) [48,21]", x = 48, y = 21, zone = "Stranglethorn Vale" },
			[25] = { str = "#DOQUESTThe Defense of Grom'gol# part2 [36,30], once that's done...", x = 36, y = 30, zone = "Stranglethorn Vale" },
			[26] = { str = "Head up north and turn in #TURNINPanther Mastery# ...accept #ACCEPTPanther Mastery# (#NPCBhag'thera#) but don't do it now." },
			[27] = { str = "Hearth to BB, turn in #TURNINSinging Blue Shards# #TURNINHostile Takeover# #TURNINBloodscalp Ears# #TURNINInvestigate the Camp# " },
			[28] = { str = "Turn in #TURNINGoblin Sponsorship# part4 ... accept #ACCEPTGoblin Sponsorship# part5." },
			[29] = { str = "Fly to Grom'gol, turn in all quests: #TURNINThe Defense of Grom'gol# #TURNINMok'thardin's Enchantment# #TURNINHeadhunting# #TURNINBloody Bone Necklaces# and #TURNINThe Vile Reef# " },
			[30] = { str = "Should be level 36 now, if not, grind to it. Accept #AcceptTrollbane#. #HUNTERThen get new hunter spells/abilities.#" },
			[31] = { str = "Get on the zeppelin to go to the Undercity." },
			[32] = { str = "Once in the UC, turn in 60 Silk Cloth for #TURNINA Donation of Silk# quest at [71,28].", x = 71, y = 28, zone = "Undercity" },
			[33] = { str = "Accept #ACCEPTTo Steal From Thieves# [63,49]", x = 63, y = 49, zone = "Undercity" },
			[34] = { str = "Then fly to Hammerfall..." },
			--[35] = { str = "." },
			--[36] = { str = "." },
		}
	},

-----------35-37 Arathi Highlands
	--[307] = {
	[3537] = {
		title = "35-37 Arathi Highlands",
		--n = "35-37 Arathi Highlands",
		--pID = 306, nID = 308,
		--itemCount = 28,
		items = {
			[1] = { str = "35-37 Arathi Highlands" },
			[2] = { str = "Make Hammerfall your home." },
			[3] = { str = "Turn in #TURNINTrollbane# ... I SKIP #NPCSigil of Strom# " },
			[4] = { str = "Accept #ACCEPTCall to Arms#, #ACCEPTFoul Magics# and #ACCEPTGuile of the Raptor# " },
			[5] = { str = "Grind your way down south and do: #DOQUESTCall to Arms# " },
			[6] = { str = "Then go west of hammerfall and accept #ACCEPTThe Princess Trapped# [62,33]", x = 62, y = 33, zone = "Arathi Highlands" },
			[7] = { str = "Then go do #DOQUESTThe Princess Trapped# (mobs are east of hammerfall)" },
			[8] = { str = "Go in the cave (look for the tree, shows you where the hidden path is)..." },
			[9] = { str = "Then turn in #TURNINThe Princess Trapped# (in the cave)... accept #ACCEPTStones of Binding# " },
			[10] = { str = "Then turn in #TURNINCall to Arms# ... accept #ACCEPTCall to Arms# " },
			[11] = { str = "Build up first aid, go do #DOQUESTTriage#  (Doctor Gregory Victor, first aid training in Hammerfall)" },
			[12] = { str = "Then do:" },
			[13] = { str = "#DOQUESTStones of Binding# First key, just west of hammerfall [66,29]", x = 66, y = 29, zone = "Arathi Highlands" },
			[14] = { str = "Then do: #DOQUESTTo Steal From Thieves# at [54,40]", x = 54, y = 40, zone = "Arathi Highlands" },
			[15] = { str = "Go down south a little and get the next key for #DOQUESTStones of Binding# [52,50]", x = 52, y = 50, zone = "Arathi Highlands" },
			[16] = { str = "Then go down and do:" },
			[17] = { str = "#DOQUESTCall to Arms# (killing ogres) and #DOQUESTGuile of the Raptor# (killing Highland Fleshstalkers) around [50,75]", x = 50, y = 75, zone = "Arathi Highlands" },
			[18] = { str = "Then go up and do #DOQUESTFoul Magics# at [31,28]", x = 31, y = 28, zone = "Arathi Highlands" },
			[19] = { str = "Then go west and get the last key for #DOQUESTStones of Binding# [25,31]", x = 25, y = 31, zone = "Arathi Highlands" },
			[20] = { str = "Go discover Stromguard, and turn in #TURNINStones of Binding# (at the Circle of Inner Binding) [36,57]", x = 36, y = 57, zone = "Arathi Highlands" },
			[21] = { str = "Note: i SKIP #NPCBreaking the Keystone# (Elite)" },
			[22] = { str = "Hearth to Hammerfall." },
			[23] = { str = "Turn in #TURNINFoul Magics# #TURNINGuile of the Raptor# and #TURNINCall to Arms# " },
			[24] = { str = "Complete the #DOQUESTGuile of the Raptor# quest chain by running back and forth..." },
			[25] = { str = "NOTE: i SKIP all stromguard quests (but I still recommend doing them if you can find groups)" },
			[26] = { str = "Fly to Tarren Mill..." },
			--[27] = { str = "." },
			--[28] = { str = "." },
		}
	},

-----------37-37 Alterac Mountains
	--[308] = {
	[3736] = {
		title = "37-37 Alterac Mountains",
		--n = "37-37 Alterac Mountains",
		--pID = 307, nID = 309,
		--itemCount = 16,
		items = {
			[1] = { str = "37-37 Alterac Mountains" },
			[2] = { str = "Once at TM, accept #ACCEPTStone Tokens# and #ACCEPTPrison Break In# " },
			[3] = { str = "Then go do them in Alterac Mountains (at Dalaran)" },
			[4] = { str = "Then turn them in and accept #ACCEPTDalaran Patrols# and #ACCEPTBracers of Binding# " },
			[5] = { str = "Then go do them in Alterac Mountains (at Dalaran)" },
			[6] = { str = "Once they are both completed, die on purpose, so u end up at TM" },
			[7] = { str = "Turn them in" },
			[8] = { str = "Then fly to the UC." },
			[9] = { str = "Once at UC, turn in #TURNINTo Steal From Thieves# and buy 3x#NPCSoothing Spices" },
			[10] = { str = "Get on zeppelin to go to orgrimmar." },
			[11] = { str = "Once in Orgrimmar, turn in #TURNINAlliance Relations# at #NPCKeldran#. at [21,53]", x = 21, y = 53, zone = "Orgrimmar" },
			[12] = { str = "Then fly to XRs." },
			[13] = { str = "Make XRs your home." },
			[14] = { str = "Fly to Freewind Post (1k needles)..." },
			--[15] = { str = "." },
			--[16] = { str = "." },
		}
	},

-----------37-37 Thousand Needles
	--[309] = {
	[3737] = {
		title = "37-37 Thousand Needles",
		--n = "37-37 Thousand Needles",
		--pID = 308, nID = 310,
		--itemCount = 14,
		items = {
			[1] = { str = "37-37 Thousand Needles" },
			[2] = { str = "Run towards the Shimmering Flats.." },
			[3] = { str = "Turn in #TURNINThe Swarm Grows# ... accept #ACCEPTThe Swarm Grows# part2 [67,63]", x = 67, y = 63, zone = "Thousand Needles" },
			[4] = { str = "Stop at the goblins and turn in #TURNINParts for Kravel# ... accept #ACCEPTDelivery to the Gnomes# ... turn in #TURNINDelivery to the Gnomes# .  Turn in #TURNINGoblin Sponsorship# part3 ... accept #ACCEPTThe Eighteenth Pilot# .  Turn in #TURNINThe Eighteenth Pilot#   ... accept #ACCEPTRazzeric's Tweaking# .  Turn in #TURNINEncrusted Tail Fins# " },
			[5] = { str = "Accept #ACCEPTThe Rumormonger# " },
			[6] = { str = "Do the following quests:" },
			[7] = { str = "#DOQUESTThe Swarm Grows# and #DOQUESTParts of the Swarm# (quest starts from an item drop) [71,85]", x = 71, y = 85, zone = "Thousand Needles" },
			[8] = { str = "Then go turn in #TURNINThe Swarm Grows# [67,63]", x = 67, y = 63, zone = "Thousand Needles" },
			[9] = { str = "Hearth to XRs" },
			[10] = { str = "Turn in #TURNINParts of the Swarm# ... accept #ACCEPTParts of the Swarm# part2" },
			[11] = { str = "Get new spells/abilities." },
			[12] = { str = "Fly to Dustwallow Marsh..." },
			--[13] = { str = "." },
			--[14] = { str = "." },
		}
	},

-----------37-38 Dustwallow Marsh
	--[310] = {
	[3738] = {
		title = "37-38 Dustwallow Marsh",
		--n = "37-38 Dustwallow Marsh",
		--pID = 309, nID = 311,
		--itemCount = 25,
		items = {
			[1] = { str = "37-38 Dustwallow Marsh" },
			[2] = { str = "Accept #ACCEPTTheramore Spies# and #ACCEPTThe Black Shield# " },
			[3] = { str = "Go slightly south of Brackenwall Village and accept #ACCEPTHungry!# from the ogre at [35,37]", x = 35, y = 37, zone = "Dustwallow Marsh" },
			[4] = { str = "I turn this zone into a quest-grind area, ill move around killing anything in my path while focusing on these quests:" },
			[5] = { str = "#DOQUESTTheramore Spies#, #DOQUESTThe Black Shield# #DOQUESTHungry!#  I do #DOQUESTHungry!# at [58,23]", x = 58, y = 23, zone = "Dustwallow Marsh" },
			[6] = { str = "I stop at Jarl's cabin [55,25] and get #ACCEPTThe Lost Report# quest (the dirt mound next to his cabin)", x = 55, y = 25, zone = "Dustwallow Marsh" },
			[7] = { str = "And turn in #TURNINSoothing Spices# ... accept #ACCEPTJarl Needs Eyes#" },
			[8] = { str = "Go south at [54,56] to retrive the Seaforium Booster for Razzeric", x = 54, y = 56, zone = "Dustwallow Marsh" },
			[9] = { str = "Go do #DOQUESTJarl Needs Eyes# (while focusing on the others too)" },
			[10] = { str = "I do the escort quest #DOQUESTStinky's Escape# that starts at [47,18] (grind mobs during this quest)", x = 47, y = 18, zone = "Dustwallow Marsh" },
			[11] = { str = "I'll stop at the big raptor spot at [47,17], and grind it clear several times." , x = 47, y = 17, zone = "Dustwallow Marsh" },
			[12] = { str = "Stop at Brackenwall Village and turn in all quests, accept new ones." },
			[13] = { str = "Turn in #TURNINHungry!#" },
			[14] = { str = "Stop back at Jarl's cabin at [55,25], go to the dirt mound once again to get #NPCThe Severed Head#", x = 55, y = 25, zone = "Dustwallow Marsh" },
			[15] = { str = "Turn in #TURNINJarl Needs Eyes# ... i SKIP #TURNINJarl Needs a Blade#" },
			[16] = { str = "I grind some more at the raptors and such, at this point i should be a little over half way to 39." },
			[17] = { str = "I then go do this quest:" },
			[18] = { str = "#DOQUESTThe Theramore Docks# the Captain's Documents are under the water at [71,51]" , x = 71, y = 51, zone = "Dustwallow Marsh" },
			[19] = { str = "I then die on purpose, so i end up right at Brackenwall Village." },
			[20] = { str = "Turn in #TURNINThe Theramore Docks#" },
			[21] = { str = "Turn in #TURNINThe Severed Head# ... accept #ACCEPTThe Troll Witchdoctor#" },
			--[BB] = { str = "CC) Kill Deadmire at XX.YY" , x = XX, y = YY, zone = "Dustwallow Marsh" },
			[22] = { str = "Hearth to XRs" },
			[23] = { str = "Fly to Ratchet, turn in #TURNINStinky's Escape# while your there." },
			[24] = { str = "Get on the boat to go to BB..." },
			--[25] = { str = "." },
			--[26] = { str = "." },
		}
	},

-----------38-40 Stranglethorn Vale
	--[311] = {
	[3840] = {
		title = "38-40 Stranglethorn Vale",
		--n = "38-40 Stranglethorn Vale",
		--pID = 310, nID = 401,
		--itemCount = 34,
		items = {
			[1] = { str = "38-40 Stranglethorn Vale" },
			[2] = { str = "Accept #ACCEPTThe Bloodsail Buccaneers#, #ACCEPTVenture Company Mining# and #ACCEPTScaring Shaky# " },
			[3] = { str = "Make BB your home, then go up the steps and turn in #TURNINThe Rumormonger# " },
			[4] = { str = "Fly to Grom'gol." },
			[5] = { str = "Accept #ACCEPTMok'thardin's Enchantment# " },
			[6] = { str = "Turn in #TURNINThe Troll Witchdoctor# ... right click the cauldron ... accept #ACCEPTMarg Speaks# " },
			[7] = { str = "Go do:" },
			[8] = { str = "#DOQUESTRaptor Mastery# along with #DOQUESTMok'thardin's Enchantment# [31,41]  (Kill #NPCJungle Stalkers#)", x = 31, y = 41, zone = "Stranglethorn Vale" },
			[9] = { str = "Grind away at raptors/cold eye ballisks till level 39, then do:" },
			[10] = { str = "#DOQUESTVenture Company Mining# at [40,42]", x = 40, y = 42, zone = "Stranglethorn Vale" },
			[11] = { str = "Once that is done, go back to Grom'Gol and turn in #TURNINMok'thardin's Enchantment# ... accept #ACCEPTMok'thardin's Enchantment# part3." },
			[12] = { str = "Then do #DOQUESTPanther Mastery# (#NPCBhag'thera#) (he has 3 different spawn points, either at [48,20], [49,23], or [47,26])", x = 48, y = 20, zone = "Stranglethorn Vale" },
			[13] = { str = "Then turn in #TURNINPanther Mastery# (#NPCBhag'thera#) and #TURNINRaptor Mastery# (#NPCJungle Stalkers#) at Nesingwary's Expedition [35,10]", x = 35, y = 10, zone = "Stranglethorn Vale" },
			[14] = { str = "Accept #ACCEPTRaptor Mastery# (#NPCTethis#) but don't do it now." },
			[15] = { str = "Hearth to BB." },
			[16] = { str = "Turn in #TURNINVenture Company Mining# " },
			[17] = { str = "Then go do:" },
			[18] = { str = "#DOQUESTThe Bloodsail Buccaneers# (just slightly north-west of BB at [27,69], there's a little note on a barrel, click on it, accept new quest). ", x = 27, y = 69, zone = "Stranglethorn Vale" },
			[19] = { str = "#DOQUESTScaring Shaky# along with #DOQUESTMok'thardin's Enchantment# part3 [32,66]", x = 32, y = 66, zone = "Stranglethorn Vale" },
			[20] = { str = "Once that's done run back into BB." },
			[21] = { str = "Turn in #TURNINScaring Shaky# ... accept #ACCEPTReturn to MacKinley# " },
			[22] = { str = "Turn in #TURNINThe Bloodsail Buccaneers# ... accept #ACCEPTThe Bloodsail Buccaneers# " },
			[23] = { str = "Turn in #TURNINReturn to MacKinley# " },
			[24] = { str = "Then turn in #TURNINThe Bloodsail Buccaneers# at Fleet Master Seahorn." },
			[25] = { str = "Fly to Grom'gol." },
			[26] = { str = "Turn in #TURNINMok'thardin's Enchantment# part3  ... accept #ACCEPTMok'thardin's Enchantment# part4" },
			[27] = { str = "You should be level 40 for sure now. If not grind the rest of the way to 40 on raptors/cold eye basilisks." },
			[28] = { str = "OPTIONAL: Scarlet Monastery instance instead of the grinding." },
			[29] = { str = "#HUNTER28) I get new hunter spells/abilities at grom'gol, also make sure you get the lvl 40 arrows/bullets.#" },
			[30] = { str = "Then get on the zeppelin to go to the UC." },
			[31] = { str = "Fly to Hammerfall and stop at the inn to get the #NPCFrost Oil#, the #NPCGyrochronatom#, the #NPCHealing Potion#, the #NPCLesser Invisibility Potion# and the #NPCPatterned Bronze Bracers# items for some free XP in Badlands." },
			[32] = { str = "Run all the way to the Badlands..." },
			--[33] = { str = "." },
			--[34] = { str = "." },
		}
	},
}
