--[[--------------------------------------------------
003_Horde_30to40.lua
Authors: mrmr, lanjelin
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 30 to Lvl 40
    1.04.1
        -- First Release
            Horde's Guide
            from level 30 to lever 40
    1.04.2
    	-- no changes in here for this revision
    1.04.3
	    -- Cleanup in text, changed formatting of coords
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Horde_30to40 = {
-----------30-30 Alterac Mountains
	--[301] = {
	[3029] = {
		title = "30-30 Alterac Mountains",
		--n = "30-30 Alterac Mountains",
		--pID = 210, nID = 302,
		--itemCount = 12,
		items = {
			[1] = { str = "30-30 Alterac Mountains" },
			[2] = { str = "Do the following:" },
			[3] = { str = "#DOElixir of Pain# (killing the level 32-34 mountain lions, on the plateaus there)" },
			[4] = { str = "Charge the third flame (Flame of Uzel), for the quest #DOHelcular's Revenge# " },
			[5] = { str = "Kill #NPCFrostmaw# Yes I know your gonna be killing Frostmaw (level 37 mob) at level 30, it's a tough battle so prepare yourself! " },
			[6] = { str = "Run down to Southshore, to drive the rod into Helcular's grave. (hint: i use my pet to distract the guards, by having my pet run all over the place). This is for the quest #DOHelcular's Revenge# " },
			[7] = { str = "Run back to Tarren Mill" },
			[8] = { str = "Turn in #INElixir of Pain# " },
			[9] = { str = "Accept #GETThe Hammer May Fall# " },
			[10] = { str = "Run into Arathi Highlands..." },
			--[11] = { str = "." },
			--[12] = { str = "." },
		}
	},

-----------30-30 Arathi Highlands
	--[302] = {
	[3030] = {
		title = "30-30 Arathi Highlands",
		--n = "30-30 Arathi Highlands",
		--pID = 301, nID = 303,
		--itemCount = 20,
		items = {
			[1] = { str = "30-30 Arathi Highlands" },
			[2] = { str = "Go do this quest:" },
			[3] = { str = "#DOThe Hammer May Fall# at #COORD[34,45]#", x = 34, y = 45, zone = "Arathi Highlands" },
			[4] = { str = "Then run to Hammerfall at #COORD[73,36]#", x = 73, y = 36, zone = "Arathi Highlands" },
			[5] = { str = "Accept #GETHammerfall# " },
			[6] = { str = "Turn in #INHammerfall# ... accept #GETRaising Spirits# " },
			[7] = { str = "Turn in #INThe Hammer May Fall# " },
			[8] = { str = "Get FP there." },
			[9] = { str = "Then do #DORaising Spirits#, just to the left of Hammerfall all around #COORD[64,37]#.  Then turn it in ... accept #GETRaising Spirits# part2", x = 64, y = 37, zone = "Arathi Highlands" },
			[10] = { str = "Turn in #INRaising Spirits# part2 ... accept #GETRaising Spirits# part3" },
			[11] = { str = "Turn in #INRaising Spirits# part3 ... skip #NPCGuile of the Raptor# for now" },
			[12] = { str = "Hearth to Orgrimmar. Put [Frostmaw's Mane] into the bank to save bagspace. It will not be turned in until level 43." },
			[13] = { str = "Fly to XRs." },
			[14] = { str = "Run west in the XRs ... accept #GETThe Swarm Grows# " },
			[15] = { str = "Then run west from the XRs to the guy in the hut ... accept #GETThe Kolkar of Desolace# " },
			[16] = { str = "Run back to XRs, make XRs your home." },
			[17] = { str = "Fly to Ratchet" },
			[18] = { str = "Get on the boat at Ratchet to go to BB..." },
			--[19] = { str = "." },
			--[20] = { str = "." },
		}
	},

-----------30-31 Stranglethorn Vale
	--[303] = {
	[3031] = {
		title = "30-31 Stranglethorn Vale",
		--n = "30-31 Stranglethorn Vale",
		--pID = 302, nID = 304,
		--itemCount = 18,
		items = {
			[1] = { str = "30-31 Stranglethorn Vale" },
			[2] = { str = "Get the FP at BB and run up to Grom'Gol (get the FP there too)." },
			[3] = { str = "Go up north #COORD[35,10]# and start doing the STV hunt quests:", x = 35, y = 10, zone = "Stranglethorn Vale" },
			[4] = { str = "#DOWelcome to the Jungle# (just accept this and turn in in right there)" },
			[5] = { str = "#DOTiger Mastery# (#NPCYoung Stranglethorn Tigers#) #COORD[33,10]#", x = 33, y = 10, zone = "Stranglethorn Vale" },
			[6] = { str = "#DOPanther Mastery# (#NPCYoung Panthers#) (41.9)", x = 41, y = 9, zone = "Stranglethorn Vale" },
			[7] = { str = "#DOPanther Mastery# (#NPCPanthers#) #COORD[30,11]#", x = 30, y = 11, zone = "Stranglethorn Vale" },
			[8] = { str = "#DOTiger Mastery# (#NPCStranglethorn Tigers#) #COORD[30,10]#", x = 30, y = 11, zone = "Stranglethorn Vale" },
			[9] = { str = "#DORaptor Mastery# (#NPCStranglethorn Raptors#) #COORD[25,15]#", x = 25, y = 15, zone = "Stranglethorn Vale" },
			[10] = { str = "Accept #GETTiger Mastery# (#NPCElder Stranglethorn Tigers#) .. but don't do it now." },
			[11] = { str = "Accept #GETRaptor Mastery# (#NPCLashtail Raptors#) .. but don't do it now." },
			[12] = { str = "Skip the rest for now." },
			[13] = { str = "You should belvl 31 for sure, if not grind to it" },
			[14] = { str = "Hearth to XRs." },
			[15] = { str = "Fly to 1K needles." },
			[16] = { str = "Go east into Shimmering Flats at #COORD[77,77]#...", x = 77, y = 77, zone = "Thousand Needles" },
			--[17] = { str = "." },
			--[18] = { str = "." },
		}
	},

-----------31-32 Thousand needles (Shimmering Flats)
	--[304] = {
	[3132] = {
		title = "31-32 TN (Shimmering Flats)",
		--n = "31-32 TN (Shimmering Flats)",
		--pID = 303, nID = 305,
		--itemCount = 27,
		items = {
			[1] = { str = "31-32 Thousand needles (Shimmering Flats)" },
			[2] = { str = "Accept: " },
			[3] = { str = "#GETHemet Nesingwary# " },
			[4] = { str = "#GETWharfmaster Dizzywig# " },
			[5] = { str = "Accept and do the following 5 quests together:" },
			[6] = { str = "#DOA Bump in the Road# " },
			[7] = { str = "#DOHardened Shells# " },
			[8] = { str = "#DOLoad Lightening# " },
			[9] = { str = "#DORocket Car Parts# " },
			[10] = { str = "#DOSalt Flat Venom# " },
			[11] = { str = "Turn them all in." },
			[12] = { str = "Accept:" },
			[13] = { str = "#GETGoblin Sponsorship# " },
			[14] = { str = "#GETMartek the Exiled# " },
			[15] = { str = "SKIP #GETEncrusted Tail Fins# (Elite) " },
			[16] = { str = "You may or may not be level 32 right now, if not that's okay." },
			[17] = { str = "Go south into Tanaris to get FP in Gadgetzan at #COORD[51,25]#", x = 51, y = 25, zone = "Tanaris" },
			[18] = { str = "Hearth to XRs." },
			[19] = { str = "Fly to Orgrimmar" },
			[20] = { str = "Turn in #INThe Swarm Grows# at #COORD[75,34]# ... accept #GETThe Swarm Grows# part2", x = 75, y = 34, zone = "Orgrimmar" },
			[21] = { str = "Accept #GETAlliance Relations# from Craven Drok in the Cleft of Shadow, #COORD[47,50]#", x = 47, y = 50, zone = "Orgrimmar" },
			[22] = { str = "Then go to #NPCKeldran# in Orgrimmar #COORD[23,53]# to accept #GETAlliance Relations# part2.", x = 23, y = 53, zone = "Orgrimmar" },
			[23] = { str = "Stop at first aid guy to buy silk bandage training.  #VIDEONOTE:#  Make sure you save all your extra Cloths in either your bank or mailbox, you will need them later for Cloth Donation quests." },
			[24] = { str = "Then fly to Stonetalon Mountains." },
			[25] = { str = "Run into Desolace..." },
			--[26] = { str = "." },
			--[27] = { str = "." },
		}
	},

-----------32-34 Desolace
	--[305] = {
	[3234] = {
		title = "32-34 Desolace",
		--n = "32-34 Desolace",
		--pID = 304, nID = 306,
		--itemCount = 64,
		items = {
			[1] = { str = "32-34 Desolace" },
			[2] = { str = "First thing to do here is start killing mobs at the Thunder Axe Fortress #COORD[55,24]#...", x = 55, y = 24, zone = "Desolace" },
			[3] = { str = "Until this item drops: #NPCFlayed Demon Skin# which starts: #GETThe Corrupter# " },
			[4] = { str = "Then go down the path and do:" },
			[5] = { str = "#DOKodo Roundup#, starts at #COORD[60,61]# (don't have to finish all of it now)", x = 60, y = 61, zone = "Desolace" },
			[6] = { str = "Then go to Ghost Walker Post #COORD[56,59]#", x = 56, y = 59, zone = "Desolace" },
			[7] = { str = "Turn in #INThe Kolkar of Desolace# ... accept #GETKhan Dez'hepah# " },
			[8] = { str = "Accept #GETGelkis Alliance# (this is the one you should choose to do).  Skip #NPCMagram Alliance# " },
			[9] = { str = "Turn in #INAlliance Relations# ... accept #GETAlliance Relations# part2 ... accept #GETBefouled by Satyr# " },
			[10] = { str = "Turn in #INThe Corrupter# ... accept #GETThe Corrupter# part2" },
			[11] = { str = "Turn in #INAlliance Relations# part2 ... accept #GETThe Burning of Spirits# " },
			[12] = { str = "Do in the following order:" },
			[13] = { str = "#DOBefouled by Satyr# #COORD[75,22]#  (Keep step #13 in mind)", x = 75, y = 22, zone = "Desolace" },
			[14] = { str = "#DOThe Corrupter# Part2 (collect a Shadowstalker Scalp from a Hatefury shadowstalker)" },
			[15] = { str = "#DOKhan Dez'hepah# #COORD[73,48]#", x = 73, y = 48, zone = "Desolace" },
			[16] = { str = "#DOGelkis Alliance# #COORD[68,71]#", x = 68, y = 71, zone = "Desolace" },
			[17] = { str = "Go back to Ghost Walker Post #COORD[56,59]#, and turn in #INKhan Dez'hepah# .. accept #GETCentaur Bounty# .  Turn in #INBefouled by Satyr# .  Turn in #INThe Corrupter# Part2 .. accept #GETThe Corrupter# Part3.", x = 56, y = 59, zone = "Desolace" },
			[18] = { str = "Then run to Shadowprey Village, stopping along the way to turn in #INGelkis Alliance# at #COORD[36,79]# ... accept #GETStealing Supplies# ", x = 36, y = 79, zone = "Desolace" },
			[19] = { str = "Accept all quests at Shadowprey Village at #COORD[24,71]#, which include:  #GETHunting in Stranglethorn# #GETHand of Iruxos# #GETClam Bait# and #GETOther Fish to Fry# ", x = 24, y = 71, zone = "Desolace" },
			[20] = { str = "Make Shadowprey Village your home." },
			[21] = { str = "Then do:" },
			[22] = { str = "Go in the water and collect 10 #NPCShellfish# (from the Shellfish traps)" },
			[23] = { str = "Turn those in for 2 #NPCBloodbelly Fish# " },
			[24] = { str = "Travel up the water (collecting #NPCSoft-shelled Clam Meat# for the quest #DOClam Bait# along the way)" },
			[25] = { str = "Then accept #GETClaim Rackmore's Treasure!#, the chest/wrecked boat along the shore, #COORD[36,30]#  (the silver key is dropped by a drysnap, and the golden key is dropped by a Slitherblade)", x = 36, y = 30, zone = "Desolace" },
			[26] = { str = "Go accept #GETSceptre of Light# from the argent dawn dude, at #COORD[38,27]#", x = 38, y = 27, zone = "Desolace" },
			[27] = { str = "Then go do following at Thunder Axe Fortress #COORD[54,29]#:", x = 54, y = 29, zone = "Desolace" },
			[28] = { str = "#DOThe Burning of Spirits# " },
			[29] = { str = "#DOSceptre of Light# " },
			[30] = { str = "#DOHand of Iruxos# " },
			[31] = { str = "Then grind your way back to the argent dawn dude #COORD[38,27]#...", x = 38, y = 27, zone = "Desolace" },
			[32] = { str = "Then turn #INSceptre of Light# in and get #GETBook of the Ancients# quest." },
			[33] = { str = "Then go do all this stuff in the water to the west:" },
			[34] = { str = "#DOOther Fish to Fry# " },
			[35] = { str = "#DOClam Bait# " },
			[36] = { str = "#DOBook of the Ancients# (27.6) ", x = 27, y = 6, zone = "Desolace" },
			[37] = { str = "#DOThe Corrupter# Part3 (collect a Oracle Crystal from a Slitherblade Oracle)" },
			[38] = { str = "#DOClaim Rackmore's Treasure!# " },
			[39] = { str = "Then turn in #INClaim Rackmore's Treasure!# at the little chest (29.8)", x = 29, y = 8, zone = "Desolace" },
			[40] = { str = "Turn in #INBook of the Ancients# #COORD[38,27]#", x = 38, y = 27, zone = "Desolace" },
			[41] = { str = "Then go accept #GETBone Collector#   #COORD[62,38]# (grinding mobs along the way)", x = 62, y = 38, zone = "Desolace" },
			[42] = { str = "Go to Ghost Walker Post #COORD[56,59]#, turn in #INCatch of the Day# accept and turn in #INThe Burning of Spirits# #INThe Corrupter# Part3 .. accept and then turn in #INThe Corrupter# Part4. Accept #GETAlliance Relations# Skip #NPCThe Corrupter# Part5.", x = 56, y = 59, zone = "Desolace" },
			[43] = { str = "Then go do:" },
			[44] = { str = "#DOBone Collector#, done at the kodo graveyard, #COORD[51,58]#", x = 51, y = 58, zone = "Desolace" },
			[45] = { str = "Then #DOCentaur Bounty# and #DOStealing Supplies# #COORD[70,74]#", x = 70, y = 74, zone = "Desolace" },
			[46] = { str = "Then go turn in #INCentaur Bounty# #COORD[56,59]#", x = 56, y = 59, zone = "Desolace" },
			[47] = { str = "Then turn in #INBone Collector# #COORD[62,38]#", x = 62, y = 38, zone = "Desolace" },
			[48] = { str = "Hearth to Shadowprey Village." },
			[49] = { str = "Turn in all quests there, which are: #INHand of Iruxos# #INOther Fish to Fry# and #INClam Bait# " },
			[50] = { str = "You should be level 34 now for sure." },
			[51] = { str = "Turn in #INStealing Supplies# #COORD[36,79]# and accept #GETOngeku# ", x = 36, y = 79, zone = "Desolace" },
			[52] = { str = "Fly to CT (In the Barrens). (the flight master is on the docks in Shadowprey Village)" },
			[53] = { str = "Once at CT, run south-east into Dustwallow Marsh (#COORD[51,79]# in the Barrens).", x = 51, y = 79, zone = "The Barrens" },
			[54] = { str = "Collect the 3 quest-objects at the Shady Rest Inn: " },
			[55] = { str = "#GETSuspicious Hoofprints# (just right outside in front of the inn)" },
			[56] = { str = "#GETLieutenant Paval Reethe# (laying on one of the planks on the ground)" },
			[57] = { str = "#GETThe Black Shield# (on top of the fireplace)" },
			[58] = { str = "Now run to Brackenwall Village #COORD[35,29]#", x = 35, y = 29, zone = "Dustwallow Marsh" },
			[59] = { str = "Turn those 3 quests in (#INSuspicious Hoofprints# #INLieutenant Paval Reethe# and #INThe Black Shield# ) ... accept and then turn in #INThe Black Shield# Part2.  Skip #NPCThe Black Shield# Part3 for now." },
			[60] = { str = "Stop at the troll vendor, buy the 3 first aid books." },
			[61] = { str = "Fly to Ratchet to turn in #INGoblin Sponsorship# & #INWharfmaster Dizzywig# ... accept #GETGoblin Sponsorship# Part2 and #GETParts for Kravel# " },
			[62] = { str = "Get on the boat to go to BB (Booty Bay) ... (while waiting for the boat, build up first aid)" },
			--[63] = { str = "." },
			--[64] = { str = "." },
		}
	},

-----------34-35 Stranglethorn Vale
	--[306] = {
	[3435] = {
		title = "34-35 Stranglethorn Vale",
		--n = "34-35 Stranglethorn Vale",
		--pID = 305, nID = 307,
		--itemCount = 37,
		items = {
			[1] = { str = "34-35 Stranglethorn Vale" },
			[2] = { str = "Turn in #INGoblin Sponsorship# Part2 .. accept #GETGoblin Sponsorship# Part3.  Make BB your home!  Accept #GETSinging Blue Shards# #GETBloodscalp Ears# #GETHostile Takeover# and #GETInvestigate the Camp# .  Turn in #INGoblin Sponsorship# Part3 at Baron Revilgaz ... accept #GETGoblin Sponsorship# Part4." },
			[3] = { str = "Then do the following:" },
			[4] = { str = "Fly to Grom'gol..." },
			[5] = { str = "Grab ALL quests in grom'gol:  #GETThe Defense of Grom'gol# #GETMok'thardin's Enchantment# #GETBloodscalp Insight# #GETHunt for Yenniku# #GETTrollbane# #GETBloody Bone Necklaces# #GETThe Vile Reef# " },
			[6] = { str = "'_^" },
			[7] = { str = "#VIDEOIMPORTANT:#  Make sure you save any Green Hills of Stranglethorn pages you find and mail them to your alt for storage, you will need them for a later #DOquest#.  You will need one of each of the following pages: 1, 4, 6, 8, 10, 11, 14, 16, 18, 20, 21, 24, 25, 26, and 27.  Once your alt collects all the pages, mail them back to your main.  Now go complete these quests:" },
			[8] = { str = "#DOSinging Blue Shards# #COORD[25,19]#", x = 25, y = 19, zone = "Stranglethorn Vale" },
			[9] = { str = "#DOTiger Mastery# (#NPCElder Stranglethorn Tigers#) #COORD[31,19]#", x = 31, y = 19, zone = "Stranglethorn Vale" },
			[10] = { str = "#DOBloodscalp Ears# and..." },
			[11] = { str = "#DOHunt for Yenniku# " },
			[12] = { str = "#DOBloody Bone Necklaces# (you don't have to finish all of this now)" },
			[13] = { str = "#DORaptor Mastery# (#NPCLashtail Raptors#)" },
			[14] = { str = "#DOThe Defense of Grom'gol# " },
			[15] = { str = "Once all those are done (besides #DOBloody Bone Necklaces# ), go to Grom'gol.." },
			[16] = { str = "Turn in #INHunt for Yenniku# ... accept #GETHeadhunting# " },
			[17] = { str = "Turn in #INThe Defense of Grom'gol# ... accept #GETThe Defense of Grom'gol# part2." },
			[18] = { str = "Should be lvl 35 now, either way buy lvl 35 food/water/repair (so that you are prepared for when you do turn level 35), then go do in the following order:" },
			[19] = { str = "#DOHeadhunting# along with finishing up #DOBloody Bone Necklaces# #COORD[21,14]#", x = 21, y = 14, zone = "Stranglethorn Vale" },
			[20] = { str = "#DOThe Vile Reef# along with #DOEncrusted Tail Fins# #COORD[24,24]# Use a breath potion if you can.", x = 24, y = 24, zone = "Stranglethorn Vale" },
			[21] = { str = "Then go to Nesingwary's Expedition #COORD[35,10]#... turn in ALL quests, accept all new ones (except #NPCThe Green Hills of Stranglethorn# ).  Then go do:", x = 35, y = 10, zone = "Stranglethorn Vale" },
			[22] = { str = "#DOTiger Mastery# (#NPCSin'Dall#), he is usually on top of the hill at #COORD[31,17]#.  Once that is done, go turn it in, then go do:", x = 31, y = 17, zone = "Stranglethorn Vale" },
			[23] = { str = "#DOHostile Takeover# along with #DOGoblin Sponsorship# #COORD[44,19]#", x = 44, y = 19, zone = "Stranglethorn Vale" },
			[24] = { str = "#DOPanther Mastery# along with #DOMok'thardin's Enchantment# (kill #NPCshadowmaw panthers#) #COORD[48,21]#", x = 48, y = 21, zone = "Stranglethorn Vale" },
			[25] = { str = "#DOThe Defense of Grom'gol# part2 #COORD[36,30]#, once that's done...", x = 36, y = 30, zone = "Stranglethorn Vale" },
			[26] = { str = "Head up north and turn in #INPanther Mastery# ...accept #GETPanther Mastery# (#NPCBhag'thera#) but don't do it now." },
			[27] = { str = "Hearth to BB, turn in #INSinging Blue Shards# #INHostile Takeover# #INBloodscalp Ears# #INInvestigate the Camp# " },
			[28] = { str = "Turn in #INGoblin Sponsorship# part4 ... accept #GETGoblin Sponsorship# part5." },
			[29] = { str = "Fly to Grom'gol, turn in all quests: #INThe Defense of Grom'gol# #INMok'thardin's Enchantment# #INHeadhunting# #INBloody Bone Necklaces# and #INThe Vile Reef# " },
			[30] = { str = "Should be level 36 now, if not, grind to it. Accept #GETTrollbane#." },
			[31] = { str = "Get on the zeppelin to go to the Undercity." },
			[32] = { str = "Once in the UC, turn in 60 Silk Cloth for #INA Donation of Silk# quest at #COORD[71,28]#.", x = 71, y = 28, zone = "Undercity" },
			[33] = { str = "Accept #GETTo Steal From Thieves# #COORD[63,49]#", x = 63, y = 49, zone = "Undercity" },
			[34] = { str = "Then fly to Hammerfall..." },
			--[35] = { str = "." },
			--[36] = { str = "." },
		}
	},

-----------35-37 Arathi Highlands
	--[307] = {
	[3537] = {
		title = "35-37 Arathi Highlands",
		--n = "35-37 Arathi Highlands",
		--pID = 306, nID = 308,
		--itemCount = 28,
		items = {
			[1] = { str = "35-37 Arathi Highlands" },
			[2] = { str = "Make Hammerfall your home." },
			[3] = { str = "Turn in #INTrollbane# ... I SKIP #NPCSigil of Strom# " },
			[4] = { str = "Accept #GETCall to Arms#, #GETFoul Magics# and #GETGuile of the Raptor# " },
			[5] = { str = "Grind your way down south and do: #DOCall to Arms# " },
			[6] = { str = "Then go west of hammerfall and accept #GETThe Princess Trapped# #COORD[62,33]#", x = 62, y = 33, zone = "Arathi Highlands" },
			[7] = { str = "Then go do #DOThe Princess Trapped# (mobs are east of hammerfall)" },
			[8] = { str = "Go in the cave (look for the tree, shows you where the hidden path is)..." },
			[9] = { str = "Then turn in #INThe Princess Trapped# (in the cave)... accept #GETStones of Binding# " },
			[10] = { str = "Then turn in #INCall to Arms# ... accept #GETCall to Arms# " },
			[11] = { str = "Build up first aid, go do #DOTriage#  (Doctor Gregory Victor, first aid training in Hammerfall)" },
			[12] = { str = "Then do:" },
			[13] = { str = "#DOStones of Binding# First key, just west of hammerfall #COORD[66,29]#", x = 66, y = 29, zone = "Arathi Highlands" },
			[14] = { str = "Then do: #DOTo Steal From Thieves# at #COORD[54,40]#", x = 54, y = 40, zone = "Arathi Highlands" },
			[15] = { str = "Go down south a little and get the next key for #DOStones of Binding# #COORD[52,50]#", x = 52, y = 50, zone = "Arathi Highlands" },
			[16] = { str = "Then go down and do:" },
			[17] = { str = "#DOCall to Arms# (killing ogres) and #DOGuile of the Raptor# (killing Highland Fleshstalkers) around #COORD[50,75]#", x = 50, y = 75, zone = "Arathi Highlands" },
			[18] = { str = "Then go up and do #DOFoul Magics# at #COORD[31,28]#", x = 31, y = 28, zone = "Arathi Highlands" },
			[19] = { str = "Then go west and get the last key for #DOStones of Binding# #COORD[25,31]#", x = 25, y = 31, zone = "Arathi Highlands" },
			[20] = { str = "Go discover Stromguard, and turn in #INStones of Binding# (at the Circle of Inner Binding) #COORD[36,57]#", x = 36, y = 57, zone = "Arathi Highlands" },
			[21] = { str = "Note: i SKIP #NPCBreaking the Keystone# (Elite)" },
			[22] = { str = "Hearth to Hammerfall." },
			[23] = { str = "Turn in #INFoul Magics# #INGuile of the Raptor# and #INCall to Arms# " },
			[24] = { str = "Complete the #DOGuile of the Raptor# quest chain by running back and forth..." },
			[25] = { str = "NOTE: i SKIP all stromguard quests (but I still recommend doing them if you can find groups)" },
			[26] = { str = "Fly to Tarren Mill..." },
			--[27] = { str = "." },
			--[28] = { str = "." },
		}
	},

-----------37-37 Alterac Mountains
	--[308] = {
	[3736] = {
		title = "37-37 Alterac Mountains",
		--n = "37-37 Alterac Mountains",
		--pID = 307, nID = 309,
		--itemCount = 16,
		items = {
			[1] = { str = "37-37 Alterac Mountains" },
			[2] = { str = "Once at TM, accept #GETStone Tokens# and #GETPrison Break In# " },
			[3] = { str = "Then go do them in Alterac Mountains (at Dalaran)" },
			[4] = { str = "Then turn them in and accept #GETDalaran Patrols# and #GETBracers of Binding# " },
			[5] = { str = "Then go do them in Alterac Mountains (at Dalaran)" },
			[6] = { str = "Once they are both completed, die on purpose, so u end up at TM" },
			[7] = { str = "Turn them in" },
			[8] = { str = "Then fly to the UC." },
			[9] = { str = "Once at UC, turn in #INTo Steal From Thieves# and buy 3x#NPCSoothing Spices" },
			[10] = { str = "Get on zeppelin to go to orgrimmar." },
			[11] = { str = "Once in Orgrimmar, turn in #INAlliance Relations# at #NPCKeldran#. at #COORD[21,53]#", x = 21, y = 53, zone = "Orgrimmar" },
			[12] = { str = "Then fly to XRs." },
			[13] = { str = "Make XRs your home." },
			[14] = { str = "Fly to Freewind Post (1k needles)..." },
			--[15] = { str = "." },
			--[16] = { str = "." },
		}
	},

-----------37-37 Thousand Needles
	--[309] = {
	[3737] = {
		title = "37-37 Thousand Needles",
		--n = "37-37 Thousand Needles",
		--pID = 308, nID = 310,
		--itemCount = 14,
		items = {
			[1] = { str = "37-37 Thousand Needles" },
			[2] = { str = "Run towards the Shimmering Flats.." },
			[3] = { str = "Turn in #INThe Swarm Grows# ... accept #GETThe Swarm Grows# part2 #COORD[67,63]#", x = 67, y = 63, zone = "Thousand Needles" },
			[4] = { str = "Stop at the goblins and turn in #INParts for Kravel# ... accept #GETDelivery to the Gnomes# ... turn in #INDelivery to the Gnomes# .  Turn in #INGoblin Sponsorship# part3 ... accept #GETThe Eighteenth Pilot# .  Turn in #INThe Eighteenth Pilot#   ... accept #GETRazzeric's Tweaking# .  Turn in #INEncrusted Tail Fins# " },
			[5] = { str = "Accept #GETThe Rumormonger# " },
			[6] = { str = "Do the following quests:" },
			[7] = { str = "#DOThe Swarm Grows# and #DOParts of the Swarm# (quest starts from an item drop) #COORD[71,85]#", x = 71, y = 85, zone = "Thousand Needles" },
			[8] = { str = "Then go turn in #INThe Swarm Grows# #COORD[67,63]#", x = 67, y = 63, zone = "Thousand Needles" },
			[9] = { str = "Hearth to XRs" },
			[10] = { str = "Turn in #INParts of the Swarm# ... accept #GETParts of the Swarm# part2" },
			[11] = { str = "Get new spells/abilities." },
			[12] = { str = "Fly to Dustwallow Marsh..." },
			--[13] = { str = "." },
			--[14] = { str = "." },
		}
	},

-----------37-38 Dustwallow Marsh
	--[310] = {
	[3738] = {
		title = "37-38 Dustwallow Marsh",
		--n = "37-38 Dustwallow Marsh",
		--pID = 309, nID = 311,
		--itemCount = 25,
		items = {
			[1] = { str = "37-38 Dustwallow Marsh" },
			[2] = { str = "Accept #GETTheramore Spies# and #GETThe Black Shield# " },
			[3] = { str = "Go slightly south of Brackenwall Village and accept #GETHungry!# from the ogre at #COORD[35,37]#", x = 35, y = 37, zone = "Dustwallow Marsh" },
			[4] = { str = "I turn this zone into a quest-grind area, ill move around killing anything in my path while focusing on these quests:" },
			[5] = { str = "#DOTheramore Spies#, #DOThe Black Shield# #DOHungry!#  I do #DOHungry!# at #COORD[58,23]#", x = 58, y = 23, zone = "Dustwallow Marsh" },
			[6] = { str = "I stop at Jarl's cabin #COORD[55,25]# and get #GETThe Lost Report# quest (the dirt mound next to his cabin)", x = 55, y = 25, zone = "Dustwallow Marsh" },
			[7] = { str = "And turn in #INSoothing Spices# ... accept #GETJarl Needs Eyes#" },
			[8] = { str = "Go south at #COORD[54,56]# to retrive the Seaforium Booster for Razzeric", x = 54, y = 56, zone = "Dustwallow Marsh" },
			[9] = { str = "Go do #DOJarl Needs Eyes# (while focusing on the others too)" },
			[10] = { str = "I do the escort quest #DOStinky's Escape# that starts at #COORD[47,18]# (grind mobs during this quest)", x = 47, y = 18, zone = "Dustwallow Marsh" },
			[11] = { str = "I'll stop at the big raptor spot at #COORD[47,17]#, and grind it clear several times." , x = 47, y = 17, zone = "Dustwallow Marsh" },
			[12] = { str = "Stop at Brackenwall Village and turn in all quests, accept new ones." },
			[13] = { str = "Turn in #INHungry!#" },
			[14] = { str = "Stop back at Jarl's cabin at #COORD[55,25]#, go to the dirt mound once again to get #NPCThe Severed Head#", x = 55, y = 25, zone = "Dustwallow Marsh" },
			[15] = { str = "Turn in #INJarl Needs Eyes# ... i SKIP #INJarl Needs a Blade#" },
			[16] = { str = "I grind some more at the raptors and such, at this point i should be a little over half way to 39." },
			[17] = { str = "I then go do this quest:" },
			[18] = { str = "#DOThe Theramore Docks# the Captain's Documents are under the water at #COORD[71,51]#" , x = 71, y = 51, zone = "Dustwallow Marsh" },
			[19] = { str = "I then die on purpose, so i end up right at Brackenwall Village." },
			[20] = { str = "Turn in #INThe Theramore Docks#" },
			[21] = { str = "Turn in #INThe Severed Head# ... accept #GETThe Troll Witchdoctor#" },
			--[BB] = { str = "CC) Kill Deadmire at XX.YY" , x = XX, y = YY, zone = "Dustwallow Marsh" },
			[22] = { str = "Hearth to XRs" },
			[23] = { str = "Fly to Ratchet, turn in #INStinky's Escape# while your there." },
			[24] = { str = "Get on the boat to go to BB..." },
			--[25] = { str = "." },
			--[26] = { str = "." },
		}
	},

-----------38-40 Stranglethorn Vale
	--[311] = {
	[3840] = {
		title = "38-40 Stranglethorn Vale",
		--n = "38-40 Stranglethorn Vale",
		--pID = 310, nID = 401,
		--itemCount = 34,
		items = {
			[1] = { str = "38-40 Stranglethorn Vale" },
			[2] = { str = "Accept #GETThe Bloodsail Buccaneers#, #GETVenture Company Mining# and #GETScaring Shaky# " },
			[3] = { str = "Make BB your home, then go up the steps and turn in #INThe Rumormonger# " },
			[4] = { str = "Fly to Grom'gol." },
			[5] = { str = "Accept #GETMok'thardin's Enchantment# " },
			[6] = { str = "Turn in #INThe Troll Witchdoctor# ... right click the cauldron ... accept #GETMarg Speaks# " },
			[7] = { str = "Go do:" },
			[8] = { str = "#DORaptor Mastery# along with #DOMok'thardin's Enchantment# #COORD[31,41]#  (Kill #NPCJungle Stalkers#)", x = 31, y = 41, zone = "Stranglethorn Vale" },
			[9] = { str = "Grind away at raptors/cold eye ballisks till level 39, then do:" },
			[10] = { str = "#DOVenture Company Mining# at #COORD[40,42]#", x = 40, y = 42, zone = "Stranglethorn Vale" },
			[11] = { str = "Once that is done, go back to Grom'Gol and turn in #INMok'thardin's Enchantment# ... accept #GETMok'thardin's Enchantment# part3." },
			[12] = { str = "Then do #DOPanther Mastery# (#NPCBhag'thera#) (he has 3 different spawn points, either at #COORD[48,20]#, #COORD[49,23]#, or #COORD[47,26]#)", x = 48, y = 20, zone = "Stranglethorn Vale" },
			[13] = { str = "Then turn in #INPanther Mastery# (#NPCBhag'thera#) and #INRaptor Mastery# (#NPCJungle Stalkers#) at Nesingwary's Expedition #COORD[35,10]#", x = 35, y = 10, zone = "Stranglethorn Vale" },
			[14] = { str = "Accept #GETRaptor Mastery# (#NPCTethis#) but don't do it now." },
			[15] = { str = "Hearth to BB." },
			[16] = { str = "Turn in #INVenture Company Mining# " },
			[17] = { str = "Then go do:" },
			[18] = { str = "#DOThe Bloodsail Buccaneers# (just slightly north-west of BB at #COORD[27,69]#, there's a little note on a barrel, click on it, accept new quest). ", x = 27, y = 69, zone = "Stranglethorn Vale" },
			[19] = { str = "#DOScaring Shaky# along with #DOMok'thardin's Enchantment# part3 #COORD[32,66]#", x = 32, y = 66, zone = "Stranglethorn Vale" },
			[20] = { str = "Once that's done run back into BB." },
			[21] = { str = "Turn in #INScaring Shaky# ... accept #GETReturn to MacKinley# " },
			[22] = { str = "Turn in #INThe Bloodsail Buccaneers# ... accept #GETThe Bloodsail Buccaneers# " },
			[23] = { str = "Turn in #INReturn to MacKinley# " },
			[24] = { str = "Then turn in #INThe Bloodsail Buccaneers# at Fleet Master Seahorn." },
			[25] = { str = "Fly to Grom'gol." },
			[26] = { str = "Turn in #INMok'thardin's Enchantment# part3  ... accept #GETMok'thardin's Enchantment# part4" },
			[27] = { str = "You should be level 40 for sure now. If not grind the rest of the way to 40 on raptors/cold eye basilisks." },
			[28] = { str = "OPTIONAL: Scarlet Monastery instance instead of the grinding." },
			[29] = { str = "Then get on the zeppelin to go to the UC." },
			[30] = { str = "Fly to Hammerfall and stop at the inn to get the #NPCFrost Oil#, the #NPCGyrochronatom#, the #NPCHealing Potion#, the #NPCLesser Invisibility Potion# and the #NPCPatterned Bronze Bracers# items for some free XP in Badlands." },
			[31] = { str = "Run all the way to the Badlands..." },
			--[33] = { str = "." },
			--[34] = { str = "." },
		}
	},
}
