--[[--------------------------------------------------
   003_Horde_50to60.lua
   Authors: mrmr, lanjelin
   Version: 1.04.3
   ------------------------------------------------------
   Description: Guide Serie - 003 From Lvl 50 to Lvl 60
   1.04.1
   -- First Release
   Horde's Guide
   from level 50 to lever 60
   1.04.2
   -- no changes in here for this revision
   1.04.3
   -- Cleanup in text, changed formatting of coords
   ------------------------------------------------------
   Connection:
--]]--------------------------------------------------

Table_003_Horde_50to60 = {
   -----------50-50 Azshara
   --[501] = {
   [5049] = {
      title = "50-50 Azshara",
      n = "50-50 Azshara",
      pID = 414, nID = 502,
      itemCount = 23,
      items = {
         [1] = { str = "50-50 #ZONEID16#" },
         [2] = { str = "Accept: #GETID3517# " },
         [3] = { str = "Go do:" },
         [4] = { str = "#DOID3517# Done at the Ruins of Eldarath, #COORD[36,54]#", x = 36, y = 54, zone = "Azshara" },
         [5] = { str = "#DOID3568# Tide Pools are at: 1=#COORD[47,61]#, 2=#COORD[47,51]#, 3=#COORD[48,48]#, 4=#COORD[47,46]#", x = 47, y = 61, zone = "Azshara" },
         [6] = { str = "Once their done, turn in #INID3517# ..accept ALL 4 delivery quests." },
         [7] = { str = "Turn in #INID3561#, there is a teleporter at #COORD[28,50]#,#VIDEOSee Video# ... accept #GETID3565# ", x = 28, y = 50, zone = "Azshara" },
         [8] = { str = "Then fly to Thunder Bluff.." },
         [9] = { str = "Turn in #INID3518# (on Elder Rise) ... accept #GETID3562# " },
         [10] = { str = "Hearth to Orgrimmar." },
         [11] = { str = "Go turn in #INID32# ... accept #GETID4493# at #COORD[56,46]#", x = 56, y = 46, zone = "Azshara" },
         [12] = { str = "Turn in #INID3541# at #COORD[55,34]# ... accept #GETID3563# and #GETID4300# ", x = 55, y = 34, zone = "Azshara" },
         [13] = { str = "Then turn in #INID81# at #COORD[59,36]#  (If you did the Hinterlands section)", x = 59, y = 36, zone = "Azshara" },
         --L- Remove Ripple Delivery as the quest cannot be accepet at given level
         [14] = { str = "Then go to The Undercity, head to the Apothecarium Quarter..." },
         [15] = { str = "Turn in #INID3542# ... accept #GETID3564# " },
         [16] = { str = "Then turn in #INID3568# and #INID864# ... accept #GETID4133# while you are there." },
         [17] = { str = "Then accept #GETID3568# ... then turn it in (at the tauren right next to him) ..." },
         [18] = { str = "... Then complete #INID3568# for the final time." },
         [19] = { str = "Then accept #GETID4293# and #GETID4294# " },
         [20] = { str = "Then fly to Raventusj Village..." },
         --[22] = { str = "." },
         --[23] = { str = "." },
      }
   },

   -----------50-50 Hinterlands
   --[502] = {
   [5050] = {
      title = "50-50 Hinterlands",
      --n = "50-50 Hinterlands",
      --pID = 501, nID = 503,
      --itemCount = 20,
      items = {
         [1] = { str = "50-50 #ZONEID47#" },
         [2] = { str = "Accept: #GETID7815# #GETID7816# (Elite) and #GETID7840# " },
         [3] = { str = "Go do in the following order:" },
         [4] = { str = "#DOID7815# along with #DOID7816# and #DOID580# " },
         [5] = { str = "#DOID624# at #COORD[80,46]#, little chest in the water, 14 slot bag along with 8800 XP", x = 80, y = 46, zone = "The Hinterlands" },
         [6] = { str = "#DOID7840# at #COORD[84,42]#", x = 84, y = 42, zone = "The Hinterlands" },
         [7] = { str = "Then go turn in #INID7815# #INID7816# and #INID7840# " },
         [8] = { str = "Then go do #DOID2641# at #COORD[41,60]#", x = 41, y = 60, zone = "The Hinterlands" },
         [9] = { str = "Then hearth to Orgrimmar." },
         [10] = { str = "Fly to Azshara." },
         [11] = { str = "Turn in all 4 delivery quests." },
         [12] = { str = "Fly to XRs." },
         [13] = { str = "Make XRs your home." },
         [14] = { str = "Fly to Ratchet." },
         [15] = { str = "Pick up the #ITEMID10556# at Liv Rizzlefix shop ... also accept #GETID4502# while your there." },
         [16] = { str = "Get on the boat to go to BB" },
         [17] = { str = "Fly to Stonard (swamp of sorrows).." },
         [18] = { str = "Go into Blasted Lands..." },
         --[19] = { str = "." },
         --[20] = { str = "." },
      }
   },

   ------------50-51 Blasted Lands
   --[503] = {
   [5051] = {
      title = "50-51 Blasted Lands",
      --n = "50-51 Blasted Lands",
      --pID = 502, nID = 504,
      --itemCount = 27,
      items = {
         [1] = { str = "50-51 #ZONEID4#" },
         [2] = { str = "I then find all the items to complete these 5 quests:" },
         [3] = { str = "#DOID2583# " },
         [4] = { str = "#DOID2581# " },
         [5] = { str = "#DOID2601# " },
         [6] = { str = "#DOID2585# " },
         [7] = { str = "#DOID2603# " },
         [8] = { str = "You need to find these many items to complete these quests:" },
         [9] = { str = "#ITEMID8396# x14" },
         [10] = { str = "#ITEMID8394# x11" },
         [11] = { str = "#ITEMID8392# x6" },
         [12] = { str = "#ITEMID8393# x6" },
         [13] = { str = "#ITEMID8391# x5" },
         [14] = { str = "While I'm in Blasted Lands, I discover most of all the areas for XP." },
         [15] = { str = "If an #ITEMID10593# drops turn in for this quest: #INID3501# " },
         [16] = { str = "NOTE: I have NEVER found a #NPCID7364# for the quest #INID2521# ..good luck on that." },
         [17] = { str = "Turn in all quests." },
         [18] = { str = "I turn in #INID2585# in last for Ground Scorpok Assay (+50 to agility)" },
         [19] = { str = "Then hearth to XRs." },
         [20] = { str = "Fly to Tanaris (GET A MITHRIL CASING for a later quest in Un'Goro!!!)" },
         [21] = { str = "Turn in #INID2641# ... accept #GETID2661# " },
         [22] = { str = "Turn in #INID4493# ... accept #GETID4496# " },
         [23] = { str = "Turn in #INID2661# ...accept #GETID2662# then turn it in." },
         [24] = { str = "Go turn in #INID3444# at #COORD[52,46]# in Tanaris", x = 52, y = 46, zone = "Tanaris" },
         [25] = { str = "Then go into Un'Goro Crater..." },
         --[26] = { str = "." },
         --[27] = { str = "." },
      }
   },

   -----------51-52 Un'Goro Crater
   --[504] = {
   [5152] = {
      title = "51-52 Un'Goro Crater",
      --n = "51-52 Un'Goro Crater",
      --pID = 503, nID = 505,
      --itemCount = 56,
      items = {
         [1] = { str = "51-52 #ZONEID490#" },
         [2] = { str = "Go accept: #GETID4289# and #GETID4290# at #COORD[71,75]#", x = 71, y = 75, zone = "Un'Goro Crater" },
         [3] = { str = "Go do #DOID4290# at #COORD[68,56]#", x = 68, y = 56, zone = "Un'Goro Crater" },
         [4] = { str = "Then go start doing: #DOID4504# (up north in the middle) until this item drops #ITEMID11116#" },
         [5] = { str = "Then go into Marshal's Refuge #COORD[43,10]#, accept ALL quests there:  #GETID4243# #GETID4503# #GETID4492# #GETID4501# #GETID3882# #GETID3883# #GETID3881# #GETID4145# ", x = 43, y = 10, zone = "Un'Goro Crater" },
         [6] = { str = "Turn in #INID3884# " },
         [7] = { str = "Get FP there, then go do the Ungoro Grind :) ..." },
         [8] = { str = "NOTE: don't worry about the ungoro dirt mounds, you'll find enough soil from mob drops.  Also I don't worry about the Bloodpetal Sprouts, as they are not turned in for any XP." },
         [9] = { str = "While questing, find 7 crystals of each color (red, blue, green, and yellow for the #DOID4284# quest)" },
         [10] = { str = "#DOID4504# " },
         [11] = { str = "#DOID4289# along with #DOID4243# (if you have a #ITEMID10561# do the escort) #COORD[63,17]#", x = 63, y = 17, zone = "Un'Goro Crater" },
         [12] = { str = "#DOID4145# " },
         [13] = { str = "#DOID4501# along with #DOID4503# and.." },
         [14] = { str = "#DOID3882# " },
         [15] = { str = "#DOID3881# #COORD[68,36]# and #COORD[38,65]#", x = 68, y = 36, zone = "Un'Goro Crater" },
         [16] = { str = "#DOID4294# (I make sure I get at least 30 ooze samples)" },
         [17] = { str = "Go turn in #INID4289# ... accept #GETID4301# " },
         [18] = { str = "Turn in #INID4290# ... accept #GETID4291# " },
         [19] = { str = "Then go do:" },
         [20] = { str = "#DOID4300# along with #DOID4291# " },
         [21] = { str = "#GETID3844# ... click on boat and then bag under water at #COORD[63,68]#", x = 63, y = 68, zone = "Un'Goro Crater" },
         [22] = { str = "Then turn in #INID4291# ... accept #GETID4292# #COORD[71,75]#", x = 71, y = 75, zone = "Un'Goro Crater" },
         [23] = { str = "Then go do #DOID3883# along with #DOID4496# #COORD[50,80]#", x = 50, y = 80, zone = "Un'Goro Crater" },
         [24] = { str = "Go accept #GETID974# at #COORD[30,50]#, then do it along with #DOID4502# ", x = 30, y = 50, zone = "Un'Goro Crater" },
         [25] = { str = "The hotspot path for the quest #DOID974# starts at #COORD[51,42]# and the hot spot is at #COORD[50,46]#  (#VIDEOSee Video on where to find the hotspot#)", x = 51, y = 42, zone = "Un'Goro Crater" },
         [26] = { str = "#DOID4492# Make sure all quests are done before doing this (besides #INID4301# and #INID4292# ), then..." },
         [27] = { str = "...This leads back to Marshal's Refuge, Turn in ALL quests there, accept new ones (including all the Pylon quests in the cave)." },
         [28] = { str = "Then go do (in the following order):" },
         [29] = { str = "#DOID4285# at #COORD[56,13]#", x = 56, y = 13, zone = "Un'Goro Crater" },
         [30] = { str = "#DOID4301# cave at #COORD[63,13]#", x = 63, y = 13, zone = "Un'Goro Crater" },
         [31] = { str = "#DOID4287# at #COORD[77,50]#", x = 77, y = 50, zone = "Un'Goro Crater" },
         [32] = { str = "#DOID4292# #COORD[80,50]#.  Then turn it in along with #INID4301# #COORD[71,75]#", x = 71, y = 75, zone = "Un'Goro Crater" },
         [33] = { str = "Go west killing oozes along the way.." },
         [34] = { str = "Turn in #INID974# ... accept #GETID980# #COORD[30,50]#", x = 30, y = 50, zone = "Un'Goro Crater" },
         [35] = { str = "#DOID4288# at #COORD[23,58]#", x = 23, y = 58, zone = "Un'Goro Crater" },
         [36] = { str = "Go back to Marshal's Refuge killing oozes along the way.." },
         [37] = { str = "Turn in quests. make sure you complete #DOID4321# (just talk to the gnome in the cave)" },
         [38] = { str = "Fly to Tanaris." },
         [39] = { str = "Turn in #INID4504# and #INID4496# ... I SKIP #SKIPID4507# " },
         [40] = { str = "Then fly to Thunder Bluff." },
         [41] = { str = "Go to Elder Rise." },
         [42] = { str = "Accept #GETID3761# .. then turn it in ... accept #GETID3781# .. then turn that in..." },
         [43] = { str = "...but SKIP the next part (the part that says bring 10 Morrowgrain)" },
         [44] = { str = "Go get new spells/abilities." },
         [45] = { str = "Hearth to XRs." },
         [46] = { str = "Then fly to Ratchet.." },
         [47] = { str = "Turn in #INID4502# and #INID4147# - I SKIP #SKIPID4146# " },
         [48] = { str = "Get on the boat to go to BB.." },
         [49] = { str = "Turn in #INID580# " },
         [50] = { str = "Also turn in #INID648# (if you did it)" },
         [51] = { str = "Fly to Kargath (Badlands).." },
         [52] = { str = "Turn in #INID4133# " },
         [53] = { str = "Accept: #GETID3821# and #GETID4061# " },
         [54] = { str = "Then fly to Burning Steppes..." },
         --[55] = { str = "." },
         --[56] = { str = "." },
      }
   },

   -----------52-53 Burning Steppes
   --[505] = {
   [5253] = {
      title = "52-53 Burning Steppes",
      --n = "52-53 Burning Steppes",
      --pID = 504, nID = 506,
      --itemCount = 18,
      items = {
         [1] = { str = "52-53 #ZONEID46#" },
         [2] = { str = "Accept: #GETID4726# and #GETID4296# " },
         [3] = { str = "Then go do:" },
         [4] = { str = "#DOID4726# (to the east) (also kill as many dragon whelps you see, their squishy mobs that die real fast)" },
         [5] = { str = "#DOID3821# #COORD[79,45]#... then #DOID3822# (Krom'Grul has 2 different spawn points, in either cave)", x = 79, y = 45, zone = "Burning Steppes" },
         [6] = { str = "#DOID4061# " },
         [7] = { str = "#DOID4296# it's at #COORD[54,40]#", x = 54, y = 40, zone = "Burning Steppes" },
         [8] = { str = "Go turn in #INID4296# and #INID4726# ... accept #GETID4808# " },
         [9] = { str = "Then fly to Kargath (Badlands)" },
         [10] = { str = "Turn in #INID3822# " },
         [11] = { str = "Turn in #INID4061# ... accept #GETID4061# part2" },
         [12] = { str = "Go turn in #INID4061# part2 at #COORD[25,46]# in Badlands", x = 25, y = 46, zone = "Badlands" },
         [13] = { str = "Then hearth to XRs." },
         [14] = { str = "Then fly to Orgrimmar and make it your home." },
         [15] = { str = "Go turn in #INID4300# #COORD[55,34]#", x = 55, y = 34, zone = "Orgrimmar" },
         [16] = { str = "Fly Azshara..." },
         --[17] = { str = "." },
         --[18] = { str = "." },
      }
   },

   --------------53-54 Azshara
   --[506] = {
   [5354] = {
      title = "53-54 Azshara",
      --n = "53-54 Azshara",
      --pID = 505, nID = 507,
      --itemCount = 28,
      items = {
         [1] = { str = "53-54 #ZONEID16#" },
         [2] = { str = "Accept #GETID3504# " },
         [3] = { str = "Go turn in #INID8151#, this is a hunter only quest, at #COORD[41,42]# ... accept #GETID8153# " },
         [4] = { str = "Go accept #GETID3601# at #COORD[52,22]# on top of the hill", x = 52, y = 22, zone = "Azshara" },
         [5] = { str = "Then go do:" },
         [6] = { str = "#DOID8153# " },
         [7] = { str = "#DOID3504# " },
         [8] = { str = "#DOID3601# " },
         [9] = { str = "NOTE: I grind away at bloodelfs for a while doing those 2 quests." },
         [10] = { str = "Once those 3 quests are done, go turn in #INID3601# ... accept #GET5534# " },
         [11] = { str = "Turn in #INID8153# ... accept #GETID8231# " },
         [12] = { str = "Then go do:" },
         [13] = { str = "#DOID5534# " },
         [14] = { str = "#DOID8231# " },
         [15] = { str = "Once both are done, Hearth to Orgrimmar." },
         [16] = { str = "Then Fly to Azshara.." },
         [17] = { str = "Turn in #INID3504# ... accept #GETID3504# " },
         [18] = { str = "Turn in #INID8231# ... i SKIP #SKIPID8232# " },
         [19] = { str = "Turn in #IN5534# " },
         [20] = { str = "At this point im usually about 3/4th the way to lvl 54, I grind my way to level 54 on BloodElfs." },
         [21] = { str = "I grind bloodelfs, cause their squishy mobs (mobs that have 30% fewer health/armor, than the average mob that level).  I used to grind satyrs on previous speed runs, but I was able to cut off almost a whole hour with the blood elfs." },
         [22] = { str = "OPTIONAL: Instead of the grinding you could go do BRD instance instead." },
         [23] = { str = "Once i hit 54 (or a few bars past it), i then hearth to Orgrimmar." },
         [24] = { str = "I then go turn in #INID4300# and #INID3504# " },
         [25] = { str = "Then fly to Splintertree Post (Ashenvale).." },
         [26] = { str = "Then go into Felwood..." },
         --[27] = { str = "." },
         --[28] = { str = "." },
      }
   },

   -----------54-54 Felwood
   --[507] = {
   [5454] = {
      title = "54-54 Felwood",
      --n = "54-54 Felwood",
      --pID = 506, nID = 508,
      --itemCount = 16,
      items = {
         [1] = { str = "54-54 #ZONEID361#" },
         [2] = { str = "Accept #GETTimbermaw Ally# at #COORD[50,85]# (??? TBC Quest?) Just talk to the NPC there he will give it to you.", x = 50, y = 85, zone = "Felwood" },
         [3] = { str = "Go accept #GETID5155# and #GETID5156# at the Emerald Sanctuary #COORD[51,82]#.", x = 51, y = 82, zone = "Felwood" },
         [4] = { str = "Go accept #GETID4101# at #COORD[46,84]#", x = 46, y = 84, zone = "Felwood" },
         [5] = { str = "I start killing oozes, I make sure I kill about 30/40 oozes here total for the quest #DOID4293# #COORD[40,68]#", x = 40, y = 68, zone = "Felwood" },
         [6] = { str = "Then go complete #DOID5155# #COORD[38,60]#", x = 38, y = 60, zone = "Felwood" },
         [7] = { str = "Then go to BloodVenom Post. #COORD[34,52]#", x = 34, y = 52, zone = "Felwood" },
         [8] = { str = "Accept: #GETID6162# and #GETID4521# " },
         [9] = { str = "Get FP there." },
         [10] = { str = "Then go do in the following order:" },
         [11] = { str = "#DOID5156# (Elite) #COORD[41,41]#", x = 41, y = 41, zone = "Felwood" },
         [12] = { str = "#DOID4101# #COORD[54,16]#", x = 54, y = 16, zone = "Felwood" },
         [13] = { str = "Go accept #GETDeadwood of the North# (at 64.8) but DON'T do it now.", x = 64, y = 8, zone = "Felwood" },
         [14] = { str = "Grind your way through the cave to go to Winterspring..." },
         --[15] = { str = "." },
         --[16] = { str = "." },
      }
   },

   -----------54-55 Winterspring
   --[508] = {
   [5455] = {
      title = "54-55 Winterspring",
      --n = "54-55 Winterspring",
      --pID = 507, nID = 509,
      --itemCount = 31,
      items = {
         [1] = { str = "54-55 #ZONEID618#" },
         [2] = { str = "Exit the cave and accept #GETWinterfall Activity# right outside of it." },
         [3] = { str = "Go to Donova Snowden at #COORD[31,45]#", x = 31, y = 45, zone = "Winterspring" },
         [4] = { str = "Turn in #INID980# and #INID3844# and accept #GETID4842#" },
         [5] = { str = "NOTE: I SKIP #SKIPID3909# and the rest of that chain." },
         [6] = { str = "Go to Everlook.. #COORD[61,38]#", x = 61, y = 38, zone = "Winterspring" },
         [7] = { str = "Accept: #GETID977# #GETID6028# #GETID6030# #GETID5601# #GETID6603#and #GETID5054#" },
         [8] = { str = "Turn in #INID4808# ... accept #GETID4809# " },
         [9] = { str = "Make Everlook your home." },
         [10] = { str = "Go do #DOID5054#   (just keep grinding mobs on the hill north of everlook till #NPCID10806# shows up)" },
         [11] = { str = "Then turn in #INID5054# ... accept #GETID5055# " },
         [12] = { str = "Go do #DOID5055# he patrols around #COORD[60,60]#", x = 60, y = 60, zone = "Winterspring" },
         [13] = { str = "Then go Discover Darkwhisper Gorge at #COORD[59,73]# for the quest #DOID4842# ", x = 59, y = 73, zone = "Winterspring" },
         [14] = { str = "Then hearth back to Everlook." },
         [15] = { str = "Turn in #INID5055# ... SKIP #NPCID10737# " },
         [16] = { str = "Then go do the following quests (steps 17-20, in any order) to the west and some to the north. When you're at west remember to turn-in #INID6603# and accept #GETID5082#:" },
         [17] = { str = "#DOID977# " },
         [18] = { str = "#DOID5082# you should find #ITEMID12771# which starts #GETID5083# while doing this quest.  When the #ITEMID20742# item drops, save it and put it in your bank you will need it later." },
         [19] = { str = "#DOID4521# (the Ragged Owls are west of Everlook, and the Raging Owls are just north of Everlook)" },
         [20] = { str = "#DOID4809#, you can find a larger concentration of chimaera around #COORD[66,29]#", x = 66, y = 29, zone = "Winterspring" },
         [21] = { str = "Once #DOID5082# and #DOID5083# is completed go turn them in along with #INID4842# at #COORD[31,45]#... accept #GETID5084# ", x = 31, y = 45, zone = "Winterspring" },
         [22] = { str = "Once the rest of those quests are complete, go back to Everlook and turn in #INID977# ...accept #GETID977# part2.  Turn in #INID4809# ... i SKIP #SKIPID4810# " },
         [23] = { str = "Then go do:" },
         [24] = { str = "#DOWinterfall Activity# #COORD[67,37]#", x = 67, y = 37, zone = "Winterspring" },
         [25] = { str = "#DOID977# (find 2 Pristine Yeti Horns) #COORD[66,43]#", x = 66, y = 43, zone = "Winterspring" },
         [26] = { str = "Then hearth to Everlook and accept #GETID6605#" },
         [27] = { str = "Go turn in #INID977# ... accept #GETID977# part3" },
         [28] = { str = "Go scare Legacki with the mechanical yeti for the quest #DOID977# part3" },
         [29] = { str = "Then fly to Felwood..." },
         --[30] = { str = "." },
         --[31] = { str = "." },
      }
   },

   -----------55-55 Felwood
   --[509] = {
   [5554] = {
      title = "55-55 Felwood",
      --n = "55-55 Felwood",
      --pID = 508, nID = 510,
      --itemCount = 31,
      items = {
         [1] = { str = "55-55 #ZONEID361#" },
         [2] = { str = "Turn in #INID4521# ... Accept #GETID4521# part2 and #GETID4505#" },
         [3] = { str = "Go turn in #INID4101# ... then get a cenarion beacon for the quest #DO4103# (just talk to the NPC to get it) #COORD[46,83]#", x = 46, y = 83, zone = "Felwood" },
         [4] = { str = "Go turn in #INID5156# and #INID5155# ... accept #GETID5157# #COORD[51,82]#", x = 51, y = 82, zone = "Felwood" },
         [5] = { str = "Go do in the following order:" },
         [6] = { str = "Go do #DOID6162# along with #DOTimbermaw Ally# #COORD[48,94]#", x = 48, y = 94, zone = "Felwood" },
         [7] = { str = "Once they are done go turn in #INTimbermaw Ally# at #COORD[50,85]# ... accept #GETID8462#", x = 50, y = 85, zone = "Winterspring" },
         [8] = { str = "Go do #DOID4505# at #COORD[32,66]#.  Also make sure you collect 6 #ITEMID11515# for the quest #DO4103# ", x = 32, y = 66, zone = "Felwood" },
         [9] = { str = "#DOID5157# #COORD[35,59]#", x = 35, y = 59, zone = "Felwood" },
         [10] = { str = "Then go to Bloodvenom Post" },
         [11] = { str = "Turn in #INID6162# and #INID4505# ... accept #GETID4506# " },
         [12] = { str = "Go turn in #IN5882# (the 6 Corrupted Soul Shards) #COORD[46,83]#", x = 46, y = 83, zone = "Felwood" },
         [13] = { str = "Go turn in #INID5157# ... I SKIP #SKIPID5158# #COORD[51,82]# ", x = 51, y = 82, zone = "Felwood" },
         [14] = { str = "Go do #DOID4506# #COORD[32,66]# then go turn it in.  (NOTE: when you turn it in, you have to talk to the cat first once you get to the NPC)", x = 32, y = 66, zone = "Felwood" },
         [15] = { str = "Then go up north and do:" },
         [16] = { str = "#DOIDDeadwood of the North# (61.9)  When the Deadwood Ritual Totem item drops, save it and put it in your bank when you get a chance, you will need it later.", x = 61, y = 9, zone = "Felwood" },
         [17] = { str = "#DOID5084# (the cauldron at 60.5) (hint: I have my pet distract the mobs, while doing this quest)   ... then accept #GETID5085# ", x = 60, y = 5, zone = "Felwood" },
         [18] = { str = "Go turn in #INIDDeadwood of the North# (64.8) ... accept #GETID8465# .  And turn in #INID8462# ", x = 64, y = 8, zone = "Felwood" },
         [19] = { str = "Then run through the cave (you should be Unfriendly with Timbermaw, so they shouldn't attack you).." },
         [20] = { str = "Turn in #INWinterfall Activity# and #INID8465# " },
         [21] = { str = "Then go turn in #INID5085# at #COORD[31,45]# in Winterspring ... SKIP #SKIPID5086# ", x = 31, y = 45, zone = "Winterspring" },
         [22] = { str = "Then hearth to Everlook." },
         [23] = { str = "Fly to Orgrimmar and make it your home." },
         [24] = { str = "If you happen to see #NPCID10880#, accept #GETID5066# " },
         [25] = { str = "Fly to Thunder Bluff, then directly to Camp Mojache, Ferelas" },
         [26] = { str = "Turn in #INID4120# " },
         [27] = { str = "Then fly to Tanaris..." },
         [28] = { str = "Go scare #NPCID7583# with the mechanical yeti for the quest #DOID977# part3" },
         [29] = { str = "Then fly to Silithus" },
         --[30] = { str = "." },
         --[31] = { str = "." },
      }
   },

   ------------55-55 Silithus
   --[510] = {
   [5555] = {
      title = "55-55 Silithus",
      --n = "55-55 Silithus",
      --pID = 509, nID = 511,
      --itemCount = 25,
      items = {
         [1] = { str = "55-55 #ZONEID1377#" },
         [2] = { str = "Accept: #GETID8284# #GETID8280# and #GETID8277# " },
         [3] = { str = "Go do: #DOID8280# and #DOID8277# (do these 2 quests northeast of Cenarion Hold)" },
         [4] = { str = "Then turn them in and accept new quests." },
         [5] = { str = "Then go do:" },
         [6] = { str = "#DOID8281# " },
         [7] = { str = "#DOID8284# " },
         [8] = { str = "#DOID8278# " },
         [9] = { str = "Once all three of those are done, go turn them in accept new ones." },
         [10] = { str = "Go do:" },
         [11] = { str = "#DOID8282#, it's at around #COORD[40,90]#", x = 40, y = 90, zone = "Silithus" },
         [12] = { str = "NOTE: I skip #SKIPID8283# (Elite) cause it's too hard to solo at 55, but do it if you can find a group." },
         [13] = { str = "#DOID1286# He's in the cave at #COORD[67,71]# ... i SKIP #SKIPID8279# ", x = 67, y = 71, zone = "Silithus" },
         [14] = { str = "Then i die on purpose, so i end up at Cenarion Hold." },
         [15] = { str = "Turn in #INID8282# " },
         [16] = { str = "Then go to Marshal's Refuge in Un'Goro Crater." },
         [17] = { str = "Go scare Quixxil with the mechanical yeti for the quest #DOID977# part3" },
         [18] = { str = "Then hearth to Orgrimmar." },
         [19] = { str = "Go to the Under City." },
         [20] = { str = "Go complete #INID4293# and #INID4294# " },
         [21] = { str = "Go accept #GETID5066# " },
         [22] = { str = "Make Under City your home." },
         [23] = { str = "Go to the Bulwark... (which is a small village east of Tirisfal Glades)" },
         --[24] = { str = "." },
         --[25] = { str = "." },
      }
   },

   -----------55-56 Western Plaguelands
   --[511] = {
   [5556] = {
      title = "55-56 Western Plaguelands",
      --n = "55-56 Western Plaguelands",
      --pID = 510, nID = 512,
      --itemCount = 24,
      items = {
         [1] = { str = "55-56 #ZONEID28#" },
         [2] = { str = "Turn in #INID5066# accept #GETID5096# ..." },
         [3] = { str = "... (make sure you get a Flame in a Bottle first, before doing this quest, it's in the box)" },
         [4] = { str = "Turn in #INID6028# " },
         [5] = { str = "Accept and complete #DOID5401# " },
         [6] = { str = "Accept #GETID5901# " },
         [7] = { str = "Go into the Western Plaguelands, Felstone field at #COORD[37,56]# and...", x = 37, y = 56, zone = "Western Plaguelands" },
         [8] = { str = "Accept #GETID5021# (the lady in the house)" },
         [9] = { str = "Then go to the barn next door, and..." },
         [10] = { str = "Complete #DOID5021# .. click on the chest again to accept #GETID5021# again." },
         [11] = { str = "Go do #DOID5096#, burn the tent down, and plant the banner #COORD[40,51]#  ", x = 40, y = 51, zone = "Western Plaguelands" },
         [12] = { str = "Go back to the Bulwark..  (#VIDEONOTE:# Make sure you save all #ITEMID22526# you find, you will need 30 of them for a later #DOquest#)" },
         [13] = { str = "Turn in #INID5096# ... accept #GETID5097# (Elite) and #GETID5215# " },
         [14] = { str = "Turn in #INID5215# ... accept #GETID5216# " },
         [15] = { str = "Go complete the whole Cauldron quest chain, you need to kill the Cauldron Lord at each targeted field (listed below), grab their key and use it at the big cauldron in the middle of the field.  (Just keep going back and forth from The Bulwark to the next field completing each one, turning them in and then accepting and doing the next one)..." },
         [16] = { str = "#DOID5216# #COORD[37,56]#", x = 37, y = 56, zone = "Western Plaguelands" },
         [17] = { str = "#DOID5219# #COORD[46,52]#.  #VIDEONOTE:#  While you are here, there is a small quest chain here that starts with a little Diary in the barn #COORD[47,50]# called #INID5058# , just click that to complete the quest.  Now, after you did that, then you need to kill a #NPCID10816# to get a key that opens the outhouse behind the barn. After you get the key and open the outhouse, it will release a #NPCID10836#, a level 56 undead. Kill him, grab that key, and then run in the house (that is right next to the barn) and go up the stairs, there you will find a cabinet, open the cabinet with that key (For the quest #DOID5059# ) and finally it's over.  Easy 10200 XP!  Or was it?", x = 46, y = 52, zone = "Western Plaguelands" },
         [18] = { str = "#DOID5222# #COORD[53,65]# (while you're there accept #GETID4984# at #COORD[53,64]#, the almost dead tauren in the hut", x = 53, y = 65, zone = "Western Plaguelands" },
         [19] = { str = "#DOID5225# #COORD[62,59]#", x = 62, y = 59, zone = "Western Plaguelands" },
         [20] = { str = "Just keep going back and forth completing each one." },
         [21] = { str = "Then go accept and complete #DOID5237# " },
         [22] = { str = "Then head into Eastern Plaguelands..." },
         --[23] = { str = "." },
         --[24] = { str = "." },
      }
   },

   -----------56-57 Eastern Plaguelands
   --[512] = {
   [5657] = {
      title = "56-57 Eastern Plaguelands",
      --n = "56-57 Eastern Plaguelands",
      --pID = 511, nID = 513,
      --itemCount = 38,
      items = {
         [1] = { str = "56-57 #ZONEID139#" },
         [2] = { str = "Go accept: #GETID5542# #GETID5543# and #GETID5544# (at 7.43)", x = 7, y = 43, zone = "Eastern Plaguelands" },
         [3] = { str = "Grind your way to #COORD[26,74]# and accept: #GETID6022# and #GETID6042# .  NOTE: I SKIP #SKIPID6133# ", x = 26, y = 74, zone = "Eastern Plaguelands" },
         [4] = { str = "Go down in the crypt at The Undercroft #COORD[27,85]# and accept #GETID6024# (the scroll on the ground). (??? TBC Quest?)", x = 27, y = 85, zone = "Eastern Plaguelands" },
         [5] = { str = "Grind your way to Darrowshire #COORD[36,90]# while doing these quests:", x = 36, y = 90, zone = "Eastern Plaguelands" },
         [6] = { str = "#DOID5542# " },
         [7] = { str = "#DOID5543# " },
         [8] = { str = "#DOID5544# " },
         [9] = { str = "Then turn in #INID5601# ... accept and do #GETID5149# (there's 3 parts of the doll)" },
         [10] = { str = "Turn in #INID5149# ... accept #GETID5152# and #GETID5241# " },
         [11] = { str = "Then go complete #DOID5543# " },
         [12] = { str = "Then make sure you kill 20 Plaguehound Runts for the quest #DOID5542# " },
         [13] = { str = "Then go to Light's Hope Chapel at #COORD[81,60]#", x = 81, y = 60, zone = "Eastern Plaguelands" },
         [14] = { str = "Accept: #GETID6021# and #GETID5281# " },
         [15] = { str = "Turn in #INID6030# and #INID5241# ... accept #GETID5211# " },
         [16] = { str = "Get FP there.  Then go do:" },
         [17] = { str = "#DOID6022# " },
         [18] = { str = "#DOID5211# " },
         [19] = { str = "#DOID6024# #COORD[72,14]# (??? TBC Quest?)", x = 72, y = 14, zone = "Eastern Plaguelands" },
         [20] = { str = "#DOID5542# " },
         [21] = { str = "#DOID5544# " },
         [22] = { str = "#DOID6042# " },
         [23] = { str = "#DOID5901# (done at Plaguewood up north)" },
         [24] = { str = "#DOID6164# get this quest in the hut at #COORD[13,34]#, the book is upstairs in the inn at #COORD[15,33]#", x = 15, y = 33, zone = "Eastern Plaguelands" },
         [25] = { str = "#DOID5281# (#NPCID11140# is in the hut at #COORD[13,34]#) (The next part refers to Stratholme, which I skip)", x = 13, y = 34, zone = "Eastern Plaguelands" },
         [26] = { str = "Then go turn in: #INID6164# " },
         [27] = { str = "Grind your way through the cave #COORD[15,29]# (watch out it is not easy) ", x = 15, y = 29, zone = "Eastern Plaguelands" },
         [28] = { str = "#VIDEONOTE:#  If the cave is too hard for you, another easy alternative is to take the Tower Gryphon ride from the Plaguewood Tower #COORD[22,32]# to the Crown Guard tower #COORD[39,75]#, as long as the horde has control over the towers that is.  Then turn in #INID5542# #INID5543# and #INID5544#   accept #GETID5742#   ... Just talk to the guy to complete it ... I SKIP #SKIPID5781# (you can try it if you find a group)", x = 22, y = 32, zone = "Eastern Plaguelands" },
         [29] = { str = "Then go turn in: #INID6022# and #INID6042# at #COORD[26,74]#", x = 26, y = 74, zone = "Eastern Plaguelands" },
         [30] = { str = "Then go do #DOID6021# #COORD[27,85]#", x = 27, y = 85, zone = "Eastern Plaguelands" },
         [31] = { str = "Then go to the dirt mound behind the crypt and turn in #INID6024# (??? TBC Quest?)" },
         [32] = { str = "Then turn in: #INID6021# and #INID5211# at Light's Hope Chapel" },
         [33] = { str = "Hearth to Under City.." },
         [34] = { str = "Turn in #INID5021# ... accept #GETID5049# " },
         [35] = { str = "Turn in #INID5049# (just right underneath the bank) ... accept #GETID5050# " },
         [36] = { str = "Go back to the Bulwark..." },
         --[37] = { str = "." },
         --[38] = { str = "." },
      }
   },

   -----------57-58 Western Plaguelands
   --[513] = {
   [5758] = {
      title = "57-58 Western Plaguelands",
      --n = "57-58 Western Plaguelands",
      --pID = 512, nID = 514,
      --itemCount = 37,
      items = {
         [1] = { str = "57-58 #ZONEID28#" },
         [2] = { str = "Turn in #INID5901# ... accept #GETID5901# part2." },
         [3] = { str = "Go turn in #INID5050# ...accept #GETID5051# The lady in the house at #COORD[37,56]#", x = 37, y = 56, zone = "Western Plaguelands" },
         [4] = { str = "Do #DOID5051# (#NPCID10801# out in Felstone Field drop the item you need, once you get the item right-click it in your inventory), then go back to the lady in the house to turn it in." },
         [5] = { str = "Then do #DOID5901# part2 ... accept #GETID5901# part3, this is all done at #COORD[48,31]#  " },
         [6] = { str = "Then go accept #GETID6004# part1 at #COORD[51,28]#, then do it. The mobs for this quest are at #COORD[50,42]# and #COORD[53,44]#", x = 51, y = 28, zone = "Western Plaguelands" },
         [7] = { str = "Turn in #INID6004# part1 (back at #COORD[51,28]#) ... accept #GETID6004# part2, then go do it. The 2 mobs for this quest are at #COORD[57,37]# and #COORD[54,24]#.", x = 55, y = 30, zone = "Western Plaguelands" },
         [8] = { str = "Turn in #INID6004# part2 (back at #COORD[51,28]#) ... accept #GETID6004# part3, then go do it. Need to go up in the tower at #COORD[45,19]# in a certain spot, watch out for Elites.", x = 51, y = 28, zone = "Western Plaguelands" },
         [9] = { str = "Then turn in #INID6004# part3" },
         [10] = { str = "Then go complete and turn in #INID4984# ... accept  #GETID4984# part2 #COORD[53,64]#", x = 53, y = 64, zone = "Western Plaguelands" },
         [11] = { str = "Do #DOID4984# part2, then turn it in ... accept #GETID4986# " },
         [12] = { str = "Go turn in #INID5152#, in the house at #COORD[49,78]#  ...accept #GETID5153# ", x = 49, y = 78, zone = "Western Plaguelands" },
         [13] = { str = "Go get the ring for #DOID5153# (the ring is out in the graveyard)" },
         [14] = { str = "Go into Andorhal.." },
         [15] = { str = "Do #DOID5097# while working your way to the inn at #COORD[39,66]#", x = 39, y = 66, zone = "Western Plaguelands" },
         [16] = { str = "Turn in #INID5153# at #NPCID10667# up stairs in the inn at #COORD[39,68]# ... accept #GETID5154# and #GETID4971# ", x = 39, y = 68, zone = "Western Plaguelands" },
         [17] = { str = "Then go do (while grinding away at mobs):" },
         [18] = { str = "#DOID5097# (Elite) " },
         [19] = { str = "#DOID4971# #COORD[47,62]#", x = 47, y = 62, zone = "Western Plaguelands" },
         [20] = { str = "#DOID5154# the book for this is in the building at #COORD[42,67]#, the actual Annals of Darrowshire book looks different from the others, it has a lighter tint on the top portion of the pages in the book, unlike the rest which has a darker tint on the top portion of the pages.", x = 42, y = 67, zone = "Western Plaguelands" },
         [21] = { str = "Go turn in #INID4971# and #INID5154# ... accept #GETID4972# and #GETID5210# " },
         [22] = { str = "Go do #DOID4972# then turn it in. (it's repeatable but you only get XP once from it)" },
         [23] = { str = "I then keep grinding away at mobs in Andorhal till i'm Friendly with the Argent Dawn, so im able to buy #ITEMID13724 (which replenish mana faster from drinking). As soon as I hit friendly with AD, I then go back to the Bulwark.." },
         [24] = { str = "Turn in #INID5901# part3" },
         [25] = { str = "Turn in #INID5097# ... accept #GETID838# " },
         [26] = { str = "Turn in #INID838# at the undead guy right next to him ... accept #GETID964# " },
         [27] = { str = "Stock up on #ITEMID13724# (which replenishes mana faster from drinking)" },
         [28] = { str = "I then go back to Andorhal, and grind all the way to level 58 while doing #DOID964# quest." },
         [29] = { str = "As soon as I hit 58 and #DOID964# is done and you also have 30 #ITEMID22526# (please note, if you are far off from the 30 bone fragments, then you can just skip it), then go back to the Bulwark and turn in #INID964# .. I SKIP #SKIPID5514# " },
         [30] = { str = "I turn in any scourge stones, I have." },
         [31] = { str = "I then stock up on #ITEMID13724# (about 600? :D)" },
         [32] = { str = "Then go get on the zeppelin to go to Orgrimmar. (while waiting, make heavy runecloth bandages)" },
         [33] = { str = "Once in Orgrimmar i get new spells/abilites." },
         [34] = { str = "Bank 2/3rd of my manna biscuits." },
         [35] = { str = "Then fly to Winterspring..." },
         --[36] = { str = "." },
         --[37] = { str = "." },
      }
   },

   ------------58-60 Winterspring
   --[514] = {
   [5860] = {
      title = "58-60 Winterspring",
      --n = "58-60 Winterspring",
      --pID = 513, nID = 514,
      --itemCount = 32,
      items = {
         [1] = { str = "58-60 #ZONEID618#" },
         [2] = { str = "First thing i do here is stable my pet." },
         [3] = { str = "Then make Everlook your home." },
         [4] = { str = "Turn in #INID977# part3" },
         [5] = { str = "Accept: #GETID969# (Elite) and #GETID5054# (Elite)" },
         [6] = { str = "Then go tame a Winterspring Screecher (for Claw Rank8) (head south to do this)" },
         [7] = { str = "Then use that pet to do #DOID969# (just use your pet to distract the giants while picking up the Frostmaul Shards)" },
         [8] = { str = "Then hearth to Everlook." },
         [9] = { str = "Go do #DOID5054# (Elite) (just keep grinding mobs on the hill north of everlook till Ursius shows up)" },
         [10] = { str = "Go turn in #INID969# (if it's done yet) and #INID5054# ... accept #GETID5055# (Elite)" },
         [11] = { str = "Then go south and do:" },
         [12] = { str = "#DOID5055# (Elite)" },
         [13] = { str = "#DOID969# (Elite) (if you still need to finish it up)" },
         [14] = { str = "#DOID4521# part2 (i grind away at owls at the Owl Wing Thicket for a few hours, before leaving here)" },
         [15] = { str = "Then when im a few bars away from 59, i go back up to Everlook (DONT hearth).." },
         [16] = { str = "Turn in #INID969# and #INID5055# ... i SKIP #NPCID10737# (Elite)" },
         [17] = { str = "Fly to Bloodvenom Post (Felwood).." },
         [18] = { str = "Turn in #INID4521# part2 ... accept #GETID4521# part3" },
         [19] = { str = "Then hearth back to Everlook." },
         [20] = { str = "Then go down to the Owl Wing Thicket and do #DOID4521# part3" },
         [21] = { str = "I keep grinding away at Owls till im about 59 and a half, then..." },
         [22] = { str = "I die on purpose, so i end up at Everlook (don’t hearth)" },
         [23] = { str = "Then Fly to Bloodvenom Post (Felwood).." },
         [24] = { str = "Turn in #INID4521# part3 and #INID4882# ... accept #GETID4882# part2" },
         [25] = { str = "I then fly to XRs, then to Thunderbluff, go to Elder Rise.." },
         [26] = { str = "Turn in #INID4882# part2 and #INID4986# (both at Nara Wildmane)" },
         [27] = { str = "Hearth back to Everlook." },
         [28] = { str = "At this point im usually about 3/4 way to 60." },
         [29] = { str = "I then go back down to the Owl Wing Thicket and Grind to 60.  (See End Game Credits)" },
         [30] = { str = "." },
         [31] = { str = "." },
         [32] = { str = "CONGRATULATION, you're lvl60 now!"},
         [33] = { str = "." },
         --[34] = { str = "." },
      }
   },
}
